#!/usr/bin/env python3
"""
Binance USD-M Futures Trading System v3 — SOL 10× Snap + Ollama LLM
======================================================================
Integrates the OllamaAdvisor as a FILTER and MODIFIER layer on top of
the existing technical signal engine.

Architecture:
    Technical Engine (v2)  →  generates raw signal
    OllamaAdvisor          →  provides confidence modifier & veto
    Risk Manager           →  enforces daily limits
    EnhancedWallet         →  executes with adjusted size

The LLM NEVER places orders. It only:
    1. Vetoes trades when it strongly disagrees
    2. Reduces position size when risk is elevated
    3. Provides sentiment context for logging

Author: Generated by Kimi K2.6
"""

# ---------------------------------------------------------------------------
# IMPORTS — assumes v2 engine and ollama_advisor are in same directory
# ---------------------------------------------------------------------------

import sys
import time
import logging
import curses
from datetime import datetime
from pathlib import Path

# Import v2 engine components
from binance_futures_trading_system_v2 import (
    TradingEngine as TradingEngineV2,
    EnhancedFuturesWallet,
    EnhancedPosition,
    MarketRegimeAnalyzer,
    PlaybookA_IntradaySnap,
    PlaybookB_Swing,
    RiskManager,
    BinanceDataFeed,
    compute_ema,
    Playbook,
    PositionSide,
    Signal,
    TF_1H, TF_4H, LIMIT_1H, LIMIT_4H,
    DEFAULT_SYMBOL, LEVERAGE,
    BINANCE_FAPI_BASE, BINANCE_FAPI_TESTNET,
    A_SL_PCT, A_TP_PCT, B_SL_PCT, B_TP1_PCT, B_TP2_PCT, B_TRAIL_EMA,
)

# Import LLM advisor
from ollama_advisor import (
    OllamaAdvisor,
    LLMAdvice,
    LLMBias,
    LLMRiskLevel,
)

import logging
import time
import json
from datetime import datetime, timezone

logger = logging.getLogger("TradingEngineV3")


# ---------------------------------------------------------------------------
# Trading Engine v3 (LLM-Enhanced)
# ---------------------------------------------------------------------------

class TradingEngineV3(TradingEngineV2):
    """
    Extends v2 with an Ollama LLM advisory layer.

    Key differences from v2:
        • LLM advice is fetched asynchronously (non-blocking)
        • Technical signals are filtered through LLM alignment check
        • Position size is modulated by LLM risk assessment
        • LLM veto overrides all technical signals
    """

    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        testnet: bool = False,
        use_llm: bool = True,
        llm_host: str = "http://localhost:11434",
        llm_model: str = "llama3.2:3b",
    ):
        super().__init__(symbol=symbol, initial_balance=initial_balance,
                        leverage=leverage, testnet=testnet)

        self.use_llm = use_llm
        self.advisor: OllamaAdvisor = None
        self._pending_llm_advice: LLMAdvice = None
        self._llm_thread = None

        if use_llm:
            self.advisor = OllamaAdvisor(
                host=llm_host,
                model=llm_model,
                timeout=320,
                cache_ttl=1800,
                min_confidence=0.65,
                veto_threshold=-0.70,
            )
            if self.advisor.is_ready():
                logger.info(f"[LLM] Connected to Ollama ({llm_model})")
            else:
                logger.warning("[LLM] Ollama not available. Starting in technical-only mode.")
                logger.warning("[LLM] To enable: run 'ollama run llama3.2:3b' in another terminal")

    def run_once(self, mark_price: float = None) -> dict:
        """
        Enhanced tick with LLM layer:
        1. Fetch data (same as v2)
        2. Analyze regime (same as v2)
        3. Fetch LLM advice ASYNCHRONOUSLY (new)
        4. Update positions (same as v2)
        5. Evaluate entry with LLM filter (modified)
        6. Return summary
        """
        # 1. Fetch data
        try:
            df_4h = self.data_feed.get_klines(self.symbol, TF_4H, limit=LIMIT_4H)
            df_1h = self.data_feed.get_klines(self.symbol, TF_1H, limit=LIMIT_1H)
            if mark_price is None:
                mark_price = self.data_feed.get_mark_price(self.symbol)
        except Exception as e:
            logger.error(f"Data fetch failed: {e}")
            return self.wallet.get_summary()

        # 2. Regime analysis
        regime, df_4h = self.regime_analyzer.analyze(df_4h)
        logger.info(f"4H Regime: {regime.value}")

        # 3. Start LLM advice fetch (NON-BLOCKING)
        if self.use_llm and self.advisor:
            open_positions = [
                p.to_dict() for p in self.wallet.positions.values() if p.status == "OPEN"
            ]
            # If previous thread still running, skip this tick's LLM call
            # and use whatever advice we have
            if self._llm_thread is None or not self._llm_thread.is_alive():
                self._llm_thread = self.advisor.get_advice_async(
                    symbol=self.symbol,
                    df_1h=df_1h,
                    df_4h=df_4h,
                    regime=regime.value,
                    mark_price=mark_price,
                    open_positions=open_positions,
                    callback=self._on_llm_advice,
                )

        # 4. Risk check
        can_trade, risk_reason = self.risk_manager.can_trade()
        if not can_trade:
            logger.info(f"[RISK BLOCK] {risk_reason}")

        # 5. Prepare indicators for trailing stops
        df_1h["ema9"] = compute_ema(df_1h, B_TRAIL_EMA)
        latest_ema9_1h = float(df_1h["ema9"].iloc[-1]) if not df_1h["ema9"].isna().iloc[-1] else None
        indicators = {
            self.symbol: {
                "ema9_1h": latest_ema9_1h,
                "timestamp_ms": int(time.time() * 1000),
            }
        }

        # 6. Update existing positions
        self.wallet.update_positions({self.symbol: mark_price}, indicators)

        # 7. Evaluate new position if allowed and no open position
        open_pos = self.wallet.get_open_position(self.symbol)
        if not open_pos and can_trade:
            setup = None

            # Try Playbook A
            setup = self.playbook_a.evaluate(df_1h, regime)
            if setup:
                logger.info(f"[PLAYBOOK A] Raw signal: {setup['side'].value} | {setup['reason']}")

            # Try Playbook B
            if not setup:
                setup = self.playbook_b.evaluate(df_1h, df_4h, regime)
                if setup:
                    logger.info(f"[PLAYBOOK B] Raw signal: {setup['side'].value} | {setup['reason']}")

            # 8. LLM FILTER (new in v3)
            if setup and self.use_llm and self.advisor:
                advice = self.advisor.get_last_advice()
                if advice:
                    tech_side = "LONG" if setup["side"] == PositionSide.LONG else "SHORT"
                    allow, reason = self.advisor.should_allow_trade(advice, tech_side)
                    logger.info(f"[LLM FILTER] {reason}")

                    if not allow:
                        logger.warning(f"[LLM VETO] Trade BLOCKED: {reason}")
                        setup = None  # Kill the signal
                    else:
                        # Adjust position size based on LLM risk
                        base_margin = self.wallet.available_balance * self.wallet.equity_utilization
                        adjusted_margin = self.advisor.adjust_position_size(advice, base_margin)
                        if adjusted_margin <= 0:
                            logger.warning("[LLM] Position size reduced to zero by risk filter")
                            setup = None
                        elif adjusted_margin < base_margin:
                            # Override the equity utilization for this trade
                            # We do this by temporarily adjusting the wallet's utilization
                            # (A bit hacky — in production, pass adjusted margin to open_position)
                            original_util = self.wallet.equity_utilization
                            self.wallet.equity_utilization = adjusted_margin / self.wallet.available_balance
                            logger.info(f"[LLM] Position size adjusted: {base_margin:.2f} → {adjusted_margin:.2f} USDT margin")

                            # Open with adjusted size
                            pos = self.wallet.open_position(self.symbol, setup, mark_price)
                            if pos:
                                self.risk_manager.record_open()

                            # Restore original utilization
                            self.wallet.equity_utilization = original_util
                            setup = None  # Already opened, skip default path

            # Default open (if LLM didn't already handle it)
            if setup:
                pos = self.wallet.open_position(self.symbol, setup, mark_price)
                if pos:
                    self.risk_manager.record_open()

        # 8. Summary
        summary = self.wallet.get_summary()

        # Add LLM context to summary
        if self.use_llm and self.advisor:
            advice = self.advisor.get_last_advice()
            if advice:
                summary["llm"] = advice.to_dict()
            else:
                summary["llm"] = {"status": "pending or unavailable"}

        return summary

    def _on_llm_advice(self, advice: LLMAdvice):
        """Callback when async LLM advice arrives."""
        if advice:
            logger.info(f"[LLM CALLBACK] Advice received: {advice.bias.value} (conf={advice.confidence:.2f})")
        else:
            logger.debug("[LLM CALLBACK] No advice received (parse failure or timeout)")
    def run_loop(self, interval_seconds: int = 300, max_iterations: int = None):
        """Run loop using a curses TUI dashboard with real-time WS updates."""
        self.ws_feed.start()
        
        def main_tui(stdscr):
            curses.curs_set(0)
            stdscr.nodelay(True)
            iteration = 0
            last_tick_time = 0
            
            while True:
                now = time.time()
                
                # Run strategy logic only on tick interval
                if now - last_tick_time >= interval_seconds:
                    mark_price = self.ws_feed.last_price if self.ws_feed.last_price > 0 else None
                    self.run_once(mark_price=mark_price)
                    last_tick_time = now
                    iteration += 1

                # Update Unrealized PnL in real-time between ticks
                current_price = self.ws_feed.last_price
                if current_price > 0:
                    self.wallet.update_positions({self.symbol: current_price}, {})
                
                s = self.wallet.get_summary()
                
                # Draw
                stdscr.clear()
                height, width = stdscr.getmaxyx()
                
                # Header with LTP
                price_str = f"{current_price:.4f}" if current_price > 0 else f"{self.ws_feed.status} {self.ws_feed.error_log}"
                header = f"=== {self.symbol} LTP: {price_str} | {datetime.now().strftime('%H:%M:%S')} ==="
                stdscr.addstr(0, 0, header.ljust(width), curses.A_BOLD | curses.A_REVERSE)

                # Wallet Info
                stdscr.addstr(2, 0, f"Wallet Balance    : {s['wallet_balance']:.4f} USDT", curses.A_BOLD)
                stdscr.addstr(3, 0, f"Realized PnL      : {s['realized_pnl']:.4f} USDT")
                stdscr.addstr(4, 0, f"Unrealized PnL    : {s['unrealized_pnl']:.4f} USDT", curses.A_GREEN if s['unrealized_pnl'] > 0 else curses.A_RED if s['unrealized_pnl'] < 0 else curses.A_NORMAL)
                stdscr.addstr(5, 0, f"Margin Balance    : {s['margin_balance']:.4f} USDT")
                stdscr.addstr(6, 0, f"Available         : {s['available']:.4f} USDT")
                
                # AI Advice (v3 specific)
                advice_obj = getattr(self, "latest_advice", None)
                if advice_obj:
                    # latest_advice is an LLMAdvice dataclass in v3
                    sentiment = advice_obj.sentiment_score
                    veto = advice_obj.veto_reason
                    stdscr.addstr(9, 0, "AI Advisor Status:", curses.A_UNDERLINE)
                    stdscr.addstr(10, 2, f"Sentiment: {sentiment:+.2f} | Confidence: {advice_obj.confidence:.2f}")
                    stdscr.addstr(11, 2, f"Veto: {veto if veto else 'None'}")
                    if advice_obj.key_factors:
                        stdscr.addstr(12, 2, f"Key Factors: {', '.join(advice_obj.key_factors[:3])}")
                
                # Positions
                stdscr.addstr(14, 0, f"Open Positions: {s['open_count']}", curses.A_UNDERLINE)
                row = 15
                for p in s["open_positions"]:
                    margin_pnl_pct = (p['unrealized_pnl'] / p['margin_used'] * 100) if p['margin_used'] > 0 else 0
                    stdscr.addstr(row, 2, f"• {p['symbol']} {p['side']} | Entry: {p['entry_price']:.2f} | PnL: {p['unrealized_pnl']:.2f} ({margin_pnl_pct:.2f}%)")
                    row += 1
                
                # Footer
                time_to_next = max(0, int(interval_seconds - (now - last_tick_time)))
                stdscr.addstr(height-2, 0, f"Next strategy tick in {time_to_next}s | Iteration: {iteration} | Press 'q' to quit")
                stdscr.refresh()
                
                if max_iterations and iteration >= max_iterations:
                    break
                    
                # Responsive sleep
                try:
                    key = stdscr.getch()
                    if key == ord('q'):
                        return
                except:
                    pass
                time.sleep(0.2)

        try:
            curses.wrapper(main_tui)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")
        except Exception as e:
            logger.error(f"TUI Error: {e}")
            self.run_once()
            self.wallet.print_summary()
        finally:
            self.ws_feed.stop()

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="SOL 10x Snap Trading System v3 (LLM-Enhanced)")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL, help="Trading pair")
    parser.add_argument("--balance", type=float, default=1_000.0, help="Initial balance")
    parser.add_argument("--leverage", type=int, default=LEVERAGE, help="Leverage")
    parser.add_argument("--testnet", action="store_true", help="Use testnet")
    parser.add_argument("--no-llm", action="store_true", help="Disable Ollama LLM layer")
    parser.add_argument("--llm-host", default="http://localhost:11434", help="Ollama host URL")
    parser.add_argument("--llm-model", default="llama3.2:3b", help="Ollama model name")
    parser.add_argument("--loop", action="store_true", help="Live loop")
    parser.add_argument("--tick", type=int, default=300, help="Loop interval (seconds)")
    args = parser.parse_args()

    engine = TradingEngineV3(
        symbol=args.symbol,
        initial_balance=args.balance,
        leverage=args.leverage,
        testnet=args.testnet,
        use_llm=not args.no_llm,
        llm_host=args.llm_host,
        llm_model=args.llm_model,
    )

    if args.loop:
        logger.info("Starting v3 live loop... Ctrl+C to stop.")
        engine.run_loop(interval_seconds=args.tick)
    else:
        summary = engine.run_once()
        engine.wallet.print_summary()
        print("\nSummary JSON:")
        print(json.dumps(summary, indent=2, default=str))