#!/usr/bin/env python3
"""
Binance USD-M Futures Trading System v2 — SOL 10× Snap
=========================================================
A production-grade automated trading system implementing the
multi-timeframe "SOL 10× Snap" strategy:

    • 4H Trend Bias + Market Regime Filter
    • Playbook A: Intraday Snap (6–16h, 1.0% TP, 0.7% SL)
    • Playbook B: Swing (24–48h, scaled exits, 1.2% SL, trail)
    • Risk Manager: max 2 trades/day, max 2 consecutive losses
    • 10× leverage, 50% equity utilization per trade

Author: Generated by Kimi K2.6
"""

import os
import json
import time
import logging
from datetime import datetime, timezone, timedelta, date
from dataclasses import dataclass, field, asdict
from typing import Callable, Dict, List, Optional, Tuple, Literal
from enum import Enum
from pathlib import Path

import pandas as pd
import numpy as np
import requests

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BINANCE_FAPI_BASE = "https://fapi.binance.com"
BINANCE_FAPI_TESTNET = "https://demo-fapi.binance.com"

# Account & Leverage
LEVERAGE = 10
EQUITY_UTILIZATION = 0.50
CATASTROPHIC_SL_PCT = -0.50

# Playbook A — Intraday Snap
A_SL_PCT = 0.007          # 0.7% price stop  → 7% margin loss
A_TP_PCT = 0.010          # 1.0% price target → 10% margin profit
A_TIME_H = 18             # 18-hour time stop
A_VOL_MULT = 1.20         # Volume ≥ 120% of 20-candle avg
A_RSI_LO = 40
A_RSI_HI = 60
A_EMA = 21                # Pullback to 1H EMA21

# Playbook B — Swing
B_SL_PCT = 0.012          # 1.2% price stop  → 12% margin loss
B_TP1_PCT = 0.010         # Close 50% at +1.0%
B_TP2_PCT = 0.020         # Close 25% at +2.0%
B_TIME_H = 48             # 48-hour time stop
B_VOL_MULT = 1.50         # Volume ≥ 150% of 20-candle avg
B_BODY_MIN = 0.012        # Breakout candle body ≥ 1.2%
B_RSI_LONG_LO, B_RSI_LONG_HI = 45, 65
B_RSI_SHORT_LO, B_RSI_SHORT_HI = 35, 55
B_TRAIL_EMA = 9           # Trail runner on 1H EMA9

# Risk Manager
MAX_DAILY_TRADES = 2
MAX_CONSEC_LOSS = 2

# Data
DEFAULT_SYMBOL = "SOLUSDT"
TF_4H = "4h"
TF_1H = "1h"
LIMIT_4H = 100
LIMIT_1H = 150

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("SOL10xSnap")

DATA_DIR = Path.home() / ".crypto_trader"
DATA_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"

class PositionSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class Signal(Enum):
    LONG = 1
    SHORT = -1
    NEUTRAL = 0

class MarketRegime(Enum):
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGING = "RANGING"
    CHOP = "CHOP"

class Playbook(Enum):
    INTRADAY = "INTRADAY"
    SWING = "SWING"


# ---------------------------------------------------------------------------
# Enhanced Position (supports partial closes, trailing, time stops)
# ---------------------------------------------------------------------------

@dataclass
class EnhancedPosition:
    symbol: str
    side: PositionSide
    playbook: Playbook
    entry_price: float
    original_quantity: float
    remaining_quantity: float
    notional: float
    margin_used: float
    leverage: int
    open_time: int

    # Dynamic levels
    sl_price: float
    tp_levels: List[dict] = field(default_factory=list)   # [{"price": x, "pct": 0.5, "hit": False}, ...]
    trailing_active: bool = False
    trailing_stop_price: Optional[float] = None
    time_stop_hours: int = A_TIME_H

    # State
    unrealized_pnl: float = 0.0
    partial_realized_pnl: float = 0.0
    status: Literal["OPEN", "CLOSED"] = "OPEN"
    close_time: Optional[int] = None
    close_price: Optional[float] = None   # price at which position was closed
    close_reason: Optional[str] = None

    def update_pnl(self, mark_price: float):
        if self.status != "OPEN":
            return
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (mark_price - self.entry_price) * self.remaining_quantity
        else:
            self.unrealized_pnl = (self.entry_price - mark_price) * self.remaining_quantity

    @property
    def total_realized_pnl(self) -> float:
        return self.partial_realized_pnl + (self.unrealized_pnl if self.status == "CLOSED" else 0)

    @property
    def current_margin_pnl_pct(self) -> float:
        if self.margin_used == 0:
            return 0.0
        return self.unrealized_pnl / self.margin_used

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "side": self.side.value,
            "playbook": self.playbook.value,
            "entry_price": self.entry_price,
            "original_quantity": self.original_quantity,
            "remaining_quantity": self.remaining_quantity,
            "notional": self.notional,
            "margin_used": self.margin_used,
            "leverage": self.leverage,
            "open_time": self.open_time,
            "sl_price": self.sl_price,
            "tp_levels": self.tp_levels,
            "trailing_active": self.trailing_active,
            "trailing_stop_price": self.trailing_stop_price,
            "time_stop_hours": self.time_stop_hours,
            "unrealized_pnl": self.unrealized_pnl,
            "partial_realized_pnl": self.partial_realized_pnl,
            "status": self.status,
            "close_time": self.close_time,
            "close_price": self.close_price,
            "close_reason": self.close_reason,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "EnhancedPosition":
        data["side"] = PositionSide(data["side"])
        data["playbook"] = Playbook(data["playbook"])
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# Binance Data Feed (multi-timeframe)
# ---------------------------------------------------------------------------

class BinanceDataFeed:
    def __init__(self, base_url: str = BINANCE_FAPI_BASE):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "User-Agent": "SOL10xSnap/2.0",
        })

    def _get(self, endpoint: str, params: dict = None) -> dict:
        url = f"{self.base_url}/fapi/{endpoint}"
        try:
            resp = self.session.get(url, params=params, timeout=15)
            resp.raise_for_status()
            return resp.json()
        except requests.HTTPError as e:
            status = e.response.status_code if e.response is not None else None
            if status == 418:
                logger.critical("Binance IP ban (418) detected. Sleeping 120s before retry.")
                time.sleep(120)
            elif status == 429:
                logger.warning("Binance rate limit (429) detected. Sleeping 60s before retry.")
                time.sleep(60)
            raise
        except requests.RequestException as e:
            logger.error(f"Request failed: {e}")
            raise

    def get_klines(self, symbol: str, interval: str, limit: int = 150,
                   start_time: int = None, end_time: int = None) -> pd.DataFrame:
        params = {
            "symbol": symbol.upper(),
            "interval": interval,
            "limit": limit,
        }
        if start_time:
            params["startTime"] = start_time
        if end_time:
            params["endTime"] = end_time

        data = self._get("v1/klines", params)
        if not data:
            raise ValueError("No kline data returned")

        df = pd.DataFrame(data, columns=[
            "open_time", "open", "high", "low", "close", "volume",
            "close_time", "quote_volume", "trades",
            "taker_buy_base", "taker_buy_quote", "ignore",
        ])
        numeric_cols = ["open", "high", "low", "close", "volume",
                        "quote_volume", "taker_buy_base", "taker_buy_quote"]
        df[numeric_cols] = df[numeric_cols].astype(float)
        df["open_time"] = pd.to_datetime(df["open_time"], unit="ms", utc=True)
        df["close_time"] = pd.to_datetime(df["close_time"], unit="ms", utc=True)
        return df

    def get_mark_price(self, symbol: str) -> float:
        data = self._get("v1/premiumIndex", {"symbol": symbol.upper()})
        return float(data["markPrice"])


# ---------------------------------------------------------------------------
# Technical Indicators
# ---------------------------------------------------------------------------

def compute_ema(df: pd.DataFrame, period: int, col: str = "close") -> pd.Series:
    return df[col].ewm(span=period, adjust=False).mean()

def compute_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    delta = series.diff()
    gain = delta.where(delta > 0, 0.0)
    loss = (-delta.where(delta < 0, 0.0))
    avg_gain = gain.ewm(alpha=1/period, min_periods=period).mean()
    avg_loss = loss.ewm(alpha=1/period, min_periods=period).mean()
    rs = avg_gain / avg_loss
    return 100 - (100 / (1 + rs))

def compute_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
    tr1 = df["high"] - df["low"]
    tr2 = (df["high"] - df["close"].shift(1)).abs()
    tr3 = (df["low"] - df["close"].shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    return tr.rolling(period).mean()

def find_pivots(df: pd.DataFrame, window: int = 2) -> Tuple[List[Tuple[int, float]], List[Tuple[int, float]]]:
    """Return (pivot_highs, pivot_lows) as list of (index, price)."""
    ph, pl = [], []
    highs = df["high"].values
    lows = df["low"].values
    for i in range(window, len(df) - window):
        if highs[i] == max(highs[i-window:i+window+1]):
            ph.append((i, highs[i]))
        if lows[i] == min(lows[i-window:i+window+1]):
            pl.append((i, lows[i]))
    return ph, pl


# ---------------------------------------------------------------------------
# Market Regime Analyzer (4H)
# ---------------------------------------------------------------------------

class MarketRegimeAnalyzer:
    """Determines trend bias from 4H structure."""

    def analyze(self, df: pd.DataFrame) -> Tuple[MarketRegime, pd.DataFrame]:
        if len(df) < 30:
            return MarketRegime.CHOP, df

        df = df.copy()
        df["ema9"] = compute_ema(df, 9)
        df["ema21"] = compute_ema(df, 21)
        df["rsi"] = compute_rsi(df["close"], 14)

        latest = df.iloc[-1]
        price = latest["close"]
        ema9, ema21 = latest["ema9"], latest["ema21"]

        # EMA distance as % of price
        ema_dist = abs(ema9 - ema21) / price

        # Pivot structure
        ph, pl = find_pivots(df, window=2)

        # Check HH/HL or LH/LL using last 3 pivots
        hh_hl = False
        lh_ll = False
        if len(ph) >= 3 and len(pl) >= 3:
            last_ph = [p[1] for p in ph[-3:]]
            last_pl = [p[1] for p in pl[-3:]]
            if last_ph[0] < last_ph[1] < last_ph[2] and last_pl[0] < last_pl[1] < last_pl[2]:
                hh_hl = True
            if last_ph[0] > last_ph[1] > last_ph[2] and last_pl[0] > last_pl[1] > last_pl[2]:
                lh_ll = True

        # Regime classification
        if ema9 > ema21 and price > ema21 and hh_hl:
            regime = MarketRegime.TRENDING_UP
        elif ema9 < ema21 and price < ema21 and lh_ll:
            regime = MarketRegime.TRENDING_DOWN
        elif ema_dist < 0.005:
            regime = MarketRegime.CHOP
        else:
            # Check if ranging (oscillating between levels)
            recent = df.iloc[-20:]
            range_pct = (recent["high"].max() - recent["low"].min()) / price
            if range_pct < 0.08 and not hh_hl and not lh_ll:
                regime = MarketRegime.RANGING
            else:
                # Default to weak trend direction if EMAs aligned but no structure
                if ema9 > ema21:
                    regime = MarketRegime.TRENDING_UP
                elif ema9 < ema21:
                    regime = MarketRegime.TRENDING_DOWN
                else:
                    regime = MarketRegime.CHOP

        return regime, df


# ---------------------------------------------------------------------------
# Playbook A — Intraday Snap (1H)
# ---------------------------------------------------------------------------

class PlaybookA_IntradaySnap:
    """
    6–16 hour hold.
    Entry: 1H pullback to EMA21 within 4H trend + volume + RSI + rejection candle.
    """

    def evaluate(
        self,
        df_1h: pd.DataFrame,
        regime: MarketRegime,
    ) -> Optional[Dict]:
        if len(df_1h) < 30:
            return None

        # Only trade in direction of 4H trend
        if regime == MarketRegime.TRENDING_UP:
            direction = PositionSide.LONG
        elif regime == MarketRegime.TRENDING_DOWN:
            direction = PositionSide.SHORT
        elif regime == MarketRegime.RANGING:
            # In ranging markets, trade both sides at extremes (simplified: skip for now)
            return None
        else:
            return None

        df = df_1h.copy()
        df["ema21"] = compute_ema(df, A_EMA)
        df["rsi"] = compute_rsi(df["close"], 14)
        df["vol_avg20"] = df["volume"].rolling(20).mean()

        # Current and previous candle
        curr = df.iloc[-1]
        prev = df.iloc[-2]
        price = curr["close"]

        # Volume check
        if curr["volume"] < curr["vol_avg20"] * A_VOL_MULT:
            return None

        # RSI check
        rsi = curr["rsi"]
        if pd.isna(rsi) or not (A_RSI_LO <= rsi <= A_RSI_HI):
            return None

        # Pullback + Rejection logic
        ema21 = curr["ema21"]
        if pd.isna(ema21):
            return None

        if direction == PositionSide.LONG:
            # Pullback: price touched or went below EMA21, or within 0.3%
            pullback = (curr["low"] <= ema21 * 1.003) or (abs(price - ema21) / price < 0.003)
            if not pullback:
                return None
            # Rejection: lower wick >= 1.5x body OR bullish engulfing
            body = abs(curr["close"] - curr["open"])
            lower_wick = min(curr["open"], curr["close"]) - curr["low"]
            bullish_engulfing = (curr["close"] > prev["open"]) and (curr["open"] < prev["close"]) and (curr["close"] > curr["open"])
            if not (lower_wick >= body * 1.5 or bullish_engulfing):
                return None
            sl = price * (1 - A_SL_PCT)
            tp = price * (1 + A_TP_PCT)

        else:  # SHORT
            pullback = (curr["high"] >= ema21 * 0.997) or (abs(price - ema21) / price < 0.003)
            if not pullback:
                return None
            body = abs(curr["close"] - curr["open"])
            upper_wick = curr["high"] - max(curr["open"], curr["close"])
            bearish_engulfing = (curr["close"] < prev["open"]) and (curr["open"] > prev["close"]) and (curr["close"] < curr["open"])
            if not (upper_wick >= body * 1.5 or bearish_engulfing):
                return None
            sl = price * (1 + A_SL_PCT)
            tp = price * (1 - A_TP_PCT)

        return {
            "playbook": Playbook.INTRADAY,
            "side": direction,
            "entry_price": price,
            "sl_price": sl,
            "tp_price": tp,
            "time_stop_hours": A_TIME_H,
            "reason": f"PlaybookA: 1H pullback to EMA21 + vol + RSI({rsi:.1f})",
        }


# ---------------------------------------------------------------------------
# Playbook B — Swing (4H breakout + 1H retest)
# ---------------------------------------------------------------------------

class PlaybookB_Swing:
    """
    24–48 hour hold.
    Entry: 4H breakout with volume, 1H retest of broken level.
    Scaled exits: 50% at +1%, 25% at +2%, runner trails 1H EMA9.
    """

    def evaluate(
        self,
        df_1h: pd.DataFrame,
        df_4h: pd.DataFrame,
        regime: MarketRegime,
    ) -> Optional[Dict]:
        if len(df_4h) < 20 or len(df_1h) < 30:
            return None

        # Only trade in clear trend direction
        if regime == MarketRegime.TRENDING_UP:
            direction = PositionSide.LONG
        elif regime == MarketRegime.TRENDING_DOWN:
            direction = PositionSide.SHORT
        else:
            return None

        # 4H analysis
        df4 = df_4h.copy()
        df4["ema9"] = compute_ema(df4, 9)
        df4["ema21"] = compute_ema(df4, 21)
        df4["rsi"] = compute_rsi(df4["close"], 14)
        df4["vol_avg20"] = df4["volume"].rolling(20).mean()

        # Check last 4H candle for breakout
        c4 = df4.iloc[-1]
        p4 = df4.iloc[-2] if len(df4) > 1 else c4
        body_pct = abs(c4["close"] - c4["open"]) / c4["open"]

        if body_pct < B_BODY_MIN:
            return None
        if c4["volume"] < c4["vol_avg20"] * B_VOL_MULT:
            return None

        rsi_4h = c4["rsi"]
        if pd.isna(rsi_4h):
            return None

        # Breakout level = previous resistance/support (last 6 candles high/low)
        if direction == PositionSide.LONG:
            if not (c4["close"] > c4["open"] and c4["close"] > p4["high"]):
                return None
            if not (B_RSI_LONG_LO <= rsi_4h <= B_RSI_LONG_HI):
                return None
            breakout_level = df4.iloc[-7:-1]["high"].max()  # resistance before breakout
        else:
            if not (c4["close"] < c4["open"] and c4["close"] < p4["low"]):
                return None
            if not (B_RSI_SHORT_LO <= rsi_4h <= B_RSI_SHORT_HI):
                return None
            breakout_level = df4.iloc[-7:-1]["low"].min()

        # 1H retest check: current price is within 0.5% of breakout level
        # AND 1H candle closes back in breakout direction
        df1 = df_1h.copy()
        c1 = df1.iloc[-1]
        price = c1["close"]

        if direction == PositionSide.LONG:
            near_level = abs(price - breakout_level) / price < 0.005 or c1["low"] <= breakout_level * 1.005
            if not (near_level and c1["close"] > c1["open"]):
                return None
            sl = price * (1 - B_SL_PCT)
            tp1 = price * (1 + B_TP1_PCT)
            tp2 = price * (1 + B_TP2_PCT)
        else:
            near_level = abs(price - breakout_level) / price < 0.005 or c1["high"] >= breakout_level * 0.995
            if not (near_level and c1["close"] < c1["open"]):
                return None
            sl = price * (1 + B_SL_PCT)
            tp1 = price * (1 - B_TP1_PCT)
            tp2 = price * (1 - B_TP2_PCT)

        return {
            "playbook": Playbook.SWING,
            "side": direction,
            "entry_price": price,
            "sl_price": sl,
            "tp_levels": [
                {"price": tp1, "pct": 0.50, "hit": False, "label": "TP1"},
                {"price": tp2, "pct": 0.25, "hit": False, "label": "TP2"},
            ],
            "time_stop_hours": B_TIME_H,
            "reason": f"PlaybookB: 4H breakout + 1H retest | RSI(4H)={rsi_4h:.1f}",
        }


# ---------------------------------------------------------------------------
# Risk Manager
# ---------------------------------------------------------------------------

class RiskManager:
    """Enforces daily trade limits and consecutive loss stops."""

    def __init__(self, max_daily: int = MAX_DAILY_TRADES, max_consec: int = MAX_CONSEC_LOSS):
        self.max_daily = max_daily
        self.max_consec = max_consec
        self.daily_count = 0
        self.last_trade_date: Optional[date] = None
        self.consecutive_losses = 0
        self.state_file = DATA_DIR / "risk_manager_state.json"
        self._load_state()

    def _today(self) -> date:
        return datetime.now(timezone.utc).date()

    def can_trade(self) -> Tuple[bool, str]:
        today = self._today()
        if self.last_trade_date != today:
            self.daily_count = 0
            self.last_trade_date = today

        if self.daily_count >= self.max_daily:
            return False, f"Daily trade limit reached ({self.max_daily})"
        if self.consecutive_losses >= self.max_consec:
            return False, f"Consecutive loss limit reached ({self.max_consec}) — trading halted"
        return True, "OK"

    def record_open(self):
        today = self._today()
        if self.last_trade_date != today:
            self.daily_count = 0
            self.last_trade_date = today
        self.daily_count += 1
        self._save_state()

    def record_close(self, realized_pnl: float):
        if realized_pnl > 0:
            self.consecutive_losses = 0
        else:
            self.consecutive_losses += 1
        self._save_state()

    def _save_state(self):
        state = {
            "daily_count": self.daily_count,
            "last_trade_date": self.last_trade_date.isoformat() if self.last_trade_date else None,
            "consecutive_losses": self.consecutive_losses,
        }
        with open(self.state_file, "w") as f:
            json.dump(state, f)

    def _load_state(self):
        if not self.state_file.exists():
            return
        try:
            with open(self.state_file, "r") as f:
                state = json.load(f)
            self.daily_count = state.get("daily_count", 0)
            d = state.get("last_trade_date")
            self.last_trade_date = date.fromisoformat(d) if d else None
            self.consecutive_losses = state.get("consecutive_losses", 0)
        except Exception as e:
            logger.warning(f"RiskManager load failed: {e}")

    def reset(self):
        self.daily_count = 0
        self.consecutive_losses = 0
        self.last_trade_date = None
        if self.state_file.exists():
            self.state_file.unlink()


# ---------------------------------------------------------------------------
# Enhanced Futures Wallet
# ---------------------------------------------------------------------------

class EnhancedFuturesWallet:
    def __init__(
        self,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        equity_utilization: float = EQUITY_UTILIZATION,
        catastrophic_sl_pct: float = CATASTROPHIC_SL_PCT,
        state_file: str = "wallet_state.json",
    ):
        self.leverage = leverage
        self.equity_utilization = equity_utilization
        self.catastrophic_sl_pct = catastrophic_sl_pct
        self.state_file = DATA_DIR / state_file
        self.wallet_balance = initial_balance
        self.unrealized_pnl_total = 0.0
        self.realized_pnl_total = 0.0
        self.positions: Dict[str, EnhancedPosition] = {}
        self.position_history: List[dict] = []
        # Optional callback to notify external observers when a position closes.
        # Set by TradingEngine so RiskManager can update its consecutive-loss counter.
        self.on_position_closed: Optional[Callable[[float], None]] = None
        self._load_state()

    @property
    def margin_balance(self) -> float:
        return self.wallet_balance + self.unrealized_pnl_total

    @property
    def available_balance(self) -> float:
        used = sum(p.margin_used for p in self.positions.values() if p.status == "OPEN")
        return max(0.0, self.margin_balance - used)

    def get_open_position(self, symbol: str) -> Optional[EnhancedPosition]:
        pos = self.positions.get(symbol)
        return pos if pos and pos.status == "OPEN" else None

    def can_open(self, symbol: str) -> Tuple[bool, str]:
        if self.get_open_position(symbol):
            return False, f"Already have open position on {symbol}"
        if self.available_balance <= 0:
            return False, "No available balance"
        return True, "OK"

    def open_position(self, symbol: str, setup: dict, mark_price: float) -> Optional[EnhancedPosition]:
        can, reason = self.can_open(symbol)
        if not can:
            logger.info(f"[OPEN BLOCKED] {symbol}: {reason}")
            return None

        capital = self.available_balance * self.equity_utilization
        if capital <= 0:
            return None

        notional = capital * self.leverage
        entry = setup["entry_price"]
        qty = notional / entry
        margin = capital

        side = setup["side"]
        playbook = setup["playbook"]

        # Build TP levels
        tp_levels = setup.get("tp_levels", [])
        if not tp_levels and "tp_price" in setup:
            tp_levels = [{"price": setup["tp_price"], "pct": 1.0, "hit": False, "label": "TP"}]

        pos = EnhancedPosition(
            symbol=symbol,
            side=side,
            playbook=playbook,
            entry_price=entry,
            original_quantity=qty,
            remaining_quantity=qty,
            notional=notional,
            margin_used=margin,
            leverage=self.leverage,
            open_time=int(time.time() * 1000),
            sl_price=setup["sl_price"],
            tp_levels=tp_levels,
            time_stop_hours=setup.get("time_stop_hours", A_TIME_H),
        )
        pos.update_pnl(mark_price)
        self.positions[symbol] = pos

        logger.info(
            f"[POSITION OPENED] {symbol} {side.value} | Playbook={playbook.value} | "
            f"Qty={qty:.4f} @ {entry:.2f} | Margin={margin:.2f} | "
            f"SL={setup['sl_price']:.2f} | TP={tp_levels} | Reason: {setup['reason']}"
        )
        self._save_state()
        return pos

    def close_position(self, symbol: str, close_price: float, reason: str) -> Optional[EnhancedPosition]:
        pos = self.get_open_position(symbol)
        if not pos:
            return None

        pos.update_pnl(close_price)
        realized = pos.unrealized_pnl
        pos.unrealized_pnl = 0.0
        pos.status = "CLOSED"
        pos.close_time = int(time.time() * 1000)
        pos.close_price = close_price
        pos.close_reason = reason

        self.wallet_balance += realized
        self.realized_pnl_total += realized
        self.position_history.append(pos.to_dict())
        del self.positions[symbol]

        logger.info(
            f"[POSITION CLOSED] {symbol} {pos.side.value} | Playbook={pos.playbook.value} | "
            f"Close={close_price:.2f} | Realized={realized:.2f} | Reason={reason}"
        )
        self._save_state()

        # Notify RiskManager so it can update the consecutive-loss counter
        if self.on_position_closed is not None:
            self.on_position_closed(realized)

        return pos

    def partial_close(self, symbol: str, close_price: float, pct: float, reason: str) -> float:
        """Close a percentage of the position. Returns realized PnL from this slice."""
        pos = self.get_open_position(symbol)
        if not pos:
            return 0.0

        qty_to_close = pos.remaining_quantity * pct
        if qty_to_close <= 0:
            return 0.0

        if pos.side == PositionSide.LONG:
            pnl_slice = (close_price - pos.entry_price) * qty_to_close
        else:
            pnl_slice = (pos.entry_price - close_price) * qty_to_close

        pos.partial_realized_pnl += pnl_slice
        pos.remaining_quantity -= qty_to_close
        pos.notional = pos.remaining_quantity * pos.entry_price
        pos.margin_used = pos.notional / pos.leverage

        logger.info(
            f"[PARTIAL CLOSE] {symbol} {pos.side.value} | Closed {pct*100:.0f}% | "
            f"Qty={qty_to_close:.4f} | PnL={pnl_slice:.2f} | Reason={reason}"
        )

        if pos.remaining_quantity <= 0.0001:
            # Fully closed via partials
            return self.close_position(symbol, close_price, reason="FULL_VIA_PARTIALS")

        self._save_state()
        return pnl_slice

    def update_positions(self, mark_prices: Dict[str, float], indicators: Dict[str, dict]):
        """
        Update PnL, check TP/SL/Time/Trail/Catastrophic.
        indicators: symbol -> {"ema9_1h": float, "timestamp_ms": int}
        """
        indicator_ts = [
            v.get("timestamp_ms")
            for v in indicators.values()
            if isinstance(v, dict) and v.get("timestamp_ms") is not None
        ]
        now_ms = int(max(indicator_ts)) if indicator_ts else int(time.time() * 1000)

        for symbol, pos in list(self.positions.items()):
            if pos.status != "OPEN":
                continue

            mark = mark_prices.get(symbol)
            if mark is None:
                continue

            ind = indicators.get(symbol, {})
            pos.update_pnl(mark)
            pnl = pos.unrealized_pnl
            pnl_pct = pos.current_margin_pnl_pct

            # 1. Catastrophic SL (-50% margin)
            cat_sl = pos.margin_used * self.catastrophic_sl_pct
            if pnl <= cat_sl:
                self.close_position(symbol, mark, reason=f"CATASTROPHIC_SL ({pnl:.2f})")
                continue

            # 2. Playbook-specific TP/SL
            if pos.playbook == Playbook.INTRADAY:
                # Simple TP/SL
                if pos.side == PositionSide.LONG:
                    if mark >= pos.tp_levels[0]["price"]:
                        self.close_position(symbol, mark, reason=f"TP_HIT ({pnl:.2f})")
                        continue
                    if mark <= pos.sl_price:
                        self.close_position(symbol, mark, reason=f"SL_HIT ({pnl:.2f})")
                        continue
                else:
                    if mark <= pos.tp_levels[0]["price"]:
                        self.close_position(symbol, mark, reason=f"TP_HIT ({pnl:.2f})")
                        continue
                    if mark >= pos.sl_price:
                        self.close_position(symbol, mark, reason=f"SL_HIT ({pnl:.2f})")
                        continue

                # Time stop
                hours_open = (now_ms - pos.open_time) / 3_600_000
                if hours_open >= pos.time_stop_hours:
                    self.close_position(symbol, mark, reason=f"TIME_STOP ({hours_open:.1f}h)")
                    continue

            elif pos.playbook == Playbook.SWING:
                # Scaled exits
                for tp in pos.tp_levels:
                    if tp["hit"]:
                        continue
                    hit = False
                    if pos.side == PositionSide.LONG and mark >= tp["price"]:
                        hit = True
                    elif pos.side == PositionSide.SHORT and mark <= tp["price"]:
                        hit = True

                    if hit:
                        tp["hit"] = True
                        pct = tp["pct"]
                        self.partial_close(symbol, mark, pct, reason=f"{tp['label']} HIT")
                        # After TP1, move SL to breakeven
                        if tp["label"] == "TP1":
                            pos.sl_price = pos.entry_price
                            logger.info(f"[SL ADJUSTED] {symbol} SL moved to BREAKEVEN ({pos.entry_price:.2f})")
                        # After TP2, activate trailing
                        if tp["label"] == "TP2":
                            pos.trailing_active = True
                            logger.info(f"[TRAIL ACTIVE] {symbol} trailing stop on 1H EMA9")

                # Check SL (original or moved to BE)
                if pos.side == PositionSide.LONG and mark <= pos.sl_price:
                    self.close_position(symbol, mark, reason=f"SL_HIT ({pnl:.2f})")
                    continue
                elif pos.side == PositionSide.SHORT and mark >= pos.sl_price:
                    self.close_position(symbol, mark, reason=f"SL_HIT ({pnl:.2f})")
                    continue

                # Trailing stop
                if pos.trailing_active:
                    ema9 = ind.get("ema9_1h")
                    if ema9 is not None:
                        if pos.side == PositionSide.LONG and mark < ema9:
                            self.close_position(symbol, mark, reason=f"TRAIL_STOP (EMA9 {ema9:.2f})")
                            continue
                        elif pos.side == PositionSide.SHORT and mark > ema9:
                            self.close_position(symbol, mark, reason=f"TRAIL_STOP (EMA9 {ema9:.2f})")
                            continue

                # Time stop
                hours_open = (now_ms - pos.open_time) / 3_600_000
                if hours_open >= pos.time_stop_hours:
                    self.close_position(symbol, mark, reason=f"TIME_STOP ({hours_open:.1f}h)")
                    continue

        self.unrealized_pnl_total = sum(
            p.unrealized_pnl for p in self.positions.values() if p.status == "OPEN"
        )

    def get_summary(self) -> dict:
        open_pos = [p.to_dict() for p in self.positions.values() if p.status == "OPEN"]
        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "wallet_balance": round(self.wallet_balance, 4),
            "unrealized_pnl": round(self.unrealized_pnl_total, 4),
            "realized_pnl": round(self.realized_pnl_total, 4),
            "margin_balance": round(self.margin_balance, 4),
            "available": round(self.available_balance, 4),
            "open_count": len(open_pos),
            "open_positions": open_pos,
            "history_count": len(self.position_history),
        }

    def print_summary(self):
        s = self.get_summary()
        print("\n" + "=" * 65)
        print("  SOL 10× SNAP — WALLET SUMMARY")
        print("=" * 65)
        print(f"  Wallet Balance    : {s['wallet_balance']:.4f} USDT")
        print(f"  Unrealized PnL    : {s['unrealized_pnl']:.4f} USDT")
        print(f"  Realized PnL      : {s['realized_pnl']:.4f} USDT")
        print(f"  Margin Balance    : {s['margin_balance']:.4f} USDT")
        print(f"  Available         : {s['available']:.4f} USDT")
        print(f"  Open Positions    : {s['open_count']}")
        for p in s["open_positions"]:
            print(f"    → {p['symbol']} {p['side']} | Playbook={p['playbook']} | "
                  f"Entry={p['entry_price']:.2f} | RemQty={p['remaining_quantity']:.4f} | "
                  f"U-PnL={p['unrealized_pnl']:.4f} ({p['unrealized_pnl']/p['margin_used']*100:.2f}%)")
        print("=" * 65 + "\n")

    def _save_state(self):
        state = {
            "wallet_balance": self.wallet_balance,
            "realized_pnl_total": self.realized_pnl_total,
            "positions": {s: p.to_dict() for s, p in self.positions.items()},
            "position_history": self.position_history,
        }
        with open(self.state_file, "w") as f:
            json.dump(state, f, indent=2, default=str)

    def _load_state(self):
        if not self.state_file.exists():
            return
        try:
            with open(self.state_file, "r") as f:
                state = json.load(f)
            self.wallet_balance = state.get("wallet_balance", self.wallet_balance)
            self.realized_pnl_total = state.get("realized_pnl_total", 0.0)
            self.positions = {
                s: EnhancedPosition.from_dict(d)
                for s, d in state.get("positions", {}).items()
            }
            self.position_history = state.get("position_history", [])
            logger.info(f"Loaded wallet state from {self.state_file}")
        except Exception as e:
            logger.warning(f"Failed to load state: {e}")

    def reset(self):
        self.positions.clear()
        self.position_history.clear()
        self.wallet_balance = 1_000.0
        self.unrealized_pnl_total = 0.0
        self.realized_pnl_total = 0.0
        if self.state_file.exists():
            self.state_file.unlink()
        logger.info("Wallet state reset")


# ---------------------------------------------------------------------------
# Trading Engine
# ---------------------------------------------------------------------------

class TradingEngine:
    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        testnet: bool = False,
    ):
        self.symbol = symbol.upper()
        self.data_feed = BinanceDataFeed(
            base_url=BINANCE_FAPI_TESTNET if testnet else BINANCE_FAPI_BASE
        )
        self.regime_analyzer = MarketRegimeAnalyzer()
        self.playbook_a = PlaybookA_IntradaySnap()
        self.playbook_b = PlaybookB_Swing()
        self.risk_manager = RiskManager()
        self.wallet = EnhancedFuturesWallet(
            initial_balance=initial_balance,
            leverage=leverage,
            state_file=f"wallet_{self.symbol}_v2.json",
        )
        # Wire up RiskManager so it tracks wins/losses from auto-close events
        self.wallet.on_position_closed = self.risk_manager.record_close

    def run_once(self) -> dict:
        logger.info(f"--- Tick: {self.symbol} ---")

        # 1. Fetch multi-timeframe data
        try:
            df_4h = self.data_feed.get_klines(self.symbol, TF_4H, limit=LIMIT_4H)
            df_1h = self.data_feed.get_klines(self.symbol, TF_1H, limit=LIMIT_1H)
            mark_price = self.data_feed.get_mark_price(self.symbol)
        except Exception as e:
            logger.error(f"Data fetch failed: {e}")
            return self.wallet.get_summary()

        # 2. Analyze 4H regime
        regime, df_4h = self.regime_analyzer.analyze(df_4h)
        logger.info(f"4H Regime: {regime.value}")

        # 3. Risk check
        can_trade, risk_reason = self.risk_manager.can_trade()
        if not can_trade:
            logger.info(f"[RISK BLOCK] {risk_reason}")

        # 4. Prepare indicators for trailing stops
        df_1h["ema9"] = compute_ema(df_1h, B_TRAIL_EMA)
        latest_ema9_1h = float(df_1h["ema9"].iloc[-1]) if not pd.isna(df_1h["ema9"].iloc[-1]) else None
        indicators = {
            self.symbol: {
                "ema9_1h": latest_ema9_1h,
                "timestamp_ms": int(time.time() * 1000),
            }
        }

        # 5. Update existing positions (TP/SL/Trail/Time/Catastrophic)
        self.wallet.update_positions({self.symbol: mark_price}, indicators)

        # 6. Evaluate new position if allowed and no open position
        open_pos = self.wallet.get_open_position(self.symbol)
        if not open_pos and can_trade:
            setup = None

            # Try Playbook A first (higher frequency, tighter risk)
            setup = self.playbook_a.evaluate(df_1h, regime)
            if setup:
                logger.info(f"[PLAYBOOK A] Signal detected: {setup['side'].value} | {setup['reason']}")

            # If no Playbook A, try Playbook B (lower frequency, higher reward)
            if not setup:
                setup = self.playbook_b.evaluate(df_1h, df_4h, regime)
                if setup:
                    logger.info(f"[PLAYBOOK B] Signal detected: {setup['side'].value} | {setup['reason']}")

            if setup:
                pos = self.wallet.open_position(self.symbol, setup, mark_price)
                if pos:
                    self.risk_manager.record_open()

        # 7. Summary
        summary = self.wallet.get_summary()
        return summary

    def run_loop(self, interval_seconds: int = 300, max_iterations: int = None):
        """Run loop. Default 5-min ticks (align with 1H close for best results)."""
        iteration = 0
        try:
            while True:
                self.run_once()
                self.wallet.print_summary()
                iteration += 1
                if max_iterations and iteration >= max_iterations:
                    break
                time.sleep(interval_seconds)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")

    def backtest(self, days: int = 14) -> pd.DataFrame:
        """
        Walk-forward backtest on 1H data.
        For each 1H candle close, we look back at 4H alignment.
        """
        end_ms = int(time.time() * 1000)
        start_ms = end_ms - (days * 24 * 60 * 60 * 1000)

        df_1h = self.data_feed.get_klines(self.symbol, TF_1H, start_time=start_ms, end_time=end_ms, limit=1000)
        df_4h = self.data_feed.get_klines(self.symbol, TF_4H, start_time=start_ms, end_time=end_ms, limit=1000)

        if len(df_1h) < 50:
            raise ValueError("Insufficient data")

        self.wallet.reset()
        self.risk_manager.reset()

        records = []
        for i in range(50, len(df_1h)):
            # Simulate 4H view at this point (re-sampled from 1H up to i)
            window_1h = df_1h.iloc[:i].copy()
            # Approximate 4H by taking every 4th candle from the 1H window
            # (Not perfect but workable for backtest)
            window_4h = window_1h.iloc[::4].copy()
            if len(window_4h) < 10:
                continue

            price = float(window_1h["close"].iloc[-1])
            timestamp = window_1h["close_time"].iloc[-1]

            # Regime
            regime, _ = self.regime_analyzer.analyze(window_4h)

            # Indicators
            window_1h["ema9"] = compute_ema(window_1h, B_TRAIL_EMA)
            ema9 = float(window_1h["ema9"].iloc[-1]) if not pd.isna(window_1h["ema9"].iloc[-1]) else None
            indicators = {self.symbol: {"ema9_1h": ema9, "timestamp_ms": int(timestamp.timestamp() * 1000)}}

            # Update positions
            self.wallet.update_positions({self.symbol: price}, indicators)

            # Risk
            can_trade, _ = self.risk_manager.can_trade()

            # Evaluate new position
            if not self.wallet.get_open_position(self.symbol) and can_trade:
                setup = self.playbook_a.evaluate(window_1h, regime)
                if not setup:
                    setup = self.playbook_b.evaluate(window_1h, window_4h, regime)
                if setup:
                    pos = self.wallet.open_position(self.symbol, setup, price)
                    if pos:
                        self.risk_manager.record_open()

            rec = {
                "timestamp": timestamp,
                "price": price,
                "regime": regime.value,
                "wallet": self.wallet.wallet_balance,
                "margin": self.wallet.margin_balance,
                "open": len(self.wallet.positions),
            }
            records.append(rec)

        return pd.DataFrame(records)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="SOL 10x Snap Trading System v2")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL, help="Trading pair")
    parser.add_argument("--balance", type=float, default=1_000.0, help="Initial balance")
    parser.add_argument("--leverage", type=int, default=LEVERAGE, help="Leverage")
    parser.add_argument("--testnet", action="store_true", help="Use testnet")
    parser.add_argument("--backtest-days", type=int, default=None, help="Backtest N days")
    parser.add_argument("--loop", action="store_true", help="Live loop")
    parser.add_argument("--tick", type=int, default=300, help="Loop interval (seconds)")
    args = parser.parse_args()

    engine = TradingEngine(
        symbol=args.symbol,
        initial_balance=args.balance,
        leverage=args.leverage,
        testnet=args.testnet,
    )

    if args.backtest_days:
        logger.info(f"Backtesting {args.backtest_days} days...")
        df = engine.backtest(days=args.backtest_days)
        print(df.tail(20).to_string(index=False))
        engine.wallet.print_summary()
    elif args.loop:
        logger.info("Starting live loop... Ctrl+C to stop.")
        engine.run_loop(interval_seconds=args.tick)
    else:
        summary = engine.run_once()
        engine.wallet.print_summary()
        print("\nSummary JSON:")
        print(json.dumps(summary, indent=2))
