#!/usr/bin/env python3
"""
Binance USD-Margined Futures Local Trading System
====================================================
A complete paper-trading system that:
- Fetches OHLCV data from Binance Futures
- Generates trading signals via technical analysis
- Maintains a local futures wallet (broker-like)
- Opens positions: 10x leverage, 50% equity utilization
- Manages open positions with PnL targets and catastrophic stops
- Handles same-direction / opposite-direction signal logic

Author: Generated by Kimi K2.6
"""

import os
import json
import time
import hashlib
import hmac
import logging
# curses removed – using plain terminal output
import threading
import websocket
import ssl
from datetime import datetime, timezone
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Tuple, Literal
from enum import Enum
import pandas as pd
from pathlib import Path

import numpy as np
import requests

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BINANCE_FAPI_BASE = "https://fapi.binance.com"
BINANCE_FAPI_TESTNET = "https://demo-fapi.binance.com"

LEVERAGE = 5
EQUITY_UTILIZATION = 0.10   # 10% of available equity (Professional risk)
PNL_TARGET_PCT = 0.05       # +5% PnL target (+1% price move with 5x)
CATASTROPHIC_SL_PCT = -0.025 # -2.5% catastrophic stop (-0.5% price move with 5x)

# Signal generation parameters
EMA_FAST = 9
EMA_SLOW = 21
RSI_PERIOD = 14
RSI_OVERBOUGHT = 65         # More conservative
RSI_OVERSOLD = 35           # More conservative

DEFAULT_SYMBOL = "SOLUSDT"
DEFAULT_INTERVAL = "1h"
DEFAULT_KLINE_LIMIT = 150

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("FuturesTrader")


# ---------------------------------------------------------------------------
# Enums & Data Classes
# ---------------------------------------------------------------------------

class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"

class PositionSide(Enum):
    LONG = "LONG"
    SHORT = "SHORT"

class Signal(Enum):
    LONG = 1
    SHORT = -1
    NEUTRAL = 0

@dataclass
class OHLCV:
    open_time: int
    open: float
    high: float
    low: float
    close: float
    volume: float
    close_time: int
    quote_volume: float
    trades: int
    taker_buy_base: float
    taker_buy_quote: float

@dataclass
class Position:
    symbol: str
    side: PositionSide          # LONG or SHORT
    entry_price: float
    quantity: float             # contract quantity (notional / entry_price)
    notional: float             # position value in USDT at entry
    margin_used: float          # notional / leverage
    leverage: int
    open_time: int
    pnl_target: float           # absolute USDT target
    catastrophic_sl: float      # absolute USDT catastrophic stop
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    status: Literal["OPEN", "CLOSED"] = "OPEN"
    close_time: Optional[int] = None
    close_price: Optional[float] = None
    close_reason: Optional[str] = None

    def update_pnl(self, mark_price: float):
        """Update unrealized PnL based on current mark price."""
        if self.status != "OPEN":
            return
        if self.side == PositionSide.LONG:
            self.unrealized_pnl = (mark_price - self.entry_price) * self.quantity
        else:
            self.unrealized_pnl = (self.entry_price - mark_price) * self.quantity

    @property
    def pnl_pct(self) -> float:
        """Return PnL as percentage of margin used."""
        if self.margin_used == 0:
            return 0.0
        return self.unrealized_pnl / self.margin_used

    def to_dict(self) -> dict:
        d = asdict(self)
        d["side"] = self.side.value
        d["status"] = self.status
        return d

    @classmethod
    def from_dict(cls, data: dict) -> "Position":
        data["side"] = PositionSide(data["side"])
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


# ---------------------------------------------------------------------------
# Binance Data Feed
# ---------------------------------------------------------------------------

class BinanceDataFeed:
    """Fetches market data from Binance USD-M Futures REST API."""

    def __init__(self, base_url: str = BINANCE_FAPI_BASE):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({
            "Accept": "application/json",
            "User-Agent": "FuturesTrader/1.0",
        })

    def _get(self, endpoint: str, params: dict = None) -> dict:
        url = f"{self.base_url}/fapi/{endpoint}"
        try:
            resp = self.session.get(url, params=params, timeout=15)
            resp.raise_for_status()
            return resp.json()
        except requests.HTTPError as e:
            status = e.response.status_code if e.response is not None else None
            if status == 418:
                logger.critical("Binance IP ban (418) detected. Sleeping 120s before retry.")
                time.sleep(120)
            elif status == 429:
                logger.warning("Binance rate limit (429) detected. Sleeping 60s before retry.")
                time.sleep(60)
            raise
        except requests.RequestException as e:
            logger.error(f"Request failed: {e}")
            raise

    def get_klines(
        self,
        symbol: str,
        interval: str = "1h",
        limit: int = 150,
        start_time: int = None,
        end_time: int = None,
    ) -> pd.DataFrame:
        """
        Fetch OHLCV klines and return a pandas DataFrame.
        Columns: open_time, open, high, low, close, volume, close_time,
                 quote_volume, trades, taker_buy_base, taker_buy_quote, ignore
        """
        params = {
            "symbol": symbol.upper(),
            "interval": interval,
            "limit": limit,
        }
        if start_time:
            params["startTime"] = start_time
        if end_time:
            params["endTime"] = end_time

        data = self._get("v1/klines", params)
        if not data:
            raise ValueError("No kline data returned")

        df = pd.DataFrame(data, columns=[
            "open_time", "open", "high", "low", "close", "volume",
            "close_time", "quote_volume", "trades",
            "taker_buy_base", "taker_buy_quote", "ignore",
        ])
        numeric_cols = ["open", "high", "low", "close", "volume",
                        "quote_volume", "taker_buy_base", "taker_buy_quote"]
        df[numeric_cols] = df[numeric_cols].astype(float)
        df["open_time"] = pd.to_datetime(df["open_time"], unit="ms", utc=True)
        df["close_time"] = pd.to_datetime(df["close_time"], unit="ms", utc=True)
        return df

    def get_mark_price(self, symbol: str) -> float:
        """Get current mark price for a symbol."""
        data = self._get("v1/premiumIndex", {"symbol": symbol.upper()})
        return float(data["markPrice"])

    def get_exchange_info(self) -> dict:
        """Get exchange info including symbol filters and leverage brackets."""
        return self._get("v1/exchangeInfo")

    def get_server_time(self) -> int:
        """Get Binance server time in milliseconds."""
        return self._get("v1/time")["serverTime"]


# ---------------------------------------------------------------------------
# Signal Generator
# ---------------------------------------------------------------------------

class SignalGenerator:
    """
    Generates LONG / SHORT / NEUTRAL signals from OHLCV DataFrame.
    Strategy: EMA crossover + RSI confirmation.
    """

    def __init__(
        self,
        ema_fast: int = EMA_FAST,
        ema_slow: int = EMA_SLOW,
        rsi_period: int = RSI_PERIOD,
        rsi_overbought: float = RSI_OVERBOUGHT,
        rsi_oversold: float = RSI_OVERSOLD,
    ):
        self.ema_fast = ema_fast
        self.ema_slow = ema_slow
        self.rsi_period = rsi_period
        self.rsi_overbought = rsi_overbought
        self.rsi_oversold = rsi_oversold

    @staticmethod
    def _rsi(series: pd.Series, period: int = 14) -> pd.Series:
        delta = series.diff()
        gain = delta.where(delta > 0, 0.0)
        loss = (-delta.where(delta < 0, 0.0))
        avg_gain = gain.ewm(alpha=1/period, min_periods=period).mean()
        avg_loss = loss.ewm(alpha=1/period, min_periods=period).mean()
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        return rsi

    def generate(self, df: pd.DataFrame) -> Tuple[Signal, pd.DataFrame]:
        """
        Given a DataFrame with at least 'close' column, compute indicators
        and return the latest signal plus the enriched DataFrame.
        """
        if len(df) < self.ema_slow + self.rsi_period:
            logger.warning("Insufficient data for signal generation")
            return Signal.NEUTRAL, df

        df = df.copy()
        df["ema_fast"] = df["close"].ewm(span=self.ema_fast, adjust=False).mean()
        df["ema_slow"] = df["close"].ewm(span=self.ema_slow, adjust=False).mean()
        df["ema_trend"] = df["close"].ewm(span=200, adjust=False).mean()
        df["rsi"] = self._rsi(df["close"], self.rsi_period)
        df["vol_ma"] = df["volume"].rolling(20).mean()

        # Determine crossover state
        df["signal_raw"] = np.where(df["ema_fast"] > df["ema_slow"], 1, -1)
        df["signal_change"] = df["signal_raw"].diff()

        latest = df.iloc[-1]
        prev = df.iloc[-2] if len(df) > 1 else latest

        sig = Signal.NEUTRAL

        # Volume confirmation: current volume > 1.2x of 20-candle average
        volume_confirmed = latest["volume"] > (latest["vol_ma"] * 1.2)
        
        # Momentum confirmation: RSI direction
        rsi_rising = latest["rsi"] > prev["rsi"]
        rsi_falling = latest["rsi"] < prev["rsi"]

        # Trend confirmation: Price vs EMA200
        trend_up = latest["close"] > latest["ema_trend"]
        trend_down = latest["close"] < latest["ema_trend"]

        # Bullish: fast crosses above slow AND RSI not overbought AND volume confirmed AND RSI rising AND trend up
        if latest["ema_fast"] > latest["ema_slow"] and latest["rsi"] < self.rsi_overbought:
            if (prev["ema_fast"] <= prev["ema_slow"] or latest["signal_change"] == 2) and volume_confirmed and rsi_rising and trend_up:
                sig = Signal.LONG
            else:
                sig = Signal.NEUTRAL

        # Bearish: fast crosses below slow AND RSI not oversold AND volume confirmed AND RSI falling AND trend down
        elif latest["ema_fast"] < latest["ema_slow"] and latest["rsi"] > self.rsi_oversold:
            if (prev["ema_fast"] >= prev["ema_slow"] or latest["signal_change"] == -2) and volume_confirmed and rsi_falling and trend_down:
                sig = Signal.SHORT
            else:
                sig = Signal.NEUTRAL

        # If RSI is extreme, stay neutral to avoid chasing
        if latest["rsi"] > self.rsi_overbought + 5 and sig == Signal.LONG:
            sig = Signal.NEUTRAL
        if latest["rsi"] < self.rsi_oversold - 5 and sig == Signal.SHORT:
            sig = Signal.NEUTRAL

        return sig, df


# ---------------------------------------------------------------------------
# Futures Wallet (Broker-like Account Manager)
# ---------------------------------------------------------------------------

class FuturesWallet:
    """
    Simulates a Binance USD-M Futures wallet.
    Tracks: wallet balance, margin balance, available balance,
            positions, realized / unrealized PnL, maintenance margin.
    """

    def __init__(
        self,
        initial_balance: float = 10_000.0,
        leverage: int = LEVERAGE,
        equity_utilization: float = EQUITY_UTILIZATION,
        pnl_target_pct: float = PNL_TARGET_PCT,
        catastrophic_sl_pct: float = CATASTROPHIC_SL_PCT,
        state_file: str = "wallet_state.json",
    ):
        self.leverage = leverage
        self.equity_utilization = equity_utilization
        self.pnl_target_pct = pnl_target_pct
        self.catastrophic_sl_pct = catastrophic_sl_pct
        self.state_file = Path(state_file)

        # Balances
        self.wallet_balance: float = initial_balance
        self.unrealized_pnl_total: float = 0.0
        self.realized_pnl_total: float = 0.0

        # Positions: symbol -> Position
        self.positions: Dict[str, Position] = {}
        self.position_history: List[dict] = []

        # Load persisted state if exists
        self._load_state()

    # -- Balance Properties --

    @property
    def margin_balance(self) -> float:
        """Wallet balance + total unrealized PnL."""
        return self.wallet_balance + self.unrealized_pnl_total

    @property
    def available_balance(self) -> float:
        """Margin balance - total margin used by open positions."""
        used = sum(p.margin_used for p in self.positions.values() if p.status == "OPEN")
        return max(0.0, self.margin_balance - used)

    @property
    def total_equity(self) -> float:
        """Same as margin_balance for this simple model."""
        return self.margin_balance

    # -- Position Management --

    def get_open_position(self, symbol: str) -> Optional[Position]:
        pos = self.positions.get(symbol)
        if pos and pos.status == "OPEN":
            return pos
        return None

    def can_open_position(self, symbol: str, signal: Signal) -> Tuple[bool, str]:
        """
        Check if a new position can be opened.
        Returns (can_open, reason).
        """
        if signal == Signal.NEUTRAL:
            return False, "Signal is NEUTRAL"

        existing = self.get_open_position(symbol)
        if existing:
            existing_signal = Signal.LONG if existing.side == PositionSide.LONG else Signal.SHORT
            if existing_signal == signal:
                return False, f"Already LONG on {symbol}; same-direction signal ignored"
            else:
                return False, f"Already SHORT on {symbol}; opposite-direction signal ignored (close manually or via SL/TP)"

        if self.available_balance <= 0:
            return False, "No available balance"

        return True, "OK"

    def open_position(
        self,
        symbol: str,
        signal: Signal,
        entry_price: float,
        mark_price: float = None,
    ) -> Optional[Position]:
        """
        Open a new futures position using 50% of available equity at 10x leverage.
        """
        can_open, reason = self.can_open_position(symbol, signal)
        if not can_open:
            logger.info(f"[OPEN BLOCKED] {symbol}: {reason}")
            return None

        # Capital allocation
        capital_to_use = self.available_balance * self.equity_utilization
        if capital_to_use <= 0:
            logger.warning("No capital to allocate")
            return None

        # With leverage, notional = capital * leverage
        notional = capital_to_use * self.leverage
        quantity = notional / entry_price
        margin_used = capital_to_use  # notional / leverage

        side = PositionSide.LONG if signal == Signal.LONG else PositionSide.SHORT

        # PnL targets in absolute USDT terms (relative to margin used)
        pnl_target = margin_used * self.pnl_target_pct
        catastrophic_sl = margin_used * self.catastrophic_sl_pct  # negative number

        position = Position(
            symbol=symbol,
            side=side,
            entry_price=entry_price,
            quantity=quantity,
            notional=notional,
            margin_used=margin_used,
            leverage=self.leverage,
            open_time=int(time.time() * 1000),
            pnl_target=pnl_target,
            catastrophic_sl=catastrophic_sl,
        )

        if mark_price:
            position.update_pnl(mark_price)

        self.positions[symbol] = position
        logger.info(
            f"[POSITION OPENED] {symbol} {side.value} | "
            f"Qty={quantity:.6f} @ {entry_price:.2f} | "
            f"Notional={notional:.2f} USDT | Margin={margin_used:.2f} USDT | "
            f"Target=+{pnl_target:.2f} | CatSL={catastrophic_sl:.2f}"
        )
        self._save_state()
        return position

    def close_position(
        self,
        symbol: str,
        close_price: float,
        reason: str = "manual",
    ) -> Optional[Position]:
        """Close an open position and realize PnL."""
        pos = self.get_open_position(symbol)
        if not pos:
            logger.warning(f"No open position on {symbol} to close")
            return None

        pos.update_pnl(close_price)
        realized = pos.unrealized_pnl
        pos.realized_pnl = realized
        pos.status = "CLOSED"
        pos.close_time = int(time.time() * 1000)
        pos.close_price = close_price
        pos.close_reason = reason

        # Update wallet
        self.wallet_balance += realized
        self.realized_pnl_total += realized
        self.unrealized_pnl_total -= pos.unrealized_pnl  # remove from unrealized

        self.position_history.append(pos.to_dict())
        del self.positions[symbol]

        logger.info(
            f"[POSITION CLOSED] {symbol} {pos.side.value} | "
            f"Close={close_price:.2f} | Realized PnL={realized:.2f} USDT | Reason={reason}"
        )
        self._save_state()
        return pos

    def update_positions(self, mark_prices: Dict[str, float]):
        """
        Update unrealized PnL for all open positions and check SL/TP.
        mark_prices: dict of symbol -> current mark price
        """
        for symbol, pos in list(self.positions.items()):
            if pos.status != "OPEN":
                continue

            mark = mark_prices.get(symbol)
            if mark is None:
                continue

            pos.update_pnl(mark)
            pnl = pos.unrealized_pnl

            # Check take-profit
            if pnl >= pos.pnl_target:
                self.close_position(symbol, mark, reason=f"TP_HIT (+{pnl:.2f} USDT)")
                continue

            # Check catastrophic stop-loss (-50% of margin)
            if pnl <= pos.catastrophic_sl:
                self.close_position(symbol, mark, reason=f"CATASTROPHIC_SL ({pnl:.2f} USDT)")
                continue

        # Recompute total unrealized
        self.unrealized_pnl_total = sum(
            p.unrealized_pnl for p in self.positions.values() if p.status == "OPEN"
        )

    def get_portfolio_summary(self) -> dict:
        """Return a snapshot of the wallet state."""
        open_positions = [p.to_dict() for p in self.positions.values() if p.status == "OPEN"]
        return {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "wallet_balance": round(self.wallet_balance, 4),
            "unrealized_pnl_total": round(self.unrealized_pnl_total, 4),
            "realized_pnl_total": round(self.realized_pnl_total, 4),
            "margin_balance": round(self.margin_balance, 4),
            "available_balance": round(self.available_balance, 4),
            "total_equity": round(self.total_equity, 4),
            "open_positions_count": len(open_positions),
            "open_positions": open_positions,
            "position_history_count": len(self.position_history),
        }

    def print_summary(self):
        summary = self.get_portfolio_summary()
        print("\n" + "=" * 60)
        print("  FUTURES WALLET SUMMARY")
        print("=" * 60)
        print(f"  Wallet Balance      : {summary['wallet_balance']:.4f} USDT")
        print(f"  Unrealized PnL      : {summary['unrealized_pnl_total']:.4f} USDT")
        print(f"  Realized PnL        : {summary['realized_pnl_total']:.4f} USDT")
        print(f"  Margin Balance      : {summary['margin_balance']:.4f} USDT")
        print(f"  Available Balance   : {summary['available_balance']:.4f} USDT")
        print(f"  Open Positions      : {summary['open_positions_count']}")
        if summary["open_positions"]:
            for p in summary["open_positions"]:
                print(f"    - {p['symbol']} {p['side']} | "
                      f"Entry={p['entry_price']:.2f} | "
                      f"U-PnL={p['unrealized_pnl']:.4f} ({p['unrealized_pnl']/p['margin_used']*100:.2f}%)")
        print("=" * 60 + "\n")

    # -- Persistence --

    def _save_state(self):
        state = {
            "wallet_balance": self.wallet_balance,
            "realized_pnl_total": self.realized_pnl_total,
            "positions": {s: p.to_dict() for s, p in self.positions.items()},
            "position_history": self.position_history,
        }
        with open(self.state_file, "w") as f:
            json.dump(state, f, indent=2, default=str)

    def _load_state(self):
        if not self.state_file.exists():
            return
        try:
            with open(self.state_file, "r") as f:
                state = json.load(f)
            self.wallet_balance = state.get("wallet_balance", self.wallet_balance)
            self.realized_pnl_total = state.get("realized_pnl_total", 0.0)
            self.positions = {
                s: Position.from_dict(d)
                for s, d in state.get("positions", {}).items()
            }
            self.position_history = state.get("position_history", [])
            logger.info(f"Loaded wallet state from {self.state_file}")
        except Exception as e:
            logger.warning(f"Failed to load state: {e}")

    def reset(self):
        """Clear all state and reset to initial balance."""
        self.positions.clear()
        self.position_history.clear()
        self.wallet_balance = 10_000.0
        self.unrealized_pnl_total = 0.0
        self.realized_pnl_total = 0.0
        if self.state_file.exists():
            self.state_file.unlink()
        logger.info("Wallet state reset")


# ---------------------------------------------------------------------------
# CoinDCX WebSocket Feed (Alternative for LTP)
# ---------------------------------------------------------------------------

class CoinDCXWSFeed:
    """Real-time LTP feed via CoinDCX Futures WebSocket (Socket.io v2)."""
    def __init__(self, symbol: str):
        # Map Binance SOLUSDT to CoinDCX B-SOL_USDT
        base = symbol.replace("USDT", "")
        self.coindcx_symbol = f"B-{base}_USDT"
        self.last_price = 0.0
        self.running = False
        self.status = "DISCONNECTED"
        self.error_log = ""
        self._thread = None
        
        # Socket.io v2 endpoint
        self.ws_url = "wss://stream.coindcx.com/socket.io/?EIO=3&transport=websocket"

    def _on_message(self, ws, message):
        try:
            # Socket.io protocol: 42["event", data]
            if isinstance(message, str) and message.startswith("42"):
                payload = json.loads(message[2:])
                event_name = payload[0]
                data = payload[1]
                
                # Check for trade or price-change events
                if event_name in ["new-trade", "price-change"]:
                    if "p" in data:
                        self.last_price = float(data["p"])
                        self.status = "CONNECTED"
            
            elif isinstance(message, str) and message.startswith("0"):
                ws.send("40")  # Handshake response
            
            elif isinstance(message, str) and message.startswith("40"):
                # Join channel after namespace opened
                join_msg = f'42["join", {{"channelName": "{self.coindcx_symbol}@trades-futures"}}]'
                ws.send(join_msg)
                self.status = "JOINING..."
        except Exception as e:
            self.error_log = f"ParseErr: {str(e)[:15]}"

    def _on_error(self, ws, error):
        self.error_log = f"DCXErr: {str(error)[:20]}"
        self.status = "ERROR"

    def _on_close(self, ws, close_status_code, close_msg):
        self.status = "CLOSED"

    def _on_open(self, ws):
        self.status = "OPENED"
        self.error_log = "Handshaking..."

    def _run(self):
        while self.running:
            try:
                self.status = "CONNECTING..."
                ws = websocket.WebSocketApp(
                    self.ws_url,
                    on_message=self._on_message,
                    on_error=self._on_error,
                    on_close=self._on_close,
                    on_open=self._on_open
                )
                ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE}, ping_interval=25, ping_timeout=10)
            except Exception as e:
                self.error_log = f"RunErr: {str(e)[:15]}"
            time.sleep(5)

    def start(self):
        self.running = True
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def stop(self):
        self.running = False
        self.status = "STOPPED"


# ---------------------------------------------------------------------------
# Trading Engine
# ---------------------------------------------------------------------------

class TradingEngine:
    """
    Orchestrates data fetching, signal generation, and position management.
    """

    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        interval: str = DEFAULT_INTERVAL,
        initial_balance: float = 10_000.0,
        leverage: int = LEVERAGE,
        testnet: bool = False,
    ):
        self.symbol = symbol.upper()
        self.interval = interval
        self.data_feed = BinanceDataFeed(
            base_url=BINANCE_FAPI_TESTNET if testnet else BINANCE_FAPI_BASE
        )
        # Switch to CoinDCX for real-time LTP updates
        self.ws_feed = CoinDCXWSFeed(self.symbol)
        self.signal_gen = SignalGenerator()
        self.wallet = FuturesWallet(
            initial_balance=initial_balance,
            leverage=leverage,
            state_file=f"wallet_{self.symbol}_{self.interval}.json",
        )

    def run_once(self, mark_price: float = None) -> dict:
        """
        Single iteration:
        1. Fetch latest klines
        2. Generate signal
        3. Update existing positions PnL & check SL/TP
        4. Open new position if signal and no conflict
        5. Return summary
        """
        # 1. Fetch data
        try:
            df = self.data_feed.get_klines(self.symbol, self.interval, limit=DEFAULT_KLINE_LIMIT)
            if mark_price is None:
                mark_price = self.data_feed.get_mark_price(self.symbol)
        except Exception as e:
            logger.error(f"Data fetch failed: {e}")
            return self.wallet.get_portfolio_summary()

        # 2. Generate signal
        signal, df = self.signal_gen.generate(df)
        
        # 3. Update open positions
        self.wallet.update_positions({self.symbol: mark_price})

        # 4. Evaluate new position
        if signal in (Signal.LONG, Signal.SHORT):
            can_open, reason = self.wallet.can_open_position(self.symbol, signal)
            if can_open:
                self.wallet.open_position(
                    symbol=self.symbol,
                    signal=signal,
                    entry_price=mark_price,
                    mark_price=mark_price,
                )

        # 5. Summary
        summary = self.wallet.get_portfolio_summary()
        return summary

    def run_loop(self, interval_seconds: int = 60, max_iterations: int = None):
        """Run the main loop and render a simple stdout dashboard."""
        self.ws_feed.start()
        iteration = 0
        start_time = time.time()
        try:
            while True:
                now = time.time()
                if max_iterations is not None and iteration >= max_iterations:
                    break
                # Run strategy on tick interval
                if now - start_time >= interval_seconds:
                    mark_price = self.ws_feed.last_price if self.ws_feed.last_price > 0 else None
                    self.run_once(mark_price=mark_price)
                    start_time = now
                    iteration += 1
                # Update unrealized PnL with latest price
                current_price = self.ws_feed.last_price
                if current_price > 0:
                    self.wallet.update_positions({self.symbol: current_price})
                summary = self.wallet.get_portfolio_summary()
                # Display dashboard
                os.system('clear')
                header = f"=== {self.symbol} LTP: {current_price:.4f} | {datetime.now().strftime('%H:%M:%S')} ===" if current_price > 0 else f"=== {self.symbol} | WS {self.ws_feed.status} {self.ws_feed.error_log} ==="
                print(header)
                print("=" * len(header))
                print(f"Wallet Balance    : {summary['wallet_balance']:.4f} USDT")
                print(f"Realized PnL      : {summary['realized_pnl_total']:.4f} USDT")
                pnl = summary['unrealized_pnl_total']
                color = ''
                if pnl > 0:
                    color = '\x1b[32m'
                elif pnl < 0:
                    color = '\x1b[31m'
                reset = '\x1b[0m'
                print(f"Unrealized PnL    : {color}{pnl:.4f}{reset} USDT")
                print(f"Margin Balance    : {summary['margin_balance']:.4f} USDT")
                print(f"Available Balance : {summary['available_balance']:.4f} USDT")
                if summary['open_positions']:
                    print("Open Positions:")
                    for p in summary['open_positions']:
                        print(f"  - {p['symbol']} {p['side']} | Entry={p['entry_price']:.2f} | U‑PnL={p['unrealized_pnl']:.2f}")
                time.sleep(0.5)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")
        finally:
            self.ws_feed.stop()
            # Legacy curses UI removed - using simple stdout dashboard

    def backtest(
        self,
        days: int = 30,
        interval: str = "1h",
        plot: bool = False,
    ) -> pd.DataFrame:
        """Run a simple backtest over historical klines.
        Walk-forward: at each candle close, generate signal, update positions,
        and open/close accordingly.
        """
        # Fetch enough history
        end_time = int(time.time() * 1000)
        start_time = end_time - (days * 24 * 60 * 60 * 1000)

        df = self.data_feed.get_klines(
            self.symbol, interval, start_time=start_time, end_time=end_time, limit=1000
        )
        if len(df) < 50:
            raise ValueError("Not enough historical data")

        # Reset wallet for clean backtest
        self.wallet.reset()

        records = []
        for i in range(50, len(df)):
            window = df.iloc[:i].copy()
            signal, window = self.signal_gen.generate(window)
            price = float(window["close"].iloc[-1])
            timestamp = window["close_time"].iloc[-1]

            # Update positions with current price
            self.wallet.update_positions({self.symbol: price})

            # Try open
            if signal in (Signal.LONG, Signal.SHORT):
                can_open, _ = self.wallet.can_open_position(self.symbol, signal)
                if can_open:
                    self.wallet.open_position(self.symbol, signal, price, price)

            rec = {
                "timestamp": timestamp,
                "price": price,
                "signal": signal.name,
                "wallet_balance": self.wallet.wallet_balance,
                "margin_balance": self.wallet.margin_balance,
                "open_positions": len(self.wallet.positions),
            }
            records.append(rec)

        results = pd.DataFrame(records)
        if plot:
            try:
                import matplotlib.pyplot as plt
                fig, ax = plt.subplots(figsize=(12, 6))
                ax.plot(results["timestamp"], results["margin_balance"], label="Margin Balance")
                ax.set_title(f"Backtest: {self.symbol} ({interval})")
                ax.set_xlabel("Time")
                ax.set_ylabel("USDT")
                ax.legend()
                ax.grid(True)
                plt.tight_layout()
                plt.show()
            except Exception as e:
                logger.warning(f"Plot failed: {e}")

        return results


# ---------------------------------------------------------------------------
# CLI / Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Binance USD-M Futures Local Trading System")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL, help="Trading pair (e.g., SOLUSDT)")
    parser.add_argument("--interval", default=DEFAULT_INTERVAL, help="Kline interval (e.g., 1h)")
    parser.add_argument("--balance", type=float, default=10_000.0, help="Initial wallet balance")
    parser.add_argument("--leverage", type=int, default=LEVERAGE, help="Leverage multiplier")
    parser.add_argument("--testnet", action="store_true", help="Use Binance testnet")
    parser.add_argument("--backtest-days", type=int, default=None, help="Run backtest for N days")
    parser.add_argument("--loop", action="store_true", help="Run live loop")
    parser.add_argument("--tick", type=int, default=60, help="Loop tick interval in seconds")
    args = parser.parse_args()

    engine = TradingEngine(
        symbol=args.symbol,
        interval=args.interval,
        initial_balance=args.balance,
        leverage=args.leverage,
        testnet=args.testnet,
    )

    if args.backtest_days:
        logger.info(f"Running backtest for {args.backtest_days} days...")
        results = engine.backtest(days=args.backtest_days, interval=args.interval)
        print(results.tail(20).to_string(index=False))
        engine.wallet.print_summary()
    elif args.loop:
        logger.info("Starting live loop... Press Ctrl+C to stop.")
        engine.run_loop(interval_seconds=args.tick)
    else:
        # Single tick demo
        summary = engine.run_once()
        engine.wallet.print_summary()
        print("\nPortfolio JSON:")
        print(json.dumps(summary, indent=2))
