#!/usr/bin/env python3
"""
Ollama LLM Integration for SOL 10× Snap Trading System
========================================================
Provides an AI advisor layer that:
    • Analyzes market structure, sentiment, and risk factors
    • Returns structured JSON bias signals (NOT direct trade orders)
    • Caches responses to avoid redundant LLM calls
    • Operates asynchronously so it never blocks the trading loop
    • Acts as a FILTER and MODIFIER, never as a primary signal generator

Architecture Principle:
    Technical indicators (EMA, RSI, volume) generate the signal.
    LLM provides a CONFIDENCE MODIFIER (-1.0 to +1.0) and RISK FLAG.
    If LLM strongly disagrees with the technical signal, the trade is blocked.

Author: Generated by Kimi K2.6
"""

import os
import json
import time
import logging
import hashlib
import threading
from datetime import datetime, timezone, timedelta
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Literal
from pathlib import Path
from enum import Enum

import requests
import pandas as pd

logger = logging.getLogger("OllamaAdvisor")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen3.5:4b")  # Fast, good at JSON
OLLAMA_TIMEOUT = int(os.getenv("OLLAMA_TIMEOUT", "320"))   # Seconds — covers cold-start (~34s) + full prompt inference
OLLAMA_MAX_TOKENS = int(os.getenv("OLLAMA_MAX_TOKENS", "1024"))

# Cache settings
CACHE_TTL_SECONDS = 1800  # 30 minutes — LLM advice stays valid for 1–2 candles
CACHE_DIR = Path("llm_cache")

# LLM influence weights
LLM_MIN_CONFIDENCE = 0.65   # Below this, LLM advice is ignored
LLM_VETO_THRESHOLD = -0.70  # Below this, LLM vetoes the technical signal entirely

# ---------------------------------------------------------------------------
# LLM Response Schema
# ---------------------------------------------------------------------------

class LLMBias(Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"
    UNCLEAR = "unclear"

class LLMRiskLevel(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    EXTREME = "extreme"

@dataclass
class LLMAdvice:
    timestamp: int
    symbol: str
    bias: LLMBias
    confidence: float           # 0.0 – 1.0
    sentiment_score: float      # -1.0 (bearish) to +1.0 (bullish)
    risk_level: LLMRiskLevel
    key_factors: List[str]
    recommended_bias: Literal["long_only", "short_only", "any", "none"]
    technical_alignment: float  # How much LLM agrees with current technical regime
    veto: bool = False          # True if LLM says "do not trade"
    veto_reason: Optional[str] = None  # Explanation when veto=True; None means no veto
    raw_response: str = ""

    def to_dict(self) -> dict:
        return {
            "timestamp": self.timestamp,
            "symbol": self.symbol,
            "bias": self.bias.value,
            "confidence": round(self.confidence, 3),
            "sentiment_score": round(self.sentiment_score, 3),
            "risk_level": self.risk_level.value,
            "key_factors": self.key_factors,
            "recommended_bias": self.recommended_bias,
            "technical_alignment": round(self.technical_alignment, 3),
            "veto": self.veto,
            "veto_reason": self.veto_reason,
        }


# ---------------------------------------------------------------------------
# Prompt Engineering
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are a quantitative crypto futures trading advisor.
You analyze market data and return ONLY a JSON object. No markdown, no explanation outside the JSON.

Rules:
1. You are advisory only. You do NOT place orders.
2. Base your analysis on price action, volume, momentum, and market structure.
3. Be conservative — it is better to say "neutral" than to force a wrong bias.
4. If the setup looks like a trap (e.g., breakout on declining volume), flag HIGH risk.
5. If price is near a major liquidation cluster or funding is extreme, mention it.

Output JSON schema:
{
  "bias": "bullish" | "bearish" | "neutral" | "unclear",
  "confidence": 0.0 to 1.0,
  "sentiment_score": -1.0 to 1.0,
  "risk_level": "low" | "medium" | "high" | "extreme",
  "key_factors": ["factor 1", "factor 2", ...],
  "recommended_bias": "long_only" | "short_only" | "any" | "none",
  "technical_alignment": -1.0 to 1.0,
  "veto_reason": null | "string explaining why no trade should be taken"
}"""


def build_market_prompt(
    symbol: str,
    df_1h: pd.DataFrame,
    df_4h: pd.DataFrame,
    regime: str,
    mark_price: float,
    open_positions: List[dict],
) -> str:
    """Build a rich, structured prompt from current market data."""

    # Summarize 1H data
    recent_1h = df_1h.tail(6)
    h1_summary = []
    for _, row in recent_1h.iterrows():
        direction = "▲" if row["close"] > row["open"] else "▼"
        h1_summary.append(
            f"{direction} O:{row['open']:.2f} H:{row['high']:.2f} L:{row['low']:.2f} C:{row['close']:.2f} V:{row['volume']:.0f}"
        )

    # Summarize 4H data
    recent_4h = df_4h.tail(4)
    h4_summary = []
    for _, row in recent_4h.iterrows():
        direction = "▲" if row["close"] > row["open"] else "▼"
        h4_summary.append(
            f"{direction} O:{row['open']:.2f} H:{row['high']:.2f} L:{row['low']:.2f} C:{row['close']:.2f} V:{row['volume']:.0f}"
        )

    # Compute quick stats
    change_24h = (
        (mark_price - df_1h["close"].iloc[-24]) / df_1h["close"].iloc[-24] * 100
        if len(df_1h) >= 24 else 0
    )
    volume_24h = df_1h["volume"].tail(24).sum()
    avg_volume_20 = df_1h["volume"].tail(20).mean()
    volume_surge = (df_1h["volume"].iloc[-1] / avg_volume_20 - 1) * 100 if avg_volume_20 > 0 else 0

    # Open position context — use .get() with defaults to avoid KeyError / ZeroDivisionError
    pos_context = "No open positions."
    if open_positions:
        p = open_positions[0]
        margin = p.get("margin_used") or 1.0   # avoid ZeroDivisionError
        upnl = p.get("unrealized_pnl", 0.0)
        pct = upnl / margin * 100
        pos_context = (
            f"Open {p.get('side', '?')} from {p.get('entry_price', 0):.2f}, "
            f"current unrealized PnL: {upnl:.2f} USDT ({pct:.1f}% on margin)"
        )

    prompt = f"""Analyze the following market data for {symbol} and return ONLY JSON.

Current Price: {mark_price:.2f}
24H Change: {change_24h:+.2f}%
24H Volume: {volume_24h:,.0f}
Last 1H Volume vs 20-candle avg: {volume_surge:+.1f}%
Technical Regime: {regime}

Last 6 x 1H candles (newest last):
{chr(10).join(h1_summary)}

Last 4 x 4H candles (newest last):
{chr(10).join(h4_summary)}

Position Context: {pos_context}

Question: Based on this data, what is your bias, confidence, and risk assessment?
Return ONLY the JSON object."""

    return prompt


# ---------------------------------------------------------------------------
# Ollama Client
# ---------------------------------------------------------------------------

class OllamaClient:
    """Lightweight async-capable client for Ollama API."""

    def __init__(
        self,
        host: str = OLLAMA_HOST,
        model: str = OLLAMA_MODEL,
        timeout: int = OLLAMA_TIMEOUT,
        max_tokens: int = OLLAMA_MAX_TOKENS,
    ):
        self.host = host.rstrip("/")
        self.model = model
        self.timeout = timeout
        self.max_tokens = max_tokens
        self.session = requests.Session()

    def is_available(self) -> bool:
        """Check if Ollama server is running."""
        try:
            resp = self.session.get(f"{self.host}/api/tags", timeout=5)
            return resp.status_code == 200
        except Exception:
            return False

    def generate(
        self,
        prompt: str,
        system: str = SYSTEM_PROMPT,
        temperature: float = 0.3,  # Low temp for consistent JSON
    ) -> Optional[str]:
        """Send prompt to Ollama and return raw text."""
        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system,
            "stream": False,
            "think": False,   # Disable chain-of-thought on Qwen3/3.5 thinking models;
                              # has no effect on non-thinking models (llama3.2, etc.)
            "options": {
                "temperature": temperature,
                "num_predict": self.max_tokens,
            },
        }
        try:
            resp = self.session.post(
                f"{self.host}/api/generate",
                json=payload,
                timeout=self.timeout,
            )
            resp.raise_for_status()
            data = resp.json()
            response_text = data.get("response", "").strip()
            if not response_text and "thinking" in data:
                response_text = data["thinking"].strip()
            return response_text
        except requests.Timeout:
            logger.warning("Ollama request timed out")
            return None
        except Exception as e:
            logger.warning(f"Ollama request failed: {e}")
            return None


# ---------------------------------------------------------------------------
# Response Parser & Validator
# ---------------------------------------------------------------------------

class LLMResponseParser:
    """Parses raw LLM text into structured LLMAdvice."""

    @staticmethod
    def parse(raw: str, symbol: str, technical_regime: str) -> Optional[LLMAdvice]:
        if not raw:
            return None

        # Strip <think>...</think> blocks emitted by Qwen3/3.5 thinking models
        # even when think:false is set, some quantised versions still emit them.
        import re
        text = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
        if not text:
            logger.warning("LLM response was only a <think> block — no JSON produced")
            return None

        # Extract JSON block if wrapped in markdown
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0].strip()
        elif "```" in text:
            text = text.split("```")[1].split("```")[0].strip()

        # Fallback: find outermost { ... } block
        start = text.find("{")
        end = text.rfind("}") + 1
        if start != -1 and end > start:
            text = text[start:end]

        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            logger.warning(f"LLM returned invalid JSON: {raw[:200]}")
            return None

        # Validate and coerce fields
        bias_str = data.get("bias", "unclear").lower()
        bias = LLMBias(bias_str) if bias_str in [e.value for e in LLMBias] else LLMBias.UNCLEAR

        # BUG FIX: was corrupted to "   0, conf))" — restored full clamp expression
        conf = float(data.get("confidence", 0.5))
        conf = max(0.0, min(1.0, conf))

        score = float(data.get("sentiment_score", 0.0))
        score = max(-1.0, min(1.0, score))

        risk_str = data.get("risk_level", "medium").lower()
        risk = LLMRiskLevel(risk_str) if risk_str in [e.value for e in LLMRiskLevel] else LLMRiskLevel.MEDIUM

        factors = data.get("key_factors", [])
        if not isinstance(factors, list):
            factors = [str(factors)]

        rec = data.get("recommended_bias", "any")
        if rec not in ("long_only", "short_only", "any", "none"):
            rec = "any"

        align = float(data.get("technical_alignment", 0.0))
        align = max(-1.0, min(1.0, align))

        veto_reason = data.get("veto_reason")
        veto_reason_str = str(veto_reason).strip() if veto_reason else None
        veto = bool(veto_reason_str)  # True only when veto_reason is a non-empty string

        return LLMAdvice(
            timestamp=int(time.time()),
            symbol=symbol,
            bias=bias,
            confidence=conf,
            sentiment_score=score,
            risk_level=risk,
            key_factors=factors[:5],  # Cap at 5
            recommended_bias=rec,
            technical_alignment=align,
            veto=veto,
            veto_reason=veto_reason_str,
            raw_response=raw,
        )


# ---------------------------------------------------------------------------
# Disk Cache
# ---------------------------------------------------------------------------

class LLMCache:
    """Simple file-based cache to avoid redundant LLM calls."""

    def __init__(self, ttl: int = CACHE_TTL_SECONDS, cache_dir: Path = CACHE_DIR,
                 model: str = OLLAMA_MODEL):
        self.ttl = ttl
        self.dir = cache_dir
        self.model = model
        self.dir.mkdir(exist_ok=True)

    def _key(self, symbol: str, prompt: str) -> str:
        """Hash symbol + model + prompt — different models get separate cache entries."""
        h = hashlib.sha256(f"{symbol}:{self.model}:{prompt}".encode()).hexdigest()[:16]
        return h

    def get(self, symbol: str, prompt: str) -> Optional[LLMAdvice]:
        key = self._key(symbol, prompt)
        path = self.dir / f"{symbol}_{key}.json"
        if not path.exists():
            return None
        try:
            with open(path, "r") as f:
                data = json.load(f)
            if time.time() - data.get("cached_at", 0) > self.ttl:
                return None
            # Reconstruct — include veto_reason so it survives cache round-trips
            return LLMAdvice(
                timestamp=data["timestamp"],
                symbol=data["symbol"],
                bias=LLMBias(data["bias"]),
                confidence=data["confidence"],
                sentiment_score=data["sentiment_score"],
                risk_level=LLMRiskLevel(data["risk_level"]),
                key_factors=data["key_factors"],
                recommended_bias=data["recommended_bias"],
                technical_alignment=data["technical_alignment"],
                veto=data["veto"],
                veto_reason=data.get("veto_reason"),
                raw_response=data.get("raw_response", ""),
            )
        except Exception:
            return None

    def set(self, symbol: str, prompt: str, advice: LLMAdvice):
        key = self._key(symbol, prompt)
        path = self.dir / f"{symbol}_{key}.json"
        data = advice.to_dict()
        data["cached_at"] = int(time.time())
        data["raw_response"] = advice.raw_response[:500]  # Truncate
        with open(path, "w") as f:
            json.dump(data, f, indent=2)


# ---------------------------------------------------------------------------
# Main Advisor Class
# ---------------------------------------------------------------------------

class OllamaAdvisor:
    """
    High-level advisor that integrates LLM intelligence into the trading loop.
    Usage:
        advisor = OllamaAdvisor()
        advice = advisor.get_advice(symbol, df_1h, df_4h, regime, mark_price, positions)
        if advice and advice.veto:
            logger.info(f"LLM vetoed trade: {advice.veto_reason}")
    """

    def __init__(
        self,
        host: str = OLLAMA_HOST,
        model: str = OLLAMA_MODEL,
        timeout: int = OLLAMA_TIMEOUT,
        cache_ttl: int = CACHE_TTL_SECONDS,
        min_confidence: float = LLM_MIN_CONFIDENCE,
        veto_threshold: float = LLM_VETO_THRESHOLD,
    ):
        self.client = OllamaClient(host=host, model=model, timeout=timeout)
        self.parser = LLMResponseParser()
        self.cache = LLMCache(ttl=cache_ttl, model=model)  # model in key → no cross-model cache hits
        self.min_confidence = min_confidence
        self.veto_threshold = veto_threshold
        self._last_advice: Optional[LLMAdvice] = None
        self._advice_lock = threading.Lock()

    def is_ready(self) -> bool:
        return self.client.is_available()

    def get_advice(
        self,
        symbol: str,
        df_1h: pd.DataFrame,
        df_4h: pd.DataFrame,
        regime: str,
        mark_price: float,
        open_positions: List[dict],
        force_refresh: bool = False,
    ) -> Optional[LLMAdvice]:
        """
        Get LLM advice. Returns None if LLM is unavailable, cache miss, or parse failure.
        This is a SYNCHRONOUS call (blocking). For non-blocking, use get_advice_async().
        """
        prompt = build_market_prompt(symbol, df_1h, df_4h, regime, mark_price, open_positions)

        # Check cache
        if not force_refresh:
            cached = self.cache.get(symbol, prompt)
            if cached:
                logger.debug("LLM cache hit")
                with self._advice_lock:
                    self._last_advice = cached
                return cached

        # Call LLM
        raw = self.client.generate(prompt)
        if not raw:
            logger.warning("LLM returned no response; using last advice if available")
            with self._advice_lock:
                return self._last_advice

        advice = self.parser.parse(raw, symbol, regime)
        if not advice:
            logger.warning("Failed to parse LLM response")
            with self._advice_lock:
                return self._last_advice

        # Cache and store
        self.cache.set(symbol, prompt, advice)
        with self._advice_lock:
            self._last_advice = advice

        logger.info(
            f"[LLM ADVICE] {symbol} | Bias={advice.bias.value} | "
            f"Confidence={advice.confidence:.2f} | Score={advice.sentiment_score:+.2f} | "
            f"Risk={advice.risk_level.value} | Veto={advice.veto} | "
            f"Factors={advice.key_factors}"
        )
        return advice

    def get_advice_async(
        self,
        symbol: str,
        df_1h: pd.DataFrame,
        df_4h: pd.DataFrame,
        regime: str,
        mark_price: float,
        open_positions: List[dict],
        callback=None,
    ) -> threading.Thread:
        """
        Non-blocking version. Spawns a thread, calls LLM, then invokes callback(advice).
        Returns immediately so the trading loop is never blocked.
        """
        def _worker():
            advice = self.get_advice(symbol, df_1h, df_4h, regime, mark_price, open_positions)
            if callback:
                callback(advice)

        t = threading.Thread(target=_worker, daemon=True)
        t.start()
        return t

    def should_allow_trade(
        self,
        advice: Optional[LLMAdvice],
        technical_side: str,  # "LONG" or "SHORT"
    ) -> Tuple[bool, str]:
        """
        Decide if a technical signal should be acted upon.
        Returns (allow, reason).
        """
        if advice is None:
            return True, "No LLM advice available; proceeding on technical signal only"

        if advice.veto:
            # veto_reason is now a proper dataclass field — no hasattr needed
            reason = advice.veto_reason or "Risk too high"
            return False, f"LLM VETO: {reason}"

        if advice.confidence < self.min_confidence:
            return True, f"LLM confidence low ({advice.confidence:.2f}); technical signal takes precedence"

        # Alignment check
        tech_long = technical_side == "LONG"
        llm_bullish = advice.bias in (LLMBias.BULLISH, LLMBias.NEUTRAL) and advice.sentiment_score > 0.1
        llm_bearish = advice.bias in (LLMBias.BEARISH, LLMBias.NEUTRAL) and advice.sentiment_score < -0.1

        if tech_long and llm_bearish and advice.sentiment_score < self.veto_threshold:
            return False, f"LLM strongly disagrees with LONG (score={advice.sentiment_score:+.2f})"
        if not tech_long and llm_bullish and advice.sentiment_score > abs(self.veto_threshold):
            return False, f"LLM strongly disagrees with SHORT (score={advice.sentiment_score:+.2f})"

        # Recommended bias filter
        if advice.recommended_bias == "long_only" and not tech_long:
            return False, "LLM recommends long_only; short signal blocked"
        if advice.recommended_bias == "short_only" and tech_long:
            return False, "LLM recommends short_only; long signal blocked"
        if advice.recommended_bias == "none":
            return False, "LLM recommends no trades today"

        return True, f"LLM aligned (score={advice.sentiment_score:+.2f}, conf={advice.confidence:.2f})"

    def adjust_position_size(
        self,
        advice: Optional[LLMAdvice],
        base_margin: float,
    ) -> float:
        """
        Modify position size based on LLM risk assessment.
        Returns adjusted margin to use.
        """
        if advice is None:
            return base_margin

        multiplier = 1.0
        if advice.risk_level == LLMRiskLevel.EXTREME:
            multiplier = 0.0  # Block entirely
        elif advice.risk_level == LLMRiskLevel.HIGH:
            multiplier = 0.5
        elif advice.risk_level == LLMRiskLevel.MEDIUM:
            multiplier = 0.75
        elif advice.risk_level == LLMRiskLevel.LOW:
            multiplier = 1.0

        # Confidence scaling
        multiplier *= (0.5 + 0.5 * advice.confidence)

        return base_margin * multiplier

    def get_last_advice(self) -> Optional[LLMAdvice]:
        with self._advice_lock:
            return self._last_advice


# ---------------------------------------------------------------------------
# Integration Helpers for TradingEngine
# ---------------------------------------------------------------------------

def integrate_llm_into_engine(engine) -> OllamaAdvisor:
    """
    Attach an OllamaAdvisor to an existing TradingEngine.
    This is a convenience function showing the wiring pattern.
    """
    advisor = OllamaAdvisor()
    if not advisor.is_ready():
        logger.warning("Ollama not available at startup. LLM layer disabled until connection restored.")
    return advisor


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import numpy as np

    # Create synthetic data for testing
    np.random.seed(42)
    n = 50
    base = 100.0
    data = []
    for i in range(n):
        o = base + np.random.normal(0, 1)
        c = o + np.random.normal(0.2, 0.8)
        h = max(o, c) + abs(np.random.normal(0, 0.5))
        l = min(o, c) - abs(np.random.normal(0, 0.5))
        v = np.random.normal(1000, 200)
        data.append({"open": o, "high": h, "low": l, "close": c, "volume": max(v, 100)})
        base = c

    df = pd.DataFrame(data)
    df_1h = df.copy()
    df_4h = df.iloc[::4].reset_index(drop=True)

    advisor = OllamaAdvisor()
    print(f"Ollama available: {advisor.is_ready()}")

    if advisor.is_ready():
        advice = advisor.get_advice(
            symbol="TESTUSDT",
            df_1h=df_1h,
            df_4h=df_4h,
            regime="TRENDING_UP",
            mark_price=df_1h["close"].iloc[-1],
            open_positions=[],
        )
        if advice:
            print("\nLLM Advice:")
            print(json.dumps(advice.to_dict(), indent=2))
    else:
        print("\nOllama not running. Start it with: ollama run qwen3.5:4b")