"""
crypto_trader.engine_ws — WebSocket-Enhanced Trading Engine
============================================================
Hybrid architecture:
    • REST: Historical klines (4H, 1H), funding, OI, LLM context
    • WebSocket: Real-time LTP, mark price, bid/ask for entries/exits

Entry timing: Uses WebSocket LTP for precise entry execution
Exit monitoring: WebSocket position manager checks SL/TP/Trail every 1s
Signal generation: Still uses REST 1H/4H close for technical analysis

Author: Generated by Kimi K2.6
"""

import os
import time
import uuid
import logging
import argparse
from datetime import datetime, timezone

import pandas as pd

from .data_feed import BinanceDataFeed
from .websocket import BinanceWebSocketFeed, WebSocketPositionManager
from .wallet import EnhancedFuturesWallet, PositionSide
from .risk import RiskManager
from .playbooks import PlaybookA, PlaybookB
from .regime import MarketRegimeAnalyzer, compute_ema
from .llm_advisor import OllamaAdvisor, FINAL_SCORE_THRESHOLD
from .journal import TradeJournal

logger = logging.getLogger("crypto_trader.engine_ws")

DEFAULT_SYMBOL = "SOLUSDT"
LEVERAGE = 10


class WebSocketTradingEngine:
    """
    Hybrid engine: REST for signals, WebSocket for execution.

    Architecture:
        REST (5-min tick): Fetch 4H/1H → analyze regime → generate signal → LLM fusion
        WebSocket (1s): Monitor LTP → check SL/TP/Trail → execute entries/exits
    """

    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        testnet: bool = False,
        use_llm: bool = True,
        llm_host: str = None,
        llm_model: str = None,
        log_responses: bool = False,
        log_rest: bool = False,
        log_ws: bool = False,
        log_llm: bool = False,
    ):
        self.symbol = symbol.upper()
        self.use_llm = use_llm

        rest_logged = log_responses or log_rest
        ws_logged = log_responses or log_ws
        llm_logged = log_responses or log_llm

        # REST client (for historical data, funding, OI)
        base_url = "https://demo-fapi.binance.com" if testnet else "https://fapi.binance.com"
        self.data_feed = BinanceDataFeed(base_url=base_url, log_responses=rest_logged)

        # WebSocket client (for real-time LTP, mark price, bid/ask)
        self.ws_feed = BinanceWebSocketFeed(
            symbol=self.symbol,
            testnet=testnet,
            on_mark_price=self._on_mark_price,
            on_kline=self._on_kline,
            on_book_ticker=self._on_book_ticker,
            log_responses=ws_logged,
        )

        # Wallet & Risk
        self.wallet = EnhancedFuturesWallet(
            symbol=self.symbol,
            initial_balance=initial_balance,
            leverage=leverage,
        )
        self.risk_manager = RiskManager()

        # Strategy
        self.regime_analyzer = MarketRegimeAnalyzer()
        self.playbook_a = PlaybookA()
        self.playbook_b = PlaybookB()

        # Journal
        self.journal = TradeJournal()

        # LLM
        self.advisor = None
        self._llm_thread = None
        if use_llm:
            resolved_host = llm_host or os.getenv("OLLAMA_HOST", "http://localhost:11434")
            resolved_model = llm_model or os.getenv("OLLAMA_MODEL", "qwen3.5:4b")
            self.advisor = OllamaAdvisor(host=resolved_host, model=resolved_model, log_llm=llm_logged)
            if self.advisor.is_ready():
                logger.info(f"[LLM] Connected to {resolved_model}")
            else:
                logger.warning("[LLM] Ollama unavailable. Technical-only mode.")

        # WebSocket position manager (high-frequency exits)
        self.ws_pm = WebSocketPositionManager(
            ws_feed=self.ws_feed,
            wallet=self.wallet,
            check_interval_ms=1000,  # Check every 1 second
        )

        # State
        self._last_signal_candle_ms = 0
        self._pending_entry = None  # Signal waiting for WebSocket confirmation

    # ── Lifecycle ──

    def start(self):
        """Start WebSocket and position manager."""
        logger.info(f"[ENGINE] Starting WebSocket engine for {self.symbol}")
        self.ws_feed.start()
        self.ws_pm.start()
        # Wait for WebSocket to connect
        for _ in range(10):
            if self.ws_feed.is_connected():
                break
            time.sleep(0.5)
        logger.info(f"[ENGINE] WebSocket connected: {self.ws_feed.is_connected()}")

    def stop(self):
        """Gracefully stop all components."""
        logger.info("[ENGINE] Stopping...")
        self.ws_pm.stop()
        self.ws_feed.stop()
        logger.info("[ENGINE] Stopped")

    # ── Main Loop ──

    def run_loop(self, signal_interval_seconds: int = 300, max_iterations: int = None):
        """
        Main loop:
            - Every 5 min (default): REST fetch → signal generation → entry evaluation
            - Every 1 sec (WebSocket): Position monitoring → SL/TP/Trail execution
        """
        self.start()
        iteration = 0
        try:
            while True:
                # Signal generation tick (REST-based)
                self._signal_tick()

                iteration += 1
                if max_iterations and iteration >= max_iterations:
                    break

                time.sleep(signal_interval_seconds)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")
        finally:
            self.stop()

    def _signal_tick(self):
        """Generate signals using REST data (runs every 5 min)."""
        logger.info(f"--- Signal Tick: {self.symbol} ---")

        try:
            # Fetch historical data via REST
            df_4h = self.data_feed.get_klines(self.symbol, "4h", limit=200)
            df_1h = self.data_feed.get_klines(self.symbol, "1h", limit=150)
            df_15m = self.data_feed.get_klines(self.symbol, "15m", limit=150)
            df_5m = self.data_feed.get_klines(self.symbol, "5m", limit=150)

            # Get current context from WebSocket (real-time)
            ws_data = self.ws_feed.get_data()
            mark_price = ws_data.mark_price if ws_data.mark_price > 0 else self.data_feed.get_mark_price(self.symbol)

            funding_rate = self.data_feed.get_funding_rate(self.symbol)
            oi_data = self.data_feed.get_open_interest(self.symbol)
            taker_ratio = self.data_feed.get_taker_ratio(self.symbol)

        except Exception as e:
            logger.error(f"Data fetch failed: {e}")
            return

        # 1. Regime analysis
        regime, regime_score, df_4h = self.regime_analyzer.analyze(df_4h)
        logger.info(f"Regime: {regime.value} (score={regime_score:.2f})")

        # OI delta: would require storing historical OI to compute a proper delta.
        # Using 0.0 for now — the raw oi value is still passed to the LLM prompt.
        oi_delta = 0.0

        # 3. Start LLM async
        if self.use_llm and self.advisor:
            open_positions = [p.to_dict() for p in self.wallet.positions.values() if p.status == "OPEN"]
            if self._llm_thread is None or not self._llm_thread.is_alive():
                self._llm_thread = self.advisor.get_advice_async(
                    symbol=self.symbol,
                    df_5m=df_5m,
                    df_15m=df_15m,
                    df_1h=df_1h,
                    df_4h=df_4h,
                    regime=regime.value,
                    regime_score=regime_score,
                    mark_price=mark_price,
                    funding_rate=funding_rate,
                    oi_delta=oi_delta,
                    taker_ratio=taker_ratio,
                    open_positions=open_positions,
                )

        # 4. Risk check
        can_trade, risk_reason = self.risk_manager.can_trade()
        if not can_trade:
            logger.info(f"[RISK] {risk_reason}")

        # 5. Evaluate entry if no open position
        if not self.wallet.get_open_position() and can_trade:
            self._evaluate_entry(df_1h, df_4h, regime, regime_score, mark_price,
                                funding_rate, oi_delta, taker_ratio)

        # 6. Print summary
        self.wallet.print_summary()

    def _evaluate_entry(self, df_1h, df_4h, regime, regime_score, mark_price,
                        funding_rate, oi_delta, taker_ratio):
        """Evaluate entry signals and execute via WebSocket LTP."""
        setup = None

        # Try Playbook A
        setup = self.playbook_a.evaluate(df_1h, regime)
        if setup:
            logger.info(f"[PLAYBOOK A] Signal: {setup['side'].value} | score={setup['score']:.2f}")

        # Try Playbook B
        if not setup:
            setup = self.playbook_b.evaluate(df_1h, df_4h, regime)
            if setup:
                logger.info(f"[PLAYBOOK B] Signal: {setup['side'].value} | score={setup['score']:.2f}")

        if not setup:
            return

        # LLM Fusion
        tech_score = setup["score"]
        advice = self.advisor.get_last_advice() if self.advisor else None

        if self.advisor and advice:
            final_score, llm_weight, explanation = self.advisor.compute_final_score(
                technical_score=tech_score,
                regime=regime.value,
                regime_score=regime_score,
                advice=advice,
            )
            logger.info(f"[FUSION] {explanation} | tech={tech_score:.2f} | final={final_score:.2f}")
        else:
            final_score = tech_score
            llm_weight = 0.0
            explanation = "LLM unavailable"

        from .llm_advisor import FINAL_SCORE_THRESHOLD
        if final_score < FINAL_SCORE_THRESHOLD:
            logger.info(f"[BLOCKED] Final score {final_score:.2f} < {FINAL_SCORE_THRESHOLD}")
            return

        # Execute entry using WebSocket LTP for precise price
        self._execute_entry(setup, final_score, llm_weight, explanation,
                           mark_price, funding_rate, oi_delta, taker_ratio,
                           tech_score, regime, regime_score, advice)

    def _execute_entry(self, setup, final_score, llm_weight, explanation,
                      mark_price, funding_rate, oi_delta, taker_ratio,
                      tech_score, regime, regime_score, advice):
        """Execute entry using real-time WebSocket prices."""
        # Get current LTP and spread from WebSocket
        ltp = self.ws_feed.get_ltp()
        mid = self.ws_feed.get_mid_price()
        spread = self.ws_feed.get_spread()

        if ltp <= 0:
            logger.warning("[ENTRY] WebSocket LTP unavailable, using mark price")
            ltp = mark_price
            mid = mark_price

        # Slippage estimate: if spread > 0.1%, log warning
        spread_pct = spread / mid * 100 if mid > 0 else 0
        if spread_pct > 0.1:
            logger.warning(f"[ENTRY] Wide spread: {spread_pct:.3f}% | bid={self.ws_feed.data.best_bid:.2f} ask={self.ws_feed.data.best_ask:.2f}")

        # Adjust entry price to use mid price (fairer than LTP which can be stale)
        entry_price = mid

        # Recalculate SL/TP based on actual entry price
        if setup["side"] == PositionSide.LONG:
            sl = entry_price * (1 - 0.007)  # Use Playbook A SL as default
            tp = entry_price * (1 + 0.010)
        else:
            sl = entry_price * (1 + 0.007)
            tp = entry_price * (1 - 0.010)

        # Update setup with actual entry price
        setup["entry_price"] = entry_price
        setup["sl_price"] = sl
        if "tp_price" in setup:
            setup["tp_price"] = tp
        else:
            for tp_level in setup.get("tp_levels", []):
                if setup["side"] == PositionSide.LONG:
                    tp_level["price"] = entry_price * (1 + 0.010 if tp_level["label"] == "TP1" else 0.020)
                else:
                    tp_level["price"] = entry_price * (1 - 0.010 if tp_level["label"] == "TP1" else 0.020)

        # Size based on final score
        from .llm_advisor import FINAL_SCORE_THRESHOLD
        base_margin = self.wallet.available_balance * self.wallet.equity_utilization
        adjusted_margin = base_margin * min(final_score / FINAL_SCORE_THRESHOLD, 1.0)

        trade_id = str(uuid.uuid4())[:8]

        # Open position
        pos = self.wallet.open_position(setup, entry_price, custom_margin=adjusted_margin)

        if pos:
            self.risk_manager.record_open()

            # Calculate slippage
            intended = setup["entry_price"]
            actual = entry_price
            slippage = abs(actual - intended) / intended * 100 if intended > 0 else 0

            self.journal.log_open(
                trade_id=trade_id,
                symbol=self.symbol,
                regime=regime.value,
                regime_score=regime_score,
                setup=setup,
                technical_score=tech_score,
                llm_advice=advice.to_dict() if self.advisor and advice else None,
                llm_weight=llm_weight,
                final_score=final_score,
                margin=adjusted_margin,
                notional=pos.notional,
                entry_price=entry_price,
                funding_rate=funding_rate,
                oi_delta=oi_delta,
                taker_ratio=taker_ratio,
            )

            logger.info(
                f"[EXECUTED] Trade {trade_id} | Entry={entry_price:.2f} | "
                f"Margin={adjusted_margin:.2f} | Score={final_score:.2f} | "
                f"Spread={spread_pct:.3f}% | Slippage={slippage:.3f}%"
            )

    # ── WebSocket Callbacks ──

    def _on_mark_price(self, mark_price: float, funding_rate: float):
        """Called every 1s when mark price updates."""
        # Can be used for real-time PnL display or alerts
        pass

    def _on_kline(self, interval: str, candle: dict):
        """Called when kline updates (every candle close)."""
        if candle.get("is_closed"):
            logger.debug(f"[WS] {interval} candle closed: {candle['close']:.2f}")

    def _on_book_ticker(self, bid: float, ask: float):
        """Called when best bid/ask changes."""
        # Can be used for spread monitoring
        pass

    # ── Backtest (REST-only mode) ──

    def backtest(self, days: int = 14) -> pd.DataFrame:
        """Run walk-forward backtest using REST data only."""
        from .engine import TradingEngine
        # Use the REST-only engine for backtest
        rest_engine = TradingEngine(
            symbol=self.symbol,
            initial_balance=self.wallet.wallet_balance,
            leverage=self.wallet.leverage,
        )
        return rest_engine.backtest(days=days)


def main():
    parser = argparse.ArgumentParser(description="Crypto Trader v4 — WebSocket Edition")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL)
    parser.add_argument("--balance", type=float, default=1_000.0)
    parser.add_argument("--leverage", type=int, default=LEVERAGE)
    parser.add_argument("--testnet", action="store_true")
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--llm-host", default=None, help="Ollama host URL (defaults to OLLAMA_HOST env var)")
    parser.add_argument("--llm-model", default=None, help="Ollama model name (defaults to OLLAMA_MODEL env var)")
    parser.add_argument("--log-responses", action="store_true", help="Log all REST API, WS, and LLM JSON outputs (master toggle)")
    parser.add_argument("--log-rest", action="store_true", help="Log Binance REST API request/response JSON")
    parser.add_argument("--log-ws", action="store_true", help="Log Binance WebSocket message JSON")
    parser.add_argument("--log-llm", action="store_true", help="Log Ollama LLM prompt and response JSON")
    parser.add_argument("--tick", type=int, default=300, help="Signal tick interval (seconds)")
    parser.add_argument("--backtest-days", type=int, default=None)
    args = parser.parse_args()

    from .logger_config import configure_colored_logging
    configure_colored_logging(level=logging.INFO)

    engine = WebSocketTradingEngine(
        symbol=args.symbol,
        initial_balance=args.balance,
        leverage=args.leverage,
        testnet=args.testnet,
        use_llm=not args.no_llm,
        llm_host=args.llm_host,
        llm_model=args.llm_model,
        log_responses=args.log_responses,
        log_rest=args.log_rest,
        log_ws=args.log_ws,
        log_llm=args.log_llm,
    )

    if args.backtest_days:
        logger.info(f"Backtesting {args.backtest_days} days...")
        df = engine.backtest(days=args.backtest_days)
        print(df.tail(20).to_string(index=False))
        engine.wallet.print_summary()
    else:
        engine.run_loop(signal_interval_seconds=args.tick)


if __name__ == "__main__":
    main()
