"""
crypto_trader.engine_ws — WebSocket-Enhanced Trading Engine
============================================================
Hybrid architecture:
    • REST: Historical klines (4H, 1H), funding, OI, LLM context
    • WebSocket: Real-time LTP, mark price, bid/ask for entries/exits

Entry timing: Uses WebSocket LTP for precise entry execution
Exit monitoring: WebSocket position manager checks SL/TP/Trail every 1s
Signal generation: Still uses REST 1H/4H close for technical analysis

Author: Generated by Kimi K2.6
"""

import os
import time
import uuid
import logging
import argparse
from decimal import Decimal
from datetime import datetime, timezone

import pandas as pd

from .data_feed import BinanceDataFeed
from .ws_client import BinanceWebSocketFeed, WebSocketPositionManager
from .wallet import EnhancedFuturesWallet, PositionSide
from .risk import RiskManager, AdaptiveThresholdManager
from .playbooks import PlaybookA, PlaybookB, PlaybookAres
from .regime import MarketRegimeAnalyzer, compute_ema
from .llm_advisor import OllamaAdvisor, FINAL_SCORE_THRESHOLD
from .journal import TradeJournal
from .structure import MarketStructureAnalyzer

logger = logging.getLogger("crypto_trader.engine_ws")

DEFAULT_SYMBOL = "SOLUSDT"
LEVERAGE = 5
FUNDING_EXTREME = 0.0005


class WebSocketTradingEngine:
    """
    Hybrid engine: REST for signals, WebSocket for execution.

    Architecture:
        REST (5-min tick): Fetch 4H/1H → analyze regime → generate signal → LLM fusion
        WebSocket (1s): Monitor LTP → check SL/TP/Trail → execute entries/exits
    """

    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        use_llm: bool = True,
        llm_host: str = None,
        llm_model: str = None,
        log_responses: bool = False,
        log_rest: bool = False,
        log_ws: bool = False,
        log_llm: bool = False,
        wallet = None,
        event_bus = None,
        cfg = None,
    ):
        self.symbol = symbol.upper()
        self.use_llm = use_llm
        self.event_bus = event_bus
        self.cfg = cfg
        # CoinDCX market data for the cross-venue basis guard (F3). Public, no
        # creds; built lazily so paper/tests without network stay light.
        self._coindcx_md = None

        rest_logged = log_responses or log_rest
        ws_logged = log_responses or log_ws
        llm_logged = log_responses or log_llm

        # REST client (for historical data, funding, OI)
        self.data_feed = BinanceDataFeed(log_responses=rest_logged)

        # WebSocket client (for real-time LTP, mark price, bid/ask)
        self.ws_feed = BinanceWebSocketFeed(
            symbol=self.symbol,
            on_mark_price=self._on_mark_price,
            on_kline=self._on_kline,
            on_book_ticker=self._on_book_ticker,
            log_responses=ws_logged,
        )

        if wallet:
            self.wallet = wallet
        else:
            self.wallet = EnhancedFuturesWallet(
                symbol=self.symbol,
                initial_balance=initial_balance,
                leverage=leverage,
            )
        
        if cfg:
            self.risk_manager = RiskManager(
                max_daily_trades=cfg.max_daily_trades,
                max_orders_per_minute=cfg.max_orders_per_minute,
                max_margin_ratio=cfg.max_margin_ratio
            )
        else:
            self.risk_manager = RiskManager()
        self.adaptive_threshold = AdaptiveThresholdManager(
            base_threshold=FINAL_SCORE_THRESHOLD,
            min_threshold=0.50,
            decay_per_hour=0.01,
            target_trades_per_day=1.0
        )

        # Strategy
        self.regime_analyzer = MarketRegimeAnalyzer()
        self.playbook_a = PlaybookA()
        self.playbook_b = PlaybookB()
        self.playbook_ares = PlaybookAres()

        # Journal
        self.journal = TradeJournal()

        # LLM
        self.advisor = None
        self._llm_thread = None
        if use_llm:
            use_cloud = os.getenv("USE_CLOUD_LLM", "false").lower() in ("true", "1", "yes")

            if use_cloud:
                resolved_host = os.getenv("CLOUD_OLLAMA_HOST", "https://ollama.com")
                resolved_model = os.getenv("CLOUD_OLLAMA_MODEL", "deepseek-v3:cloud")
                resolved_key = os.getenv("CLOUD_OLLAMA_API_KEY", "")
                logger.info(f"[LLM] Mode: CLOUD (Target: {resolved_host})")
            else:
                resolved_host = llm_host or os.getenv("OLLAMA_BASE_URL", os.getenv("OLLAMA_HOST", "http://localhost:11434"))
                resolved_model = llm_model or os.getenv("OLLAMA_MODEL", "qwen3.5:4b")
                resolved_key = os.getenv("OLLAMA_API_KEY", "")
                logger.info("[LLM] Mode: LOCAL")

            use_openai = os.getenv("USE_OPENAI_FORMAT", "false").lower() in ("true", "1", "yes")

            self.advisor = OllamaAdvisor(
                host=resolved_host,
                model=resolved_model,
                api_key=resolved_key,
                use_openai=use_openai,
                log_llm=llm_logged
            )
            if self.advisor.is_ready():
                logger.info(f"[LLM] Connected to {resolved_model}")
            else:
                logger.warning("[LLM] Ollama unavailable. Technical-only mode.")

        # WebSocket position manager (high-frequency exits)
        self.ws_pm = WebSocketPositionManager(
            ws_feed=self.ws_feed,
            wallet=self.wallet,
            check_interval_ms=1000,  # Check every 1 second
            event_bus=self.event_bus,
            # G4: drive the authoritative margin guard on the 1s loop (every ~5s),
            # not only on the 5-min signal tick — liquidation can't wait 5 min.
            health_check=self._check_authoritative_health,
        )

        # State
        self._last_signal_candle_ms = 0
        self._pending_entry = None  # Signal waiting for WebSocket confirmation
        self._halted = False

        # Command Listeners
        if self.event_bus:
            from .events import CommandEvent, TradeClosedEvent
            self.event_bus.subscribe(CommandEvent, self._handle_command)
            self.event_bus.subscribe(TradeClosedEvent, self._on_trade_closed)

    def _on_trade_closed(self, event):
        """Update risk manager when a trade is closed."""
        if event.symbol == self.symbol:
            self.risk_manager.record_close(event.realized_pnl)

    def _handle_command(self, event):
        """Handle incoming commands from EventBus (e.g., Telegram)."""
        if event.command == "KILL_ALL" or (event.command == "KILL" and event.params.get("symbol") == self.symbol):
            self._halted = True
            logger.warning(f"🛑 [HALTED] {self.symbol} received KILL command.")
            # A remote KILL must flatten the live position, not just block new
            # entries — otherwise an open position rides on unattended.
            try:
                pos = self.wallet.get_open_position(self.symbol)
                if pos:
                    mark = self.ws_feed.get_ltp() or self.ws_feed.get_mid_price()
                    if not mark or mark <= 0:
                        mark = float(pos.entry_price)
                    self.wallet.close_position(self.symbol, float(mark), reason="REMOTE_KILL")
                    logger.warning(f"🛑 [KILL] flattened {self.symbol} on remote command")
            except Exception as e:
                logger.error("remote KILL flatten failed for %s: %s", self.symbol, e)
        
        elif event.command == "RESUME_ALL" or (event.command == "RESUME" and event.params.get("symbol") == self.symbol):
            self._halted = False
            logger.info(f"✅ [RESUMED] {self.symbol} received RESUME command.")

        elif event.command == "STATUS":
            # Engine will respond via logs or potentially publish a StatusEvent
            logger.info(f"📊 [STATUS] {self.symbol} | Halted: {self._halted} | Pos: {self.wallet.get_open_position(self.symbol) is not None}")

    # ── Lifecycle ──

    def start(self):
        """Start WebSocket and position manager."""
        logger.info(f"[ENGINE] Starting WebSocket engine for {self.symbol}")
        self.ws_feed.start()
        self.ws_pm.start()
        # Wait for WebSocket to connect
        for _ in range(10):
            if self.ws_feed.is_connected():
                break
            time.sleep(0.5)
        logger.info(f"[ENGINE] WebSocket connected: {self.ws_feed.is_connected()}")

    def stop(self):
        """Gracefully stop all components."""
        logger.info("[ENGINE] Stopping...")
        self.ws_pm.stop()
        self.ws_feed.stop()
        logger.info("[ENGINE] Stopped")

    def _check_authoritative_health(self):
        """Monitor authoritative exchange metrics (margin ratio) and trigger kill switch if unsafe."""
        if not self.cfg or not self.cfg.is_live:
            return

        from .exchanges.coindcx_execution import CoinDCXExecutionEngine
        if not isinstance(self.wallet.execution_engine, CoinDCXExecutionEngine):
            return

        try:
            details = self.wallet.execution_engine.get_cross_margin_details()
            if details:
                ratio = float(details.get("margin_ratio_cross", 0) or 0)
                ok, reason = self.risk_manager.check_margin_ratio(ratio)
                if not ok:
                    logger.critical(f"[AUTHORITATIVE GUARD] {reason}")
                    self.risk_manager.trigger_kill_switch(reason)
                    self._halted = True
                    if self.event_bus:
                        from .events import SystemFailureEvent
                        self.event_bus.publish(SystemFailureEvent(component="margin_guard", error=reason))
                    # Halting only blocks NEW entries; an open position is still
                    # racing toward liquidation at this margin ratio. Flatten it.
                    try:
                        pos = self.wallet.get_open_position(self.symbol)
                        if pos:
                            mark = self.ws_feed.get_ltp() or self.ws_feed.get_mid_price()
                            if not mark or mark <= 0:
                                mark = float(pos.entry_price)
                            self.wallet.close_position(
                                self.symbol, float(mark),
                                reason="MARGIN_GUARD_FLATTEN",
                            )
                            logger.critical("[AUTHORITATIVE GUARD] flattened %s to avoid liquidation", self.symbol)
                    except Exception as e:
                        logger.error("margin-guard flatten failed for %s: %s", self.symbol, e)
        except Exception as e:
            logger.error("Authoritative health check failed: %s", e)

    # ── Main Loop ──

    def run_loop(self, signal_interval_seconds: int = 300, max_iterations: int = None):
        """
        Main loop:
            - Every 5 min (default): REST fetch → signal generation → entry evaluation
            - Every 1 sec (WebSocket): Position monitoring → SL/TP/Trail execution
        """
        self.start()
        iteration = 0
        try:
            while True:
                # G3: supervise the WS threads — never trade on a dead/stale feed.
                if not self._supervise_threads():
                    break
                
                # Authoritative health check (margin ratio guard)
                self._check_authoritative_health()

                # Signal generation tick (REST-based)
                self._signal_tick()

                iteration += 1
                if max_iterations and iteration >= max_iterations:
                    break

                time.sleep(signal_interval_seconds)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")
        finally:
            self.stop()

    def _supervise_threads(self) -> bool:
        """G3: fail-stop if a background WS thread died silently.

        Returns True if it is safe to continue. On a dead feed/position-manager
        thread it trips HALT + the kill switch and halts the engine, rather than
        evaluating signals or managing positions against a stale feed.
        """
        if self.cfg is not None and not getattr(self.cfg, "thread_supervisor_enabled", True):
            return True
        dead = []
        if not self.ws_feed.is_alive():
            dead.append("ws_feed")
        if not self.ws_pm.is_alive():
            dead.append("ws_position_manager")
        if not dead:
            return True
        reason = f"WS thread(s) died: {', '.join(dead)}"
        logger.critical("[SUPERVISOR] %s — halting engine (fail-stop)", reason)
        try:
            from . import safe_mode
            safe_mode.trip_halt(reason)
        except Exception:
            pass
        if getattr(self, "risk_manager", None) is not None:
            self.risk_manager.trigger_kill_switch(reason)
        if self.event_bus:
            from .events import SystemFailureEvent
            self.event_bus.publish(SystemFailureEvent(component="thread_supervisor", error=reason))
        self._halted = True
        return False

    def _signal_tick(self):
        """Generate signals using REST data (runs every 5 min)."""
        if self._halted:
            logger.debug(f"[SIGNAL-TICK] {self.symbol} is halted. Skipping.")
            return

        logger.info(f"--- Signal Tick: {self.symbol} ---")

        try:
            # Fetch historical data via REST
            df_4h = self.data_feed.get_klines(self.symbol, "4h", limit=200)
            df_1h = self.data_feed.get_klines(self.symbol, "1h", limit=150)
            df_15m = self.data_feed.get_klines(self.symbol, "15m", limit=150)
            df_5m = self.data_feed.get_klines(self.symbol, "5m", limit=150)

            # Get current context from WebSocket (real-time)
            ws_data = self.ws_feed.get_data()
            mark_price = ws_data.mark_price if ws_data.mark_price > 0 else self.data_feed.get_mark_price(self.symbol)

            funding_rate = self.data_feed.get_funding_rate(self.symbol)
            oi_data = self.data_feed.get_open_interest(self.symbol)
            taker_ratio = self.data_feed.get_taker_ratio(self.symbol)

            if mark_price <= 0:
                logger.warning(f"[WS-ENGINE] Invalid mark price {mark_price}. Skipping signal tick.")
                return

        except Exception as e:
            logger.error(f"Data fetch failed: {e}")
            return

        # 1. Regime analysis
        regime, regime_score, df_4h = self.regime_analyzer.analyze(df_4h)
        logger.info(f"Regime: {regime.value} (score={regime_score:.2f})")

        # 2. Market structure analysis (SMC signals for playbook gating)
        structure = None
        try:
            msa = MarketStructureAnalyzer(df_1h, swing_window=3)
            structure = msa.analyze()
            recent_bos = structure.get("recent_bos")
            logger.debug(
                f"[STRUCTURE] BOS={recent_bos['type'] if recent_bos else 'None'} | "
                f"OBs={len(structure.get('unmitigated_order_blocks', []))} | "
                f"FVGs={len(structure.get('unmitigated_fvgs', []))}"
            )
        except Exception as e:
            logger.warning(f"[STRUCTURE] MarketStructureAnalyzer failed: {e}")
            structure = None

        # OI delta: would require storing historical OI to compute a proper delta.
        # Using 0.0 for now — the raw oi value is still passed to the LLM prompt.
        oi_delta = 0.0

        # 3. Start LLM async
        if self.use_llm and self.advisor:
            pos = self.wallet.get_open_position(self.symbol)
            open_positions = [pos.to_dict()] if pos else []
            if self._llm_thread is None or not self._llm_thread.is_alive():
                self._llm_thread = self.advisor.get_advice_async(
                    symbol=self.symbol,
                    df_5m=df_5m,
                    df_15m=df_15m,
                    df_1h=df_1h,
                    df_4h=df_4h,
                    regime=regime.value,
                    regime_score=regime_score,
                    mark_price=mark_price,
                    funding_rate=funding_rate,
                    oi_delta=oi_delta,
                    taker_ratio=taker_ratio,
                    open_positions=open_positions,
                )

        # 4. Risk check
        self.risk_manager.update_peak_balance(self.wallet.margin_balance)
        # Assuming initial balance for daily drawdown is the wallet balance minus daily PnL
        initial_daily_balance = float(self.wallet.wallet_balance) - self.risk_manager.daily_pnl
        can_trade, risk_reason = self.risk_manager.can_trade(
            current_balance=self.wallet.margin_balance,
            initial_daily_balance=initial_daily_balance
        )
        if not can_trade:
            if not getattr(self, "_halt_published", False):
                if self.event_bus:
                    from .events import RiskHaltEvent
                    self.event_bus.publish(RiskHaltEvent(
                        reason=risk_reason,
                        daily_pnl=float(self.wallet.realized_pnl_total),
                        trades_today=self.risk_manager.daily_count
                    ))
                self._halt_published = True
            logger.info(f"[RISK] {risk_reason}")
            return
        self._halt_published = False

        # 4.5 Update position if open (to check AI and regime reversal exits)
        pos = self.wallet.get_open_position(self.symbol)
        if pos:
            df_1h["ema9"] = compute_ema(df_1h["close"], 9)
            ema9_val = df_1h["ema9"].iloc[-1]
            ema9_1h = float(ema9_val) if pd.notna(ema9_val) else None
            candle_close_time = int(df_1h["close_time"].iloc[-1].timestamp() * 1000)

            advice = self.advisor.get_last_advice() if (self.use_llm and self.advisor) else None
            current_llm_advice = advice.to_dict() if advice else None

            self.wallet.update_positions(
                self.symbol,
                mark_price,
                candle_close_time,
                ema9_1h,
                current_llm_advice=current_llm_advice,
                current_regime=regime.value if regime else None,
            )

        # 5. Evaluate entry if no open position
        if not self.wallet.get_open_position(self.symbol) and can_trade:
            # Get latest ADX for Ares playbook filter
            latest_adx = df_4h["adx"].iloc[-1] if "adx" in df_4h.columns else None
            try:
                self._evaluate_entry(df_1h, df_4h, df_15m, regime, regime_score, mark_price,
                                    funding_rate, oi_delta, taker_ratio, structure=structure, adx_1h=latest_adx)
            except Exception as e:
                # An exception mid-entry (e.g. order placed but booking/SL failed)
                # could leave an unmanaged live position. Fail safe: HALT, trip
                # the kill switch, and reconcile against the venue rather than
                # letting the loop crash and abandon a naked position.
                logger.critical("[ENTRY FAILURE] %s — halting and reconciling: %s", self.symbol, e)
                self._halted = True
                if getattr(self, "risk_manager", None) is not None:
                    self.risk_manager.trigger_kill_switch(f"entry failure: {e}")
                if self.cfg and self.cfg.is_live:
                    try:
                        from . import safe_mode
                        safe_mode.trip_halt(f"entry failure for {self.symbol}: {e}")
                    except Exception:
                        pass
                if self.event_bus:
                    from .events import SystemFailureEvent
                    self.event_bus.publish(SystemFailureEvent(component="entry", error=str(e)))

        # 6. Print summary
        self.wallet.print_summary()

    def _evaluate_entry(self, df_1h, df_4h, df_15m, regime, regime_score, mark_price,
                        funding_rate, oi_delta, taker_ratio, structure=None, adx_1h=None):
        """Evaluate entry signals and execute via WebSocket LTP."""
        setup = None

        # 1. Try Playbook Ares (Mean Reversion)
        setup = self.playbook_ares.evaluate(df_15m, adx_1h=adx_1h)
        if setup:
            logger.info(f"[PLAYBOOK ARES] Signal: {setup['side'].value} | score={setup['score']:.2f}")

        # 2. Try Playbook A
        if not setup:
            setup = self.playbook_a.evaluate(df_1h, regime, structure=structure)
            if setup:
                logger.info(f"[PLAYBOOK A] Signal: {setup['side'].value} | score={setup['score']:.2f}")

        # 3. Try Playbook B
        if not setup:
            setup = self.playbook_b.evaluate(df_1h, df_4h, regime, structure=structure)
            if setup:
                logger.info(f"[PLAYBOOK B] Signal: {setup['side'].value} | score={setup['score']:.2f}")

        if not setup:
            return

        # Correlation check
        active_positions = {s: p.to_dict() for s, p in self.wallet.positions.items() if p.status == "OPEN"}
        allowed, corr_reason = self.risk_manager.check_correlation(self.symbol, setup["side"].value, active_positions)
        if not allowed:
            logger.info(f"[BLOCKED] {corr_reason}")
            return

        # LLM Fusion
        tech_score = setup["score"]
        advice = self.advisor.get_last_advice() if self.advisor else None

        if self.advisor and advice:
            final_score, llm_weight, explanation = self.advisor.compute_final_score(
                technical_score=tech_score,
                regime=regime.value,
                regime_score=regime_score,
                advice=advice,
            )
            logger.info(f"[FUSION] {explanation} | tech={tech_score:.2f} | final={final_score:.2f}")
        else:
            final_score = tech_score
            llm_weight = 0.0
            explanation = "LLM unavailable"

        dynamic_threshold = self.adaptive_threshold.get_threshold()
        if final_score < dynamic_threshold:
            logger.info(f"[BLOCKED] Final score {final_score:.2f} < {dynamic_threshold:.2f}")
            return
        if (
            (setup["side"] == PositionSide.LONG and funding_rate > FUNDING_EXTREME)
            or (setup["side"] == PositionSide.SHORT and funding_rate < -FUNDING_EXTREME)
        ):
            logger.info(
                f"[BLOCKED] Funding extreme for {setup['side'].value}: {funding_rate:+.4%} "
                f"(threshold={FUNDING_EXTREME:.2%})"
            )
            return

        # Execute entry using WebSocket LTP for precise price
        self._execute_entry(setup, final_score, llm_weight, explanation,
                           mark_price, funding_rate, oi_delta, taker_ratio,
                           tech_score, regime, regime_score, advice, dynamic_threshold)

    def _coindcx_market_data(self):
        if self._coindcx_md is None:
            from .exchanges.coindcx_market_data import CoinDCXMarketData
            self._coindcx_md = CoinDCXMarketData()
        return self._coindcx_md

    def _basis_guard(self, side, binance_mark: float):
        """Cross-venue basis guard (F3).

        Signals fire on Binance price but fills happen on CoinDCX. Reject the
        entry when the venues diverge beyond the configured threshold. Returns
        ``(allowed, basis)``. If CoinDCX data is unavailable, skip the guard
        (don't block trading on a missing fallback feed).
        """
        cfg = self.cfg
        if cfg is None or not getattr(cfg, "basis_guard_enabled", False) or binance_mark <= 0:
            return True, 0.0
        try:
            cdcx_mark = self._coindcx_market_data().get_mark_price(self.symbol)
        except Exception as e:
            logger.warning("[BASIS] CoinDCX mark unavailable (%s); skipping guard", e)
            return True, 0.0
        if cdcx_mark <= 0:
            return True, 0.0
        basis = (cdcx_mark - binance_mark) / binance_mark
        if abs(basis) > cfg.max_cross_venue_basis:
            logger.warning(
                f"[BASIS BLOCKED] {self.symbol} basis {basis:+.4%} exceeds "
                f"{cfg.max_cross_venue_basis:.2%} (binance={binance_mark:.4f} coindcx={cdcx_mark:.4f})"
            )
            if self.event_bus:
                from .events import SignalRejectedEvent
                self.event_bus.publish(SignalRejectedEvent(
                    symbol=self.symbol,
                    reason=f"cross-venue basis {basis:+.4%} > {cfg.max_cross_venue_basis:.2%}",
                ))
            return False, basis
        return True, basis

    def _execute_entry(self, setup, final_score, llm_weight, explanation,
                      mark_price, funding_rate, oi_delta, taker_ratio,
                      tech_score, regime, regime_score, advice, dynamic_threshold):
        """Execute entry using real-time WebSocket prices."""
        # Get current LTP and spread from WebSocket
        ltp = self.ws_feed.get_ltp()
        mid = self.ws_feed.get_mid_price()
        spread = self.ws_feed.get_spread()

        if ltp <= 0:
            logger.warning("[ENTRY] WebSocket LTP unavailable, using mark price")
            ltp = mark_price
            mid = mark_price

        # Slippage estimate: if spread > 0.1%, log warning
        spread_pct = spread / mid * 100 if mid > 0 else 0
        if spread_pct > 0.1:
            logger.warning(f"[ENTRY] Wide spread: {spread_pct:.3f}% | bid={self.ws_feed.data.best_bid:.2f} ask={self.ws_feed.data.best_ask:.2f}")

        # F3: cross-venue basis guard — reject if Binance and CoinDCX diverge.
        allowed, _basis = self._basis_guard(setup["side"], mid if mid > 0 else mark_price)
        if not allowed:
            return

        # Adjust entry price to use mid price (fairer than LTP which can be stale).
        # F3: nudge the trigger toward the fill venue by the basis buffer so risk
        # sizing reflects the price we'll actually fill on at CoinDCX.
        entry_price = mid
        buf = self.cfg.entry_basis_buffer if (self.cfg and getattr(self.cfg, "basis_guard_enabled", False)) else 0.0
        if buf:
            entry_price = mid * (1 + buf) if setup["side"] == PositionSide.LONG else mid * (1 - buf)

        # Recalculate SL/TP based on actual entry price
        if setup["side"] == PositionSide.LONG:
            sl = entry_price * (1 - 0.007)  # Use Playbook A SL as default
            tp = entry_price * (1 + 0.010)
        else:
            sl = entry_price * (1 + 0.007)
            tp = entry_price * (1 - 0.010)

        # Update setup with actual entry price
        setup["entry_price"] = entry_price
        setup["sl_price"] = sl
        if "tp_price" in setup:
            setup["tp_price"] = tp
        else:
            for tp_level in setup.get("tp_levels", []):
                if setup["side"] == PositionSide.LONG:
                    tp_level["price"] = entry_price * (1 + 0.010 if tp_level["label"] == "TP1" else 0.020)
                else:
                    tp_level["price"] = entry_price * (1 - 0.010 if tp_level["label"] == "TP1" else 0.020)

        # Risk-based sizing from stop distance (2% risk per trade)
        stop_distance = abs(entry_price - setup["sl_price"])
        risk_budget = self.wallet.margin_balance * Decimal("0.02")
        size_multiplier = min(final_score / dynamic_threshold, 1.0)
        risk_budget *= Decimal(str(size_multiplier))
        stop_distance_dec = Decimal(str(stop_distance))
        quantity = (risk_budget / stop_distance_dec) if stop_distance_dec > 0 else Decimal("0")

        trade_id = str(uuid.uuid4())[:8]

        # Open position
        pos = self.wallet.open_position(
            self.symbol,
            setup,
            entry_price,
            custom_margin=None,
            custom_quantity=quantity,
        )

        if pos:
            self.risk_manager.record_open()
            self.adaptive_threshold.record_trade()

            # Calculate slippage
            intended = setup["entry_price"]
            actual = entry_price
            slippage = abs(actual - intended) / intended * 100 if intended > 0 else 0

            self.journal.log_open(
                trade_id=trade_id,
                symbol=self.symbol,
                regime=regime.value,
                regime_score=regime_score,
                setup=setup,
                technical_score=tech_score,
                llm_advice=advice.to_dict() if self.advisor and advice else None,
                llm_weight=llm_weight,
                final_score=final_score,
                margin=pos.margin_used,
                notional=pos.notional,
                entry_price=entry_price,
                funding_rate=funding_rate,
                oi_delta=oi_delta,
                taker_ratio=taker_ratio,
            )

            logger.info(
                f"[EXECUTED] Trade {trade_id} | Entry={entry_price:.2f} | "
                f"Margin={pos.margin_used:.2f} | Score={final_score:.2f} | "
                f"Spread={spread_pct:.3f}% | Slippage={slippage:.3f}%"
            )

            # Publish Event for Telegram
            if self.event_bus:
                from .events import TradeOpenedEvent
                self.event_bus.publish(TradeOpenedEvent(
                    symbol=self.symbol,
                    side=setup["side"].value,
                    leverage=self.wallet.leverage,
                    entry_price=entry_price,
                    stop_loss=sl,
                    take_profit=tp,
                    margin=pos.margin_used,
                    notional=pos.notional,
                    regime=regime.value,
                    tech_score=tech_score,
                    llm_decision="ALLOW" if final_score >= dynamic_threshold else "LLM_VETOED",
                    funding=funding_rate,
                    oi_delta=oi_delta,
                    liquidation_price=pos.liquidation_price
                ))

    # ── WebSocket Callbacks ──

    def _on_mark_price(self, mark_price: float, funding_rate: float):
        """Called every 1s when mark price updates."""
        # Can be used for real-time PnL display or alerts
        pass

    def _on_kline(self, interval: str, candle: dict):
        """Called when kline updates (every candle close)."""
        if candle.get("is_closed"):
            logger.debug(f"[WS] {interval} candle closed: {candle['close']:.2f}")

    def _on_book_ticker(self, bid: float, ask: float):
        """Called when best bid/ask changes."""
        # Can be used for spread monitoring
        pass

    # ── Backtest (REST-only mode) ──

    def backtest(self, days: int = 14) -> pd.DataFrame:
        """Run walk-forward backtest using REST data only."""
        from .engine import TradingEngine
        # Use the REST-only engine for backtest
        rest_engine = TradingEngine(
            symbol=self.symbol,
            initial_balance=self.wallet.wallet_balance,
            leverage=self.wallet.leverage,
        )
        return rest_engine.backtest(days=days)


def main():
    parser = argparse.ArgumentParser(description="Crypto Trader v4 — WebSocket Edition")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL)
    parser.add_argument("--balance", type=float, default=1_000.0)
    parser.add_argument("--leverage", type=int, default=LEVERAGE)
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--llm-host", default=None, help="Ollama host URL (defaults to OLLAMA_HOST env var)")
    parser.add_argument("--llm-model", default=None, help="Ollama model name (defaults to OLLAMA_MODEL env var)")
    parser.add_argument("--log-responses", action="store_true", help="Log all REST API, WS, and LLM JSON outputs (master toggle)")
    parser.add_argument("--log-rest", action="store_true", help="Log Binance REST API request/response JSON")
    parser.add_argument("--log-ws", action="store_true", help="Log Binance WebSocket message JSON")
    parser.add_argument("--log-llm", action="store_true", help="Log Ollama LLM prompt and response JSON")
    parser.add_argument("--tick", type=int, default=300, help="Signal tick interval (seconds)")
    parser.add_argument("--backtest-days", type=int, default=None)
    args = parser.parse_args()

    from .logger_config import configure_colored_logging
    configure_colored_logging(level=logging.INFO)

    engine = WebSocketTradingEngine(
        symbol=args.symbol,
        initial_balance=args.balance,
        leverage=args.leverage,
        use_llm=not args.no_llm,
        llm_host=args.llm_host,
        llm_model=args.llm_model,
        log_responses=args.log_responses,
        log_rest=args.log_rest,
        log_ws=args.log_ws,
        log_llm=args.log_llm,
    )

    if args.backtest_days:
        logger.info(f"Backtesting {args.backtest_days} days...")
        df = engine.backtest(days=args.backtest_days)
        print(df.tail(20).to_string(index=False))
        engine.wallet.print_summary()
    else:
        engine.run_loop(signal_interval_seconds=args.tick)


if __name__ == "__main__":
    main()
