"""
crypto_trader.engine_ws — WebSocket-Enhanced Trading Engine
============================================================
Hybrid architecture:
    • REST: Historical klines (4H, 1H), funding, OI, LLM context
    • WebSocket: Real-time LTP, mark price, bid/ask for entries/exits

Entry timing: Uses WebSocket LTP for precise entry execution
Exit monitoring: WebSocket position manager checks SL/TP/Trail every 1s
Signal generation: Still uses REST 1H/4H close for technical analysis

Author: Generated by Kimi K2.6
"""

import os
import time
import uuid
import logging
import argparse
from dataclasses import dataclass, field as dc_field
from decimal import Decimal, ROUND_UP
from datetime import datetime, timezone
from typing import Optional

import pandas as pd

from .data_feed import BinanceDataFeed
from .exchanges.resilient_data_feed import StaleCandlesError
from .ws_client import BinanceWebSocketFeed, WebSocketPositionManager
from .wallet import EnhancedFuturesWallet, PositionSide
from .risk import RiskManager, AdaptiveThresholdManager, MarginEngine, LeverageEngine
from .playbooks import PlaybookA, PlaybookB, PlaybookAres, PlaybookVolExhaust, PlaybookSweepMSS
from .strategies.supertrend2 import PlaybookSupertrend2
from .strategies.mean_reversion import PlaybookMeanReversion
from .strategies.mr_state import MRStateManager
from .strategies.router import StrategyRouter, RouterResult, build_legacy_router
from .reconciliation import ExchangeStateReconciler
from .regime import (
    MarketRegimeAnalyzer, MarketRegime, ExtendedRegime,
    RegimeClassifier, RegimeContext, calculate_rvol, compute_ema,
)
from .session import get_session_context, TradingSession
from .llm_advisor import OllamaAdvisor, FINAL_SCORE_THRESHOLD, build_advisor
from .journal import TradeJournal, TradeOutcomeJournal, TradeOutcomeRecord
from .config_store import ConfigStore
from .structure import MarketStructureAnalyzer
from .config import load_config

logger = logging.getLogger("crypto_trader.engine_ws")

DEFAULT_SYMBOL = "SOLUSDT"
LEVERAGE = 5
FUNDING_EXTREME = 0.0005
DEFAULT_SL_PCT = 0.007
DEFAULT_TP1_PCT = 0.010
DEFAULT_TP2_PCT = 0.020


@dataclass
class EntryContext:
    """Bundles all inputs for entry evaluation/execution — replaces 11-13 positional args."""
    setup: dict
    final_score: float
    llm_weight: float
    explanation: str
    mark_price: float
    funding_rate: float
    oi_delta: float
    taker_ratio: float
    tech_score: float
    regime: object          # MarketRegime
    regime_score: float
    advice: object          # Optional[LLMAdvice]
    dynamic_threshold: float
    regime_ctx: object = None   # Optional[RegimeContext]


class WebSocketTradingEngine:
    """
    Hybrid engine: REST for signals, WebSocket for execution.

    Architecture:
        REST (5-min tick): Fetch 4H/1H → analyze regime → generate signal → LLM fusion
        WebSocket (1s): Monitor LTP → check SL/TP/Trail → execute entries/exits
    """

    def __init__(
        self,
        symbol: str = DEFAULT_SYMBOL,
        initial_balance: float = 1_000.0,
        leverage: int = LEVERAGE,
        use_llm: bool = True,
        llm_host: str = None,
        llm_model: str = None,
        log_responses: bool = False,
        log_rest: bool = False,
        log_ws: bool = False,
        log_llm: bool = False,
        wallet = None,
        event_bus = None,
        cfg = None,
        signal_publisher = None,
        risk_budget_fraction: float = 1.0,
        funding_arb = None,
    ):
        self.symbol = symbol.upper()
        self.use_llm = use_llm
        self.event_bus = event_bus
        self.cfg = cfg
        # Optional delta-neutral funding-arb manager (Strategy C). Runs alongside
        # the directional signal tick; None unless wired by the launcher.
        self.funding_arb = funding_arb
        # When set (live + Redis execution bus), entries are PUBLISHED as signals
        # and executed by the in-process consumer (shared wallet) — giving the
        # idempotency lock / DLQ / PEL-recovery / risk-gate safety on the live
        # entry path. When None, the hardened direct path runs unchanged.
        self.signal_publisher = signal_publisher
        # Fraction of the per-trade risk budget this engine may use. With a
        # SHARED wallet across N symbols (multi_engine), each engine sizes off
        # the full balance, so without this N symbols would each risk the full
        # 2% → up to 2N% concurrent. Set to 1/N to bound total exposure.
        self.risk_budget_fraction = max(0.0, min(1.0, float(risk_budget_fraction)))
        # CoinDCX market data for the cross-venue basis guard (F3). Public, no
        # creds; built lazily so paper/tests without network stay light.
        self._coindcx_md = None

        rest_logged = log_responses or log_rest
        ws_logged = log_responses or log_ws
        llm_logged = log_responses or log_llm

        # REST client (for historical data, funding, OI)
        self.data_feed = BinanceDataFeed(log_responses=rest_logged)

        # WebSocket client (for real-time LTP, mark price, bid/ask)
        self.ws_feed = BinanceWebSocketFeed(
            symbol=self.symbol,
            on_mark_price=self._on_mark_price,
            on_kline=self._on_kline,
            on_book_ticker=self._on_book_ticker,
            log_responses=ws_logged,
        )

        if wallet:
            self.wallet = wallet
        else:
            self.wallet = EnhancedFuturesWallet(
                symbol=self.symbol,
                initial_balance=initial_balance,
                leverage=leverage,
            )

        if cfg:
            self.risk_manager = RiskManager(
                max_daily_trades=cfg.max_daily_trades,
                max_consecutive_losses=cfg.max_consecutive_losses,
                max_drawdown_pct=cfg.max_drawdown_pct,
                max_daily_drawdown_pct=cfg.max_daily_drawdown_pct,
                cooldown_after_loss_minutes=cfg.cooldown_after_loss_minutes,
                max_orders_per_minute=cfg.max_orders_per_minute,
                max_margin_ratio=cfg.max_margin_ratio,
            )
        else:
            _default_cfg = load_config()
            self.risk_manager = RiskManager(
                max_daily_trades=_default_cfg.max_daily_trades,
                max_consecutive_losses=_default_cfg.max_consecutive_losses,
                max_daily_drawdown_pct=_default_cfg.max_daily_drawdown_pct,
                cooldown_after_loss_minutes=_default_cfg.cooldown_after_loss_minutes,
            )
        _base_threshold = cfg.final_score_threshold if cfg else FINAL_SCORE_THRESHOLD
        _min_threshold = cfg.adaptive_min_threshold if cfg else 0.45
        _decay_rate = cfg.adaptive_decay_per_hour if cfg else 0.01
        _target_trades = cfg.adaptive_target_trades_per_day if cfg else 2.0
        self.adaptive_threshold = AdaptiveThresholdManager(
            base_threshold=_base_threshold,
            min_threshold=_min_threshold,
            decay_per_hour=_decay_rate,
            target_trades_per_day=_target_trades,
        )

        self.margin_engine = MarginEngine()
        self.leverage_engine = LeverageEngine()
        self.mr_state = MRStateManager(self.symbol)

        self.reconciler = ExchangeStateReconciler(
            execution_engine=self.wallet.execution_engine,
            wallet=self.wallet,
            risk_manager=self.risk_manager
        )

        if self.wallet.get_open_position(self.symbol):
            self.mr_state.reconcile_on_startup(self.wallet.get_open_position(self.symbol))
            # PRD §18 / SRD §5.3: on restart with an open position, immediately
            # reconcile against the venue and recreate a missing stop-loss before
            # resuming — don't wait for the 60s periodic reconcile tick.
            try:
                self.reconciler.reconcile_symbol(self.symbol)
            except Exception as e:
                logger.error("[ENGINE] Startup reconciliation failed for %s: %s", self.symbol, e)

        # Strategy
        self.regime_analyzer = MarketRegimeAnalyzer()
        self.playbook_a = PlaybookA()
        self.playbook_b = PlaybookB()
        self.playbook_ares = PlaybookAres()
        self.playbook_volx = PlaybookVolExhaust()
        self.playbook_sweep = PlaybookSweepMSS()
        self._playbook_registry: dict = {
            pb.name: pb for pb in [
                self.playbook_a, self.playbook_b, self.playbook_ares,
                self.playbook_volx, self.playbook_sweep,
            ]
        }

        # Supertrend2 playbook (instantiated from cfg when strategy_mode=supertrend2)
        self.playbook_st2: Optional[PlaybookSupertrend2] = None
        if cfg and getattr(cfg, "strategy_mode", "legacy") == "supertrend2":
            self.playbook_st2 = PlaybookSupertrend2(
                atr_period=getattr(cfg, "st2_atr_period", 10),
                factor=getattr(cfg, "st2_factor", 3.0),
                use_adaptive_atr=getattr(cfg, "st2_use_adaptive_atr", True),
                timeframe=getattr(cfg, "st2_timeframe", "1h"),
                htf_timeframe=getattr(cfg, "st2_htf_timeframe", "4h"),
                entry_mode=getattr(cfg, "st2_entry_mode", "flip"),
                retracement_pct=getattr(cfg, "st2_retracement_pct", 1.0),
                flip_lookback=getattr(cfg, "st2_flip_lookback", 5),
                use_htf_filter=getattr(cfg, "st2_use_htf_filter", True),
                use_vol_filter=getattr(cfg, "st2_use_vol_filter", False),
                vol_multiplier=getattr(cfg, "st2_vol_multiplier", 1.2),
                use_adx_filter=getattr(cfg, "st2_use_adx_filter", False),
                adx_threshold=getattr(cfg, "st2_adx_threshold", 20),
                tp1_pct=getattr(cfg, "st2_tp1_pct", 1.0),
                use_tp=getattr(cfg, "st2_use_tp", True),
                sl_mode=getattr(cfg, "st2_sl_mode", "supertrend"),
                sl_pct=getattr(cfg, "st2_sl_pct", 1.5),
                sl_atr_mult=getattr(cfg, "st2_sl_atr_mult", 2.5),
                max_hold_hours=getattr(cfg, "st2_max_hold_hours", 168),
            )
            logger.info(
                "[ST2] Supertrend2 mode active: factor=%.1f atr=%d adaptive=%s "
                "primary_tf=%s htf_tf=%s entry_mode=%s htf_filter=%s",
                self.playbook_st2.factor,
                self.playbook_st2.atr_period,
                self.playbook_st2.use_adaptive_atr,
                self.playbook_st2.timeframe,
                self.playbook_st2.htf_timeframe,
                self.playbook_st2.entry_mode,
                self.playbook_st2.use_htf_filter,
            )

        # Mean Reversion playbook (instantiated from cfg when strategy_mode=mean_reversion)
        self.playbook_mr: Optional[PlaybookMeanReversion] = None
        if cfg and getattr(cfg, "strategy_mode", "legacy") == "mean_reversion":
            self.playbook_mr = PlaybookMeanReversion(
                sma_period=getattr(cfg, "mr_sma_period", 20),
                entry_band=getattr(cfg, "mr_entry_band", 0.015),
                stop_loss_pct=getattr(cfg, "mr_stop_loss_pct", 0.008),
                timeframe=getattr(cfg, "mr_timeframe", "15m"),
            )
            logger.info(
                "[MR] Mean Reversion mode active: SMA%d entry_band=%.3f%% sl_pct=%.3f%% "
                "timeframe=%s symbol=%s",
                self.playbook_mr.sma_period,
                self.playbook_mr.entry_band * 100,
                self.playbook_mr.stop_loss_pct * 100,
                self.playbook_mr.timeframe,
                self.symbol,
            )

        # Regime / Session engine
        _rc_kwargs = {}
        if cfg:
            _rc_kwargs = dict(
                rvol_dead=cfg.rvol_dead_threshold,
                rvol_weak=cfg.rvol_weak_threshold,
                rvol_strong=cfg.rvol_strong_threshold,
                size_high=cfg.regime_size_multiplier_high,
                size_low=cfg.regime_size_multiplier_low,
            )
        self.regime_classifier = RegimeClassifier(**_rc_kwargs)

        # Journal
        self.journal = TradeJournal()
        # Closed-trade outcome substrate (features-at-entry + outcome-at-exit).
        # Open-side context is cached here at log_open, keyed by symbol (one
        # engine = one symbol = at most one open position), then joined with the
        # TradeClosedEvent in _on_trade_closed to emit one TradeOutcomeRecord.
        self.outcome_journal = TradeOutcomeJournal()
        self._open_features: dict = {}
        # Runtime config hot-reload: polled once per signal tick. Picks up the
        # overrides file written by the calibration approver without a restart.
        self.config_store = ConfigStore()
        # SL-defining overrides that arrived while a position was open; retried
        # every tick until the symbol is flat, then applied.
        self._pending_flat_overrides: dict = {}

        # LLM
        self.advisor = None
        self._llm_thread = None
        self.advisor = build_advisor(use_llm, llm_host=llm_host, llm_model=llm_model, llm_logged=llm_logged)

        # WebSocket position manager (high-frequency exits)
        self.ws_pm = WebSocketPositionManager(
            ws_feed=self.ws_feed,
            wallet=self.wallet,
            check_interval_ms=1000,  # Check every 1 second
            event_bus=self.event_bus,
            # G4: drive the authoritative margin guard on the 1s loop (every ~5s),
            # not only on the 5-min signal tick — liquidation can't wait 5 min.
            health_check=self._check_authoritative_health,
            # A1: skip software exits on prices older than this.
            feed_stale_ms=(cfg.feed_stale_ms if cfg else 15000),
        )

        # State
        self._last_signal_candle_ms = 0
        self._pending_entry = None  # Signal waiting for WebSocket confirmation
        self._halted = False

        # Command Listeners
        if self.event_bus:
            from .events import CommandEvent, TradeClosedEvent
            self.event_bus.subscribe(CommandEvent, self._handle_command)
            self.event_bus.subscribe(TradeClosedEvent, self._on_trade_closed)

    def _on_trade_closed(self, event):
        """Update risk manager when a trade is closed.

        This runs as an event-bus subscriber. Telemetry/risk-bookkeeping must
        NEVER crash the trade-close path: if the bus does not isolate subscriber
        exceptions, an unexpected throw here would propagate back into the
        publisher (wallet.close_position). So the entire body is wrapped in a
        swallow-and-log guard.
        """
        try:
            if event.symbol != self.symbol:
                return
            # Pass the post-close wallet balance so the daily-loss HALT in
            # record_close() actually runs (it reconstructs the day's opening
            # balance as wallet_balance - daily_pnl, matching the pre-trade gate's
            # initial_daily_balance at line ~1157). A balance-read failure must
            # NOT skip risk bookkeeping — fall back to None so record_close still
            # runs (gate-only, no post-close halt).
            try:
                post_close_balance = float(self.wallet.wallet_balance)
            except (TypeError, ValueError, AttributeError):
                post_close_balance = None
            self.risk_manager.record_close(event.realized_pnl, current_balance=post_close_balance)
            self._persist_trade_outcome(event)
        except Exception as e:
            logger.error("[ENGINE] _on_trade_closed failed for %s: %s", self.symbol, e)

    def _persist_trade_outcome(self, event):
        """Join cached open-side context with the close event and persist:
        (1) a log_close record so the JSONL open/close join + analyze_llm_contribution
            works, and (2) a unified TradeOutcomeRecord for metrics/calibration.
        Best-effort: never let analytics persistence break the trading loop."""
        try:
            open_ctx = self._open_features.pop(self.symbol, {})
            trade_id = open_ctx.get("trade_id", f"{self.symbol}-{int(event.timestamp)}")

            self.journal.log_close(
                trade_id=trade_id,
                exit_price=event.exit_price,
                realized_pnl=event.realized_pnl,
                exit_reason=event.reason,
                slippage=event.slippage,
                tds=event.tds,
            )

            closed_at = int(datetime.now(timezone.utc).timestamp() * 1000)
            opened_at = open_ctx.get("opened_at", closed_at - int(event.duration_minutes * 60_000))

            # pnl_r = realized_pnl / initial_risk_amount, where
            # initial_risk = |entry_price - stop_loss| * quantity. Only computable
            # when the open-side stop and entry/qty were captured; else leave None.
            entry_price = open_ctx.get("entry_price", 0.0)
            quantity = open_ctx.get("quantity", 0.0)
            stop_loss_price = open_ctx.get("stop_loss_price")
            pnl_r = None
            if stop_loss_price is not None and quantity:
                initial_risk = abs(entry_price - stop_loss_price) * quantity
                if initial_risk > 0:
                    pnl_r = event.realized_pnl / initial_risk

            self.outcome_journal.record(TradeOutcomeRecord(
                trade_id=trade_id,
                symbol=self.symbol,
                side=open_ctx.get("side", event.side),
                opened_at=opened_at,
                closed_at=closed_at,
                entry_price=entry_price,
                exit_price=event.exit_price,
                quantity=quantity,
                realized_pnl=event.realized_pnl,
                holding_time_s=event.duration_minutes * 60.0,
                exit_reason=event.reason,
                regime=open_ctx.get("regime"),
                regime_score=open_ctx.get("regime_score"),
                funding_rate=open_ctx.get("funding_rate"),
                vol_regime=open_ctx.get("vol_regime"),
                oi_delta=open_ctx.get("oi_delta"),
                session=open_ctx.get("session"),
                entry_reason=open_ctx.get("entry_reason"),
                llm_action=open_ctx.get("llm_action"),
                llm_confidence=open_ctx.get("llm_confidence"),
                llm_rationale=open_ctx.get("llm_rationale"),
                entry_band=open_ctx.get("entry_band"),
                stop_loss_pct=open_ctx.get("stop_loss_pct"),
                risk_per_trade_pct=open_ctx.get("risk_per_trade_pct"),
                leverage=open_ctx.get("leverage"),
                pnl_r=pnl_r,
                mfe=event.mfe,
                mae=event.mae,
                slippage_bps=event.slippage * 100.0 if event.slippage else None,
            ))
        except Exception as e:
            logger.error("[OUTCOME] Failed to persist trade outcome for %s: %s", self.symbol, e)

    def _handle_command(self, event):
        """Handle incoming commands from EventBus (e.g., Telegram)."""
        if event.command == "KILL_ALL" or (event.command == "KILL" and event.params.get("symbol") == self.symbol):
            self._halted = True
            logger.warning("[KILL] [HALTED] %s received KILL command.", self.symbol)
            # A remote KILL must flatten the live position, not just block new
            # entries — otherwise an open position rides on unattended.
            try:
                pos = self.wallet.get_open_position(self.symbol)
                if pos:
                    mark = self.ws_feed.get_ltp() or self.ws_feed.get_mid_price()
                    if not mark or mark <= 0:
                        mark = float(pos.entry_price)
                    self.wallet.close_position(self.symbol, float(mark), reason="REMOTE_KILL")
                    logger.warning("[KILL] flattened %s on remote command", self.symbol)
            except Exception as e:
                logger.error("remote KILL flatten failed for %s: %s", self.symbol, e)

        elif event.command == "RESUME_ALL" or (event.command == "RESUME" and event.params.get("symbol") == self.symbol):
            self._halted = False
            logger.info("[RESUMED] %s received RESUME command.", self.symbol)

        elif event.command == "STATUS":
            # Engine will respond via logs or potentially publish a StatusEvent
            logger.info("[STATUS] %s | Halted: %s | Pos: %s", self.symbol, self._halted, self.wallet.get_open_position(self.symbol) is not None)

    # ── Lifecycle ──

    def start(self):
        """Start WebSocket and position manager."""
        logger.info(f"[ENGINE] Starting WebSocket engine for {self.symbol}")
        self.ws_feed.start()
        self.ws_pm.start()
        # Wait for WebSocket to connect
        for _ in range(10):
            if self.ws_feed.is_connected():
                break
            time.sleep(0.5)
        logger.info(f"[ENGINE] WebSocket connected: {self.ws_feed.is_connected()}")

    def stop(self):
        """Gracefully stop all components."""
        logger.info("[ENGINE] Stopping...")
        self.ws_pm.stop()
        self.ws_feed.stop()
        logger.info("[ENGINE] Stopped")

    def _check_authoritative_health(self):
        """Monitor authoritative exchange metrics (margin ratio) and trigger kill switch if unsafe."""
        if not self.cfg or not self.cfg.is_live:
            return

        from .exchanges.coindcx_execution import CoinDCXExecutionEngine
        if not isinstance(self.wallet.execution_engine, CoinDCXExecutionEngine):
            return

        if not hasattr(self, "_consecutive_health_failures"):
            self._consecutive_health_failures = 0

        try:
            details = self.wallet.execution_engine.get_cross_margin_details()
            if details:
                self._consecutive_health_failures = 0
                ratio = float(details.get("margin_ratio_cross", 0) or 0)
                ok, reason = self.risk_manager.check_margin_ratio(ratio)
                if not ok:
                    logger.critical(f"[AUTHORITATIVE GUARD] {reason}")
                    self.risk_manager.trigger_kill_switch(reason)
                    self._halted = True
                    if self.event_bus:
                        from .events import SystemFailureEvent
                        self.event_bus.publish(SystemFailureEvent(component="margin_guard", error=reason))
                    # Halting only blocks NEW entries; an open position is still
                    # racing toward liquidation at this margin ratio. Flatten it.
                    try:
                        pos = self.wallet.get_open_position(self.symbol)
                        if pos:
                            mark = self.ws_feed.get_ltp() or self.ws_feed.get_mid_price()
                            if not mark or mark <= 0:
                                mark = float(pos.entry_price)
                            self.wallet.close_position(
                                self.symbol, float(mark),
                                reason="MARGIN_GUARD_FLATTEN",
                            )
                            logger.critical("[AUTHORITATIVE GUARD] flattened %s to avoid liquidation", self.symbol)
                    except Exception as e:
                        logger.error("margin-guard flatten failed for %s: %s", self.symbol, e)
        except Exception as e:
            logger.error("Authoritative health check failed: %s", e)
            self._consecutive_health_failures += 1
            if self._consecutive_health_failures >= 3 and self.wallet.get_open_position(self.symbol):
                reason = f"Authoritative health check failed consecutively {self._consecutive_health_failures} times while holding an active position: {e}"
                logger.critical(f"[AUTHORITATIVE GUARD] {reason} — triggering kill switch")
                self.risk_manager.trigger_kill_switch(reason)
                self._halted = True
                if self.event_bus:
                    from .events import SystemFailureEvent
                    self.event_bus.publish(SystemFailureEvent(component="margin_guard", error=reason))

    # ── Main Loop ──

    def run_loop(self, signal_interval_seconds: int = 300, max_iterations: int = None):
        """
        Unified Engine Loop:
            - 1s: Thread supervision & Authoritative Health (G3, G4)
            - 60s: Exchange State Reconciliation (G5, G9)
            - signal_interval: Signal evaluation & Playbook execution
        """
        self.start()
        iteration = 0
        last_signal_time = 0
        last_recon_time = 0

        try:
            while True:
                now = time.time()

                # 1s Task: G3: supervise the WS threads
                if not self._supervise_threads():
                    break

                # 1s Task: Authoritative health check (margin ratio guard)
                self._check_authoritative_health()

                # 60s Task: Periodic state reconciliation
                if now - last_recon_time >= 60:
                    if self.reconciler:
                        self.reconciler.reconcile_symbol(self.symbol)
                    last_recon_time = now

                # signal_interval Task: Signal generation tick
                if now - last_signal_time >= signal_interval_seconds:
                    self._signal_tick()

                    # Delta-neutral funding-arb tick
                    if self.funding_arb is not None:
                        try:
                            self.funding_arb.on_signal_tick()
                        except Exception as e:
                            logger.error("[ARB] funding-arb tick error: %s", e)

                    last_signal_time = now
                    iteration += 1
                    if max_iterations and iteration >= max_iterations:
                        break

                time.sleep(1)
        except KeyboardInterrupt:
            logger.info("Engine stopped by user")
        finally:
            self.stop()

    def _supervise_threads(self) -> bool:
        """G3: fail-stop if a background WS thread died silently.

        Returns True if it is safe to continue. On a dead feed/position-manager
        thread it trips HALT + the kill switch and halts the engine, rather than
        evaluating signals or managing positions against a stale feed.
        """
        if self.cfg is not None and not getattr(self.cfg, "thread_supervisor_enabled", True):
            return True
        dead = []
        if not self.ws_feed.is_alive():
            dead.append("ws_feed")
        if not self.ws_pm.is_alive():
            dead.append("ws_position_manager")
        if not dead:
            return True
        reason = f"WS thread(s) died: {', '.join(dead)}"
        logger.critical("[SUPERVISOR] %s — halting engine (fail-stop)", reason)
        try:
            from . import safe_mode
            safe_mode.trip_halt(reason)
        except Exception as e:
            logger.critical("[SUPERVISOR] Failed to trip HALT file: %s", e)
        if getattr(self, "risk_manager", None) is not None:
            self.risk_manager.trigger_kill_switch(reason)
        if self.event_bus:
            from .events import SystemFailureEvent
            self.event_bus.publish(SystemFailureEvent(component="thread_supervisor", error=reason))
        self._halted = True
        return False

    def _apply_runtime_overrides(self) -> None:
        """Poll the ConfigStore and apply runtime parameter overrides."""
        ov = self.config_store.poll()
        if ov is not None:
            # We got new overrides (could be empty dict if file deleted)
            for k, v in ov.items():
                cls = ConfigStore.classify(k)
                if cls == "safe":
                    # Apply immediately to cfg
                    if hasattr(self.cfg, k):
                        setattr(self.cfg, k, v)
                    # Apply to risk/adaptive/playbooks
                    if self.risk_manager is not None:
                        self.risk_manager.apply_overrides({k: v})
                    if self.adaptive_threshold is not None:
                        self.adaptive_threshold.apply_overrides({k: v})
                    if k.startswith("st2_") and self.playbook_st2 is not None:
                        self.playbook_st2.apply_overrides({k: v})
                    if k.startswith("mr_") and self.playbook_mr is not None:
                        self.playbook_mr.apply_overrides({k: v})
                elif cls == "flat_only":
                    self._pending_flat_overrides[k] = v
                elif cls == "restart":
                    logger.warning("[ConfigStore] Ignored restart-only parameter override: %s", k)
                else:
                    logger.warning("[ConfigStore] Ignored unknown/unblessed parameter override: %s", k)

        # Check if we are flat to drain flat-only overrides
        if not self._pending_flat_overrides:
            return

        position = self.wallet.get_open_position(self.symbol)
        if position is None:
            # Flat! Apply all deferred overrides
            logger.info("[ConfigStore] Symbol %s is flat — draining %d deferred flat-only overrides", self.symbol, len(self._pending_flat_overrides))
            for k, v in self._pending_flat_overrides.items():
                if hasattr(self.cfg, k):
                    setattr(self.cfg, k, v)
                if k.startswith("st2_") and self.playbook_st2 is not None:
                    self.playbook_st2.apply_overrides({k: v})
                if k.startswith("mr_") and self.playbook_mr is not None:
                    self.playbook_mr.apply_overrides({k: v})
            self._pending_flat_overrides = {}

    def _signal_tick(self):
        """Generate signals using REST data (runs every 5 min)."""
        if self._halted:
            logger.debug("[SIGNAL-TICK] %s is halted. Skipping.", self.symbol)
            return

        self._apply_runtime_overrides()

        logger.info("--- Signal Tick: %s ---", self.symbol)

        data = self._fetch_market_data()
        if data is None:
            return

        result = self._compute_regime_context(data)
        if result is None:
            return
        regime, regime_score, df_4h, rvol, adx_val, regime_ctx, session_ctx = result

        structure, structure_ltf = self._compute_market_structure(data)
        self._start_llm_async(data, regime, regime_score, regime_ctx, session_ctx, rvol)
        self._evaluate_and_enter(data, regime, regime_score, df_4h, rvol, adx_val, regime_ctx, session_ctx, structure, structure_ltf)
        self.wallet.print_summary()

    @staticmethod
    def _kline_limit(timeframe: str) -> int:
        """Return a sensible kline limit for a given timeframe string."""
        tf = timeframe.lower().strip()
        # Minutes: more bars needed for short TFs to build up ATR/indicators
        if tf.endswith("m"):
            try:
                mins = int(tf[:-1])
            except ValueError:
                return 200
            if mins <= 1:
                return 500
            if mins <= 5:
                return 400
            if mins <= 15:
                return 300
            return 200
        # Hours
        if tf.endswith("h"):
            try:
                h = int(tf[:-1])
            except ValueError:
                return 200
            return 200 if h <= 4 else 150
        # Daily / weekly / monthly
        return 200

    def _fetch_market_data(self):
        """Fetch all REST and WebSocket market data. Returns dict or None to skip tick."""
        try:
            # ── Fixed baseline TFs (used by regime, structure, LLM, legacy playbooks) ──
            df_4h = self.data_feed.get_klines(self.symbol, "4h", limit=200)
            df_1h = self.data_feed.get_klines(self.symbol, "1h", limit=150)
            df_15m = self.data_feed.get_klines(self.symbol, "15m", limit=150)
            df_5m = self.data_feed.get_klines(self.symbol, "5m", limit=150)

            # Get current context from WebSocket (real-time)
            ws_data = self.ws_feed.get_data()
            mark_price = ws_data.mark_price if ws_data.mark_price > 0 else self.data_feed.get_mark_price(self.symbol)

            funding_rate = self.data_feed.get_funding_rate(self.symbol)
            oi_data = self.data_feed.get_open_interest(self.symbol)
            taker_ratio = self.data_feed.get_taker_ratio(self.symbol)

            if mark_price <= 0:
                logger.warning(f"[WS-ENGINE] Invalid mark price {mark_price}. Skipping signal tick.")
                return None

        except StaleCandlesError as e:
            # A3: fallback klines too old — never generate a signal from stale
            # technicals. Skip the whole tick (already the behaviour; explicit
            # for clarity/observability).
            logger.warning(f"[WS-ENGINE] Stale klines — skipping signal tick: {e}")
            return None
        except Exception as e:
            logger.error(f"Data fetch failed — skipping signal tick: {e}")
            return None

        data = {
            "df_4h": df_4h, "df_1h": df_1h, "df_15m": df_15m, "df_5m": df_5m,
            "mark_price": mark_price, "funding_rate": funding_rate,
            "oi_data": oi_data, "taker_ratio": taker_ratio,
        }

        # ── ST2 configurable timeframes ──────────────────────────────────────
        # Resolve primary and HTF data for the Supertrend2 mode.  When the
        # configured TF matches a baseline already fetched above, reuse it
        # (no extra API call).  Otherwise fetch a fresh series.
        if self.playbook_st2 is not None:
            _baseline_map = {"1h": df_1h, "4h": df_4h, "15m": df_15m, "5m": df_5m}
            st2_tf = self.playbook_st2.timeframe
            st2_htf = self.playbook_st2.htf_timeframe

            if st2_tf in _baseline_map:
                data["df_st2"] = _baseline_map[st2_tf]
            else:
                try:
                    data["df_st2"] = self.data_feed.get_klines(
                        self.symbol, st2_tf, limit=self._kline_limit(st2_tf)
                    )
                    logger.debug("[ST2] Fetched primary TF %s (%d bars)", st2_tf, len(data["df_st2"]))
                except Exception as e:
                    logger.warning("[ST2] Failed to fetch primary TF %s: %s — falling back to 1h", st2_tf, e)
                    data["df_st2"] = df_1h

            if st2_htf in _baseline_map:
                data["df_st2_htf"] = _baseline_map[st2_htf]
            else:
                try:
                    data["df_st2_htf"] = self.data_feed.get_klines(
                        self.symbol, st2_htf, limit=self._kline_limit(st2_htf)
                    )
                    logger.debug("[ST2] Fetched HTF %s (%d bars)", st2_htf, len(data["df_st2_htf"]))
                except Exception as e:
                    logger.warning("[ST2] Failed to fetch HTF %s: %s — HTF filter will be skipped", st2_htf, e)
                    data["df_st2_htf"] = None

        # ── Mean Reversion configurable timeframe ────────────────────────────
        # Pre-fetch the MR kline series if the configured timeframe isn't one
        # of the baseline frames already fetched above, so _evaluate_entry_mr
        # and _mr_check_sma_exit never need to make a synchronous REST call
        # inside the signal-tick hot path.
        if self.playbook_mr is not None:
            _baseline_map_mr = {"15m": df_15m, "5m": df_5m, "1h": df_1h, "4h": df_4h}
            mr_tf = self.playbook_mr.timeframe
            if mr_tf in _baseline_map_mr:
                data["df_mr"] = _baseline_map_mr[mr_tf]
            else:
                try:
                    data["df_mr"] = self.data_feed.get_klines(
                        self.symbol, mr_tf,
                        limit=self.playbook_mr.sma_period + 10,
                    )
                    logger.debug("[MR] Fetched %s (%d bars)", mr_tf, len(data["df_mr"]))
                except Exception as e:
                    logger.warning("[MR] Failed to fetch %s klines: %s — will retry in tick", mr_tf, e)
                    data["df_mr"] = None

        return data

    def _compute_regime_context(self, data: dict):
        """Build session context, check kill zone gate, and compute extended regime.

        Returns (regime, regime_score, df_4h, rvol, adx_val, regime_ctx, session_ctx)
        or None if the tick should be skipped (kill zone gate).
        """
        df_4h = data["df_4h"]
        df_1h = data["df_1h"]

        # 1. Session context
        session_ctx = get_session_context()
        logger.info(
            f"[SESSION] {session_ctx.session.value} | "
            f"kill_zone={session_ctx.is_kill_zone} ({session_ctx.kill_zone_name or 'none'}) | "
            f"UTC={session_ctx.utc_hour:02d}h"
        )

        # Kill zone gate: if enabled, skip signal evaluation outside kill zones
        require_kz = getattr(self.cfg, "require_kill_zone", False) if self.cfg else False
        if require_kz and not session_ctx.is_kill_zone:
            logger.info("[SIGNAL-TICK] Outside kill zone — skipping (REQUIRE_KILL_ZONE=True)")
            return None

        # 2. Regime analysis
        regime, regime_score, df_4h = self.regime_analyzer.analyze(df_4h)

        # RVOL on the 1H frame (most relevant for intraday entries)
        rvol = calculate_rvol(df_1h, window=20)

        # OI delta: would require storing historical OI to compute a proper delta.
        # Using 0.0 for now — the raw oi value is still passed to the LLM prompt.
        oi_delta = 0.0

        # Liquidation intensity: normalise recent liquidation volume to 0–1
        liquidation_intensity = 0.0
        try:
            liq_df = self.data_feed.get_liquidation_orders(self.symbol)
            if liq_df is not None and not liq_df.empty and "quoteQty" in liq_df.columns:
                liq_vol = float(liq_df["quoteQty"].sum())
                # Normalise against a rough baseline of 1M USDT liquidations
                liquidation_intensity = min(liq_vol / 1_000_000, 1.0)
        except Exception as e:
            logger.debug("[SIGNAL-TICK] liquidation fetch skipped: %s", e)

        # Spread estimate for chaos detection (use WS spread if available)
        ws_spread_pct = 0.0
        try:
            _spread = self.ws_feed.get_spread()
            _mid = self.ws_feed.get_mid_price()
            if _mid > 0:
                ws_spread_pct = (_spread / _mid) * 100
        except Exception as e:
            logger.debug("[SIGNAL-TICK] spread fetch skipped: %s", e)

        # Extended regime classification
        adx_val = float(df_4h["adx"].iloc[-1]) if "adx" in df_4h.columns else 0.0
        regime_ctx: RegimeContext = self.regime_classifier.build_context(
            base_regime=regime,
            adx=adx_val,
            rvol=rvol,
            oi_delta=oi_delta,
            liquidation_intensity=liquidation_intensity,
            session_name=session_ctx.session.value,
            is_kill_zone=session_ctx.is_kill_zone,
            spread_pct=ws_spread_pct,
        )
        logger.info(
            f"[REGIME] {regime.value} (score={regime_score:.2f}) | "
            f"extended={regime_ctx.extended.value} | "
            f"rvol={rvol:.2f} | adx={adx_val:.1f} | size_x={regime_ctx.size_multiplier:.2f}"
        )

        return regime, regime_score, df_4h, rvol, adx_val, regime_ctx, session_ctx

    def _compute_market_structure(self, data: dict):
        """Run SMC market structure analysis on 1H and 15M frames.

        Returns (structure, structure_ltf). Returns (None, None) on exception.
        """
        df_1h = data["df_1h"]
        df_15m = data["df_15m"]

        # 3. Market structure analysis (SMC signals for playbook gating)
        structure = None
        structure_ltf = None
        try:
            msa = MarketStructureAnalyzer(df_1h, swing_window=3)
            structure = msa.analyze()
            recent_bos = structure.get("recent_bos")
            logger.debug(
                f"[STRUCTURE] BOS={recent_bos['type'] if recent_bos else 'None'} | "
                f"OBs={len(structure.get('unmitigated_order_blocks', []))} | "
                f"FVGs={len(structure.get('unmitigated_fvgs', []))}"
            )
            # Lower-timeframe structure for sweep+MSS confirmation (PlaybookSweepMSS).
            msa_ltf = MarketStructureAnalyzer(df_15m, swing_window=3)
            structure_ltf = msa_ltf.analyze()
        except Exception as e:
            logger.warning(f"[STRUCTURE] MarketStructureAnalyzer failed: {e}")
            structure = None
            structure_ltf = None

        return structure, structure_ltf

    def _start_llm_async(self, data: dict, regime, regime_score, regime_ctx, session_ctx, rvol):
        """Start the LLM advice thread asynchronously (step 4)."""
        if not (self.use_llm and self.advisor):
            return
        # Skip LLM when regime hard-blocks entries — saves GPU for useful calls.
        _dead_regimes = {"DEAD_MARKET", "HIGH_RISK_CHAOS", "LIQUIDATION_EVENT"}
        if regime_ctx is not None and regime_ctx.extended.value in _dead_regimes:
            logger.debug("[LLM] Skipping — regime=%s blocked", regime_ctx.extended.value)
            return
        # Skip if position already open — no entry evaluation will run.
        pos = self.wallet.get_open_position(self.symbol)
        if pos:
            logger.debug("[LLM] Skipping — position already open for %s", self.symbol)
            return
        if self._llm_thread is None or not self._llm_thread.is_alive():
            self._llm_thread = self.advisor.get_advice_async(
                symbol=self.symbol,
                df_5m=data["df_5m"],
                df_15m=data["df_15m"],
                df_1h=data["df_1h"],
                df_4h=data["df_4h"],
                regime=regime.value,
                regime_score=regime_score,
                mark_price=data["mark_price"],
                funding_rate=data["funding_rate"],
                oi_delta=0.0,
                taker_ratio=data["taker_ratio"],
                open_positions=[],
                market_regime=regime_ctx.extended.value,
                session=session_ctx.session.value,
                is_kill_zone=session_ctx.is_kill_zone,
                rvol=rvol,
            )

    # ── Supertrend2 helpers ───────────────────────────────────────────────────

    def _st2_check_flip_exit(self, data: dict, pos) -> bool:
        """
        Check whether the Supertrend2 direction has just flipped against the
        open position. If so, close it and return True.

        Called every signal tick (5 min) when strategy_mode == "supertrend2".
        The 1H Supertrend can flip at most once per hour so this granularity
        is more than sufficient.
        """
        if self.playbook_st2 is None:
            return False
        try:
            df_st2 = data.get("df_st2", data["df_1h"])
            if df_st2 is None or len(df_st2) < self.playbook_st2._min_bars():
                return False

            from .strategies.supertrend2 import compute_supertrend2
            atr_len = self.playbook_st2._effective_atr_len()
            _, direction = compute_supertrend2(df_st2, self.playbook_st2.factor, atr_len)

            curr_dir = int(direction.iloc[-1])
            prev_dir = int(direction.iloc[-2])

            if curr_dir == prev_dir:
                return False  # no flip this bar

            mark = data["mark_price"]
            from .wallet import PositionSide

            if pos.side == PositionSide.LONG and curr_dir == 1 and prev_dir == -1:
                self.wallet.close_position(self.symbol, float(mark), reason="ST2_FLIP_EXIT")
                logger.info(
                    "[ST2 EXIT] Long closed — Supertrend flipped to downtrend @ %.4f", mark
                )
                if self.event_bus:
                    from .events import SystemFailureEvent  # noqa: reuse log channel
                return True

            if pos.side == PositionSide.SHORT and curr_dir == -1 and prev_dir == 1:
                self.wallet.close_position(self.symbol, float(mark), reason="ST2_FLIP_EXIT")
                logger.info(
                    "[ST2 EXIT] Short closed — Supertrend flipped to uptrend @ %.4f", mark
                )
                return True

        except Exception as exc:
            logger.warning("[ST2 EXIT] flip-exit check failed: %s", exc)

        return False

    def _evaluate_entry_st2(
        self,
        data: dict,
        mark_price: float,
        funding_rate: float,
        taker_ratio: float,
        regime_ctx,
    ) -> None:
        """
        Entry evaluation path for strategy_mode == "supertrend2".

        Bypasses legacy playbooks, LLM fusion, and regime routing.
        Only the Supertrend2 flip/retracement signal and the funding-rate
        guard (safety net) control entry.  All risk-manager checks (daily
        limits, drawdown) and the execution path (_execute_entry) are reused.
        """
        if self.playbook_st2 is None:
            return

        df_st2 = data.get("df_st2", data["df_1h"])
        df_st2_htf = data.get("df_st2_htf", data["df_4h"]) if self.playbook_st2.use_htf_filter else None

        setup = self.playbook_st2.evaluate(df_st2, df_st2_htf)
        if not setup:
            logger.debug("[ST2 ENTRY] No signal this tick")
            return

        logger.info("[ST2 SIGNAL] %s | %s", setup["side"].value, setup["reason"])

        # Funding-rate extreme guard (keep for safety)
        _funding_extreme = self.cfg.funding_extreme_threshold if self.cfg else FUNDING_EXTREME
        if (
            (setup["side"].value in ("LONG", "BUY") and funding_rate > _funding_extreme)
            or (setup["side"].value in ("SHORT", "SELL") and funding_rate < -_funding_extreme)
        ):
            logger.info(
                "[ST2 BLOCKED] Funding extreme %+.4%% (threshold %.4%%)",
                funding_rate, _funding_extreme,
            )
            return

        dynamic_threshold = self.adaptive_threshold.get_threshold()

        self._execute_entry(EntryContext(
            setup=setup,
            final_score=1.0,          # ST2 signal is binary; always passes threshold
            llm_weight=0.0,
            explanation="Supertrend2 signal",
            mark_price=mark_price,
            funding_rate=funding_rate,
            oi_delta=0.0,
            taker_ratio=taker_ratio,
            tech_score=1.0,
            regime=None,
            regime_score=1.0,
            advice=None,
            dynamic_threshold=dynamic_threshold,
            regime_ctx=regime_ctx,
        ))

    # ─────────────────────────────────────────────────────────────────────────

    def _mr_check_sma_exit(self, data: dict, pos) -> bool:
        """
        Check whether price has reverted to the SMA (mean-reversion exit).

        Called every signal tick when strategy_mode == "mean_reversion" and a
        position is open. Returns True if the position was closed.
        """
        if self.playbook_mr is None:
            return False
        try:
            # Use pre-fetched MR dataframe (from _fetch_market_data) or fall back
            df_mr = data.get("df_mr")
            if df_mr is None:
                mr_tf = self.playbook_mr.timeframe
                _baseline_map = {
                    "15m": data.get("df_15m"),
                    "5m": data.get("df_5m"),
                    "1h": data.get("df_1h"),
                    "4h": data.get("df_4h"),
                }
                df_mr = _baseline_map.get(mr_tf)
            if df_mr is None:
                try:
                    df_mr = self.data_feed.get_klines(
                        self.symbol, self.playbook_mr.timeframe,
                        limit=self.playbook_mr.sma_period + 10
                    )
                except Exception as e:
                    logger.warning("[MR EXIT] Could not fetch klines: %s", e)
                    return False

            exit_reason = self.playbook_mr.check_sma_exit(df_mr, pos.side)
            if exit_reason is None:
                return False

            mark = data["mark_price"]
            self.wallet.close_position(self.symbol, float(mark), reason=exit_reason)
            logger.info(
                "[MR EXIT] %s %s position closed — mean reverted. mark=%.4f",
                self.symbol, pos.side.value, mark,
            )
            if self.event_bus:
                from .events import TradeClosedEvent
                # TradeClosedEvent is emitted by wallet.close_position via the
                # event_hook chain; no need to re-emit here.
            return True

        except Exception as exc:
            logger.warning("[MR EXIT] SMA exit check failed for %s: %s", self.symbol, exc)
            return False

    def _evaluate_entry_mr(
        self,
        data: dict,
        mark_price: float,
        funding_rate: float,
        taker_ratio: float,
        regime_ctx,
    ) -> None:
        """
        Entry evaluation path for strategy_mode == "mean_reversion".

        Implements the SRD/PRD specification:
        - Computes SMA(mr_sma_period) on last CLOSED candle of mr_timeframe.
        - Opens LONG  when close <= SMA * (1 - entry_band)   [oversold]
        - Opens SHORT when close >= SMA * (1 + entry_band)   [overbought]
        - Funding-rate guard blocks entries when funding is extreme.
        - All risk-manager guards (daily limits, drawdown, kill-switch) are
          applied by the calling layer before this method is called.
        - Works for any symbol in the WATCHLIST (symbol-agnostic).
        """
        if self.playbook_mr is None:
            return

        # Resolve the configured MR timeframe DataFrame — use pre-fetched
        # data["df_mr"] if available (set by _fetch_market_data), falling back
        # to baseline frames or a fresh REST call for non-standard timeframes.
        df_mr = data.get("df_mr")
        if df_mr is None:
            mr_tf = self.playbook_mr.timeframe
            _baseline_map = {
                "15m": data.get("df_15m"),
                "5m":  data.get("df_5m"),
                "1h":  data.get("df_1h"),
                "4h":  data.get("df_4h"),
            }
            df_mr = _baseline_map.get(mr_tf)
        if df_mr is None:
            try:
                df_mr = self.data_feed.get_klines(
                    self.symbol, self.playbook_mr.timeframe,
                    limit=self.playbook_mr.sma_period + 10
                )
            except Exception as e:
                logger.warning("[MR ENTRY] Could not fetch klines for %s: %s", self.symbol, e)
                return

        setup = self.playbook_mr.evaluate(df_mr)
        if not setup:
            logger.debug("[MR ENTRY] No signal this tick for %s", self.symbol)
            return

        logger.info(
            "[MR SIGNAL] %s | %s | %s",
            self.symbol, setup["side"].value, setup["reason"]
        )

        # Funding-rate extreme guard (PRD §7)
        _funding_extreme = self.cfg.funding_extreme_threshold if self.cfg else FUNDING_EXTREME
        if (
            (setup["side"] == PositionSide.LONG and funding_rate > _funding_extreme)
            or (setup["side"] == PositionSide.SHORT and funding_rate < -_funding_extreme)
        ):
            logger.info(
                "[MR BLOCKED] %s — funding extreme %+.4f%% (threshold %.4f%%)",
                self.symbol, funding_rate * 100, _funding_extreme * 100,
            )
            return

        dynamic_threshold = self.adaptive_threshold.get_threshold()

        # Mean-reversion signal score is treated as the authoritative technical
        # score (no LLM fusion for now — keeps execution deterministic as the
        # PRD specifies).  Passes directly to _execute_entry.
        self._execute_entry(EntryContext(
            setup=setup,
            final_score=setup["score"],
            llm_weight=0.0,
            explanation=f"MeanReversion SMA{self.playbook_mr.sma_period} signal",
            mark_price=mark_price,
            funding_rate=funding_rate,
            oi_delta=0.0,
            taker_ratio=taker_ratio,
            tech_score=setup["score"],
            regime=None,
            regime_score=1.0,
            advice=None,
            dynamic_threshold=dynamic_threshold,
            regime_ctx=regime_ctx,
        ))

    # ─── Position update helpers ────────────────────────────────────────────

    def _update_open_position(self, data: dict, regime, session_ctx):
        """Update an open position if one exists (step 5.5 — AI/regime reversal exits)."""
        pos = self.wallet.get_open_position(self.symbol)
        if pos:
            # MR mode: check for SMA-touch exit before any other logic
            _mr_mode = self.cfg and getattr(self.cfg, "strategy_mode", "legacy") == "mean_reversion"
            if _mr_mode and self._mr_check_sma_exit(data, pos):
                return  # position closed by SMA reversion; skip further management

            # ST2 mode: check for Supertrend flip exit before normal SL/TP logic
            _st2_mode = self.cfg and getattr(self.cfg, "strategy_mode", "legacy") == "supertrend2"
            if _st2_mode and self._st2_check_flip_exit(data, pos):
                return  # position closed by flip; skip further position management

            df_1h = data["df_1h"]
            mark_price = data["mark_price"]
            df_1h["ema9"] = compute_ema(df_1h["close"], 9)
            ema9_val = df_1h["ema9"].iloc[-1]
            ema9_1h = float(ema9_val) if pd.notna(ema9_val) else None
            candle_close_time = int(df_1h["close_time"].iloc[-1].timestamp() * 1000)

            advice = self.advisor.get_last_advice() if (self.use_llm and self.advisor) else None
            current_llm_advice = advice.to_dict() if advice else None

            self.wallet.update_positions(
                self.symbol,
                mark_price,
                candle_close_time,
                ema9_1h,
                current_llm_advice=current_llm_advice,
                current_regime=regime.value if regime else None,
            )

    def _evaluate_and_enter(self, data: dict, regime, regime_score, df_4h, rvol, adx_val,
                            regime_ctx, session_ctx, structure, structure_ltf):
        """Perform risk check, update open position, then evaluate entry if no position open."""
        mark_price = data["mark_price"]
        funding_rate = data["funding_rate"]
        taker_ratio = data["taker_ratio"]
        df_1h = data["df_1h"]
        df_15m = data["df_15m"]

        # 5. Risk check
        self.risk_manager.update_peak_balance(self.wallet.margin_balance)
        # Assuming initial balance for daily drawdown is the wallet balance minus daily PnL
        initial_daily_balance = float(self.wallet.wallet_balance) - self.risk_manager.daily_pnl
        can_trade, risk_reason = self.risk_manager.can_trade(
            current_balance=self.wallet.margin_balance,
            initial_daily_balance=initial_daily_balance
        )
        if not can_trade:
            if not getattr(self, "_halt_published", False):
                if self.event_bus:
                    from .events import RiskHaltEvent
                    self.event_bus.publish(RiskHaltEvent(
                        reason=risk_reason,
                        daily_pnl=float(self.wallet.realized_pnl_total),
                        trades_today=self.risk_manager.daily_count
                    ))
                self._halt_published = True
            logger.info(f"[RISK] {risk_reason}")
            return
        self._halt_published = False

        # 5.5 Update position if open (to check AI and regime reversal exits)
        self._update_open_position(data, regime, session_ctx)

        # 6. Evaluate entry if no open position
        if not self.wallet.get_open_position(self.symbol) and can_trade:
            _st2_mode = self.cfg and getattr(self.cfg, "strategy_mode", "legacy") == "supertrend2"
            _mr_mode  = self.cfg and getattr(self.cfg, "strategy_mode", "legacy") == "mean_reversion"

            try:
                if _st2_mode:
                    # ── Supertrend2 path ──────────────────────────────────────
                    # Bypass legacy regime routing, profile regime filter, and LLM.
                    # The Supertrend direction flip is the sole entry gate.
                    self._evaluate_entry_st2(
                        data, mark_price, funding_rate, taker_ratio, regime_ctx
                    )
                elif _mr_mode:
                    # ── Mean Reversion path ───────────────────────────────────
                    # SMA-band signal; funding-rate guard applied inside.
                    # Symbol-agnostic: works for all WATCHLIST symbols.
                    self._evaluate_entry_mr(
                        data, mark_price, funding_rate, taker_ratio, regime_ctx
                    )
                else:
                    # ── Legacy multi-playbook path ────────────────────────────
                    # Block entry when regime forbids it
                    if not regime_ctx.allows_new_entries():
                        logger.info(
                            "[REGIME-BLOCK] No entry — extended regime is %s",
                            regime_ctx.extended.value,
                        )
                        return

                    # Profile-based regime filter
                    if self.cfg and self.cfg.allowed_regimes:
                        if regime_ctx.extended.value not in self.cfg.allowed_regimes:
                            logger.info(
                                "[PROFILE-BLOCK] %s regime not allowed by '%s' profile",
                                regime_ctx.extended.value, self.cfg.trading_profile,
                            )
                            return

                    latest_adx = df_4h["adx"].iloc[-1] if "adx" in df_4h.columns else None
                    self._evaluate_entry(
                        df_1h, df_4h, df_15m, regime, regime_score, mark_price,
                        funding_rate, 0.0, taker_ratio, structure=structure,
                        adx_1h=latest_adx, regime_ctx=regime_ctx,
                        session_ctx=session_ctx, structure_ltf=structure_ltf,
                    )

            except Exception as e:
                # Distinguish a benign pre-fill venue REJECTION from an ambiguous
                # mid-entry failure that could orphan a live position.
                #
                # A definitive 4xx order rejection (e.g. min-notional, bad params,
                # insufficient balance) is raised by place_order BEFORE any fill is
                # booked — no position exists, so halting all trading is wrong.
                # Skip this tick and keep trading. Ambiguous failures (5xx /
                # timeout / anything not provably pre-fill) still HALT + reconcile
                # because the order MIGHT be live.
                if self._is_benign_entry_rejection(e):
                    logger.warning(
                        "[ENTRY SKIP] %s — venue rejected order pre-fill (no position "
                        "opened), skipping tick: %s", self.symbol, e,
                    )
                    if self.event_bus:
                        from .events import SignalRejectedEvent
                        self.event_bus.publish(SignalRejectedEvent(
                            symbol=self.symbol, reason=f"venue_rejected: {e}",
                        ))
                    return
                # An exception mid-entry could leave an unmanaged live position.
                # Fail safe: HALT and trip the kill switch.
                logger.critical("[ENTRY FAILURE] %s — halting and reconciling: %s", self.symbol, e, exc_info=True)
                self._halted = True
                if getattr(self, "risk_manager", None) is not None:
                    self.risk_manager.trigger_kill_switch(f"entry failure: {e}")
                if self.cfg and self.cfg.is_live:
                    try:
                        from . import safe_mode
                        safe_mode.trip_halt(f"entry failure for {self.symbol}: {e}")
                    except Exception:
                        pass
                if self.event_bus:
                    from .events import SystemFailureEvent
                    self.event_bus.publish(SystemFailureEvent(component="entry", error=str(e)))

    @staticmethod
    def _is_benign_entry_rejection(exc: Exception) -> bool:
        """True when *exc* is a definitive venue order rejection raised BEFORE any
        fill could be booked — safe to skip without halting.

        Only a CoinDCX 4xx (client/validation error: min-notional, bad params,
        insufficient balance, etc.) qualifies. The CoinDCX client raises 429/5xx/
        timeout on non-idempotent calls as 'ambiguous — reconcile against venue'
        (status_code None or >=500), which must still trip the halt."""
        from .exchanges.coindcx_client import CoinDCXError
        if not isinstance(exc, CoinDCXError):
            return False
        sc = getattr(exc, "status_code", None)
        return isinstance(sc, int) and 400 <= sc < 500 and sc != 429

    # StrategyRouter is lazily built on first use and cached.
    # Use build_legacy_router() to customise the regime → playbook map.
    _strategy_router: Optional[StrategyRouter] = None

    def _get_strategy_router(self) -> StrategyRouter:
        if self._strategy_router is None:
            self._strategy_router = build_legacy_router()
        return self._strategy_router

    def _evaluate_entry(self, df_1h, df_4h, df_15m, regime, regime_score, mark_price,
                        funding_rate, oi_delta, taker_ratio, structure=None, adx_1h=None,
                        regime_ctx: Optional[RegimeContext] = None,
                        session_ctx=None, structure_ltf=None):
        """Evaluate entry signals and execute via WebSocket LTP.

        Score-based best-of selection is delegated to :class:`StrategyRouter`.
        This method is responsible only for:
          - building the dict of playbook evaluator lambdas,
          - post-selection correlation and funding-rate vetoes,
          - dispatching to _execute_entry.
        """
        playbook_evaluators = {
            "playbook_ares":  lambda: self.playbook_ares.evaluate(df_15m, adx_1h=adx_1h),
            "playbook_volx":  lambda: self.playbook_volx.evaluate(df_15m, adx_1h=adx_1h),
            "playbook_a":     lambda: self.playbook_a.evaluate(df_1h, regime, structure=structure),
            "playbook_b":     lambda: self.playbook_b.evaluate(df_1h, df_4h, regime, structure=structure),
            "playbook_sweep": lambda: self.playbook_sweep.evaluate(
                df_1h, df_15m, structure, structure_ltf, regime=regime),
        }

        result: Optional[RouterResult] = self._get_strategy_router().select(
            regime_ctx=regime_ctx,
            playbook_evaluators=playbook_evaluators,
            advisor=self.advisor,
            dynamic_threshold=self.adaptive_threshold.get_threshold(),
            regime=regime,
            regime_score=regime_score,
        )
        if result is None:
            return

        setup = result.setup

        # Correlation check (wallet-state dependent — stays here, not in router)
        active_positions = {
            s: p.to_dict()
            for s, p in self.wallet.positions.items()
            if p.status == "OPEN"
        }
        ok, corr_reason = self.risk_manager.check_correlation(
            self.symbol, setup["side"].value, active_positions
        )
        if not ok:
            logger.info("[BLOCKED] %s", corr_reason)
            return

        if self.advisor and result.advice:
            logger.info("[FUSION] %s | final=%.2f", result.explanation, result.final_score)

        # Funding-rate extreme gate
        _funding_extreme = self.cfg.funding_extreme_threshold if self.cfg else FUNDING_EXTREME
        if (
            (setup["side"] == PositionSide.LONG and funding_rate > _funding_extreme)
            or (setup["side"] == PositionSide.SHORT and funding_rate < -_funding_extreme)
        ):
            logger.info(
                "[BLOCKED] Funding extreme for %s: %+.4%% (threshold=%.2%%)",
                setup["side"].value, funding_rate, _funding_extreme,
            )
            return

        self._execute_entry(EntryContext(
            setup=setup,
            final_score=result.final_score,
            llm_weight=result.llm_weight,
            explanation=result.explanation,
            mark_price=mark_price,
            funding_rate=funding_rate,
            oi_delta=oi_delta,
            taker_ratio=taker_ratio,
            tech_score=result.tech_score,
            regime=regime,
            regime_score=regime_score,
            advice=result.advice,
            dynamic_threshold=result.dynamic_threshold,
            regime_ctx=regime_ctx,
        ))

    def _coindcx_market_data(self):
        if self._coindcx_md is None:
            from .exchanges.coindcx_market_data import CoinDCXMarketData
            self._coindcx_md = CoinDCXMarketData()
        return self._coindcx_md

    def _basis_guard(self, side, binance_mark: float):
        """Cross-venue basis guard (F3).

        Signals fire on Binance price but fills happen on CoinDCX. Reject the
        entry when the venues diverge beyond the configured threshold. Returns
        ``(allowed, basis)``. If CoinDCX data is unavailable, skip the guard
        (don't block trading on a missing fallback feed).
        """
        cfg = self.cfg
        if cfg is None or not getattr(cfg, "basis_guard_enabled", False) or binance_mark <= 0:
            return True, 0.0
        try:
            cdcx_mark = self._coindcx_market_data().get_mark_price(self.symbol)
        except Exception as e:
            logger.warning("[BASIS] CoinDCX mark unavailable (%s); skipping guard", e)
            return True, 0.0
        if cdcx_mark <= 0:
            return True, 0.0
        basis = (cdcx_mark - binance_mark) / binance_mark
        if abs(basis) > cfg.max_cross_venue_basis:
            logger.warning(
                f"[BASIS BLOCKED] {self.symbol} basis {basis:+.4%} exceeds "
                f"{cfg.max_cross_venue_basis:.2%} (binance={binance_mark:.4f} coindcx={cdcx_mark:.4f})"
            )
            if self.event_bus:
                from .events import SignalRejectedEvent
                self.event_bus.publish(SignalRejectedEvent(
                    symbol=self.symbol,
                    reason=f"cross-venue basis {basis:+.4%} > {cfg.max_cross_venue_basis:.2%}",
                ))
            return False, basis
        return True, basis

    def _execute_entry(self, ctx_or_setup, final_score=None, llm_weight=None,
                      explanation=None, mark_price=None, funding_rate=None,
                      oi_delta=None, taker_ratio=None, tech_score=None,
                      regime=None, regime_score=None, advice=None,
                      dynamic_threshold=None, regime_ctx=None):
        """Execute entry using real-time WebSocket prices.

        Accepts either an EntryContext as the sole positional argument (new API)
        or the legacy keyword-argument form (kept for backwards compatibility).
        """
        if isinstance(ctx_or_setup, EntryContext):
            ctx = ctx_or_setup
        else:
            ctx = EntryContext(
                setup=ctx_or_setup,
                final_score=final_score,
                llm_weight=llm_weight if llm_weight is not None else 0.0,
                explanation=explanation if explanation is not None else "",
                mark_price=mark_price if mark_price is not None else 0.0,
                funding_rate=funding_rate if funding_rate is not None else 0.0,
                oi_delta=oi_delta if oi_delta is not None else 0.0,
                taker_ratio=taker_ratio if taker_ratio is not None else 1.0,
                tech_score=tech_score if tech_score is not None else 0.0,
                regime=regime,
                regime_score=regime_score if regime_score is not None else 0.0,
                advice=advice,
                dynamic_threshold=dynamic_threshold if dynamic_threshold is not None else 0.75,
                regime_ctx=regime_ctx,
            )

        setup = ctx.setup
        final_score = ctx.final_score
        llm_weight = ctx.llm_weight
        explanation = ctx.explanation
        mark_price = ctx.mark_price
        funding_rate = ctx.funding_rate
        oi_delta = ctx.oi_delta
        taker_ratio = ctx.taker_ratio
        tech_score = ctx.tech_score
        regime = ctx.regime
        regime_score = ctx.regime_score
        advice = ctx.advice
        dynamic_threshold = ctx.dynamic_threshold
        regime_ctx = ctx.regime_ctx

        # A1: never enter on stale data. If the WS feed has no fresh price within
        # the staleness budget, veto the entry rather than fall back to a possibly
        # seconds-old price. (Exits are separately gated in ws_pm.)
        stale_ms = self.cfg.feed_stale_ms if self.cfg else 15000
        if not self.ws_feed.is_fresh(stale_ms):
            age = self.ws_feed.data_age_ms()
            logger.warning("[ENTRY] WS feed stale (age=%sms > %dms) — vetoing entry", age, stale_ms)
            return

        # Get current LTP and spread from WebSocket
        ltp = self.ws_feed.get_ltp()
        mid = self.ws_feed.get_mid_price()
        spread = self.ws_feed.get_spread()

        if ltp <= 0 or mid <= 0:
            logger.warning("[ENTRY] WebSocket LTP/mid unavailable (ltp=%.4f mid=%.4f) — vetoing entry", ltp, mid)
            return

        # Slippage estimate: if spread > 0.1%, log warning
        spread_pct = spread / mid * 100 if mid > 0 else 0
        if spread_pct > 0.1:
            logger.warning(f"[ENTRY] Wide spread: {spread_pct:.3f}% | bid={self.ws_feed.data.best_bid:.2f} ask={self.ws_feed.data.best_ask:.2f}")

        # F3: cross-venue basis guard — reject if Binance and CoinDCX diverge.
        allowed, _basis = self._basis_guard(setup["side"], mid if mid > 0 else mark_price)
        if not allowed:
            return

        # Adjust entry price to use mid price (fairer than LTP which can be stale).
        # F3: nudge the trigger toward the fill venue by the basis buffer so risk
        # sizing reflects the price we'll actually fill on at CoinDCX.
        entry_price = mid
        buf = self.cfg.entry_basis_buffer if (self.cfg and getattr(self.cfg, "basis_guard_enabled", False)) else 0.0
        if buf:
            entry_price = mid * (1 + buf) if setup["side"] == PositionSide.LONG else mid * (1 - buf)

        # Re-anchor the PLAYBOOK's stop/target to the actual fill entry.
        # The playbook computed sl/tp off its signal price; the real entry (mid +
        # basis buffer) differs slightly, so we preserve the playbook's
        # proportional stop distance rather than discarding it for a flat default.
        is_long = setup["side"] == PositionSide.LONG
        pb_entry = float(setup.get("entry_price") or 0)
        default_sl_pct, default_tp_pct = DEFAULT_SL_PCT, DEFAULT_TP1_PCT

        def _reanchor(level_price, fallback_pct, is_stop):
            """Map a playbook level to the actual entry, keeping its ratio."""
            if pb_entry > 0 and level_price and float(level_price) > 0:
                return entry_price * (float(level_price) / pb_entry)
            # No usable playbook level — fall back to a flat default.
            if is_stop:
                return entry_price * (1 - fallback_pct) if is_long else entry_price * (1 + fallback_pct)
            return entry_price * (1 + fallback_pct) if is_long else entry_price * (1 - fallback_pct)

        sl = _reanchor(setup.get("sl_price"), default_sl_pct, is_stop=True)

        # Update setup with actual entry price + re-anchored stop.
        setup["entry_price"] = entry_price
        setup["sl_price"] = sl
        if "tp_price" in setup:
            setup["tp_price"] = _reanchor(setup.get("tp_price"), default_tp_pct, is_stop=False)
        else:
            for tp_level in setup.get("tp_levels", []):
                lvl_default = 0.010 if tp_level.get("label") == "TP1" else 0.020
                tp_level["price"] = _reanchor(tp_level.get("price"), lvl_default, is_stop=False)

        # Representative TP for events/logging (first target, or single tp_price).
        tp = setup.get("tp_price")
        if tp is None:
            _levels = setup.get("tp_levels", [])
            tp = _levels[0]["price"] if _levels else entry_price

        # Risk-based sizing from stop distance (2% risk per trade, scaled by this
        # engine's share of a shared wallet to avoid multi-symbol over-allocation).
        stop_distance = abs(entry_price - setup["sl_price"])
        _risk_pct = Decimal(str(self.cfg.risk_per_trade_pct)) if self.cfg else Decimal("0.02")
        risk_budget = self.wallet.margin_balance * _risk_pct * Decimal(str(self.risk_budget_fraction))
        size_multiplier = min(final_score / dynamic_threshold, 1.0)
        # Apply regime-based size scalar (e.g. 1.25× for TREND_EXPANSION, 0.5× for LOW_VOL_CHOP)
        if regime_ctx is not None and regime_ctx.size_multiplier != 1.0:
            size_multiplier *= regime_ctx.size_multiplier
            logger.debug(
                f"[SIZING] regime={regime_ctx.extended.value} size_x={regime_ctx.size_multiplier:.2f} "
                f"→ combined_multiplier={size_multiplier:.3f}"
            )
        risk_budget *= Decimal(str(size_multiplier))
        stop_distance_dec = Decimal(str(stop_distance))
        quantity = (risk_budget / stop_distance_dec) if stop_distance_dec > 0 else Decimal("0")

        trade_id = str(uuid.uuid4())[:8]

        # Without a stop we cannot size at all → hard skip (covers the
        # quantity<=0-because-stop_distance==0 case). A tiny risk_budget that
        # yields qty<=0 with a VALID stop is handled by the bump-to-minimum
        # logic below, not skipped here.
        if stop_distance_dec <= 0:
            logger.warning("[ENTRY] computed quantity <= 0 (stop_distance=%s); skipping", stop_distance)
            return

        # ── Bump-to-minimum sizing ───────────────────────────────────────────
        # On a tiny account, risk-based sizing (risk_per_trade_pct × 1/N) can
        # produce a notional below CoinDCX's venue minimum (or a quantity that
        # rounds to ~0), so the order would be rejected outright. Per operator
        # decision: bump such orders UP to the smallest venue-legal size when
        # margin allows (accepting >target risk on this trade), and skip cleanly
        # if even that minimum can't be afforded. The bumped quantity is computed
        # HERE so it flows into the margin/liq/leverage validations below AND into
        # downstream order placement (no validate-one/place-another mismatch).
        entry_price_dec = Decimal(str(entry_price))
        exec_eng = getattr(self.wallet, "execution_engine", None)
        if exec_eng is not None and hasattr(exec_eng, "mapper"):
            try:
                spec = exec_eng.mapper.get_spec(self.symbol)
                min_n = Decimal(str(spec.min_notional))
                min_q = Decimal(str(spec.min_quantity))
                cur_notional = quantity * entry_price_dec
                if quantity < min_q or cur_notional < min_n:
                    # Smallest qty satisfying BOTH min_notional and min_quantity,
                    # rounded UP to the venue quantity increment (never down — a
                    # round-down could drop us back below the minimum).
                    q_for_notional = (
                        (min_n / entry_price_dec) if entry_price_dec > 0 else min_q
                    )
                    target_qty = max(q_for_notional, min_q)
                    inc = Decimal(str(spec.quantity_increment))
                    if inc > 0:
                        steps = (target_qty / inc).to_integral_value(rounding=ROUND_UP)
                        bumped_qty = steps * inc
                    else:
                        bumped_qty = target_qty
                    # Guard against float-rounding leaving us a hair below either
                    # minimum after increment rounding.
                    while bumped_qty < min_q or (bumped_qty * entry_price_dec) < min_n:
                        bumped_qty += inc if inc > 0 else (min_q - bumped_qty)

                    bumped_notional = bumped_qty * entry_price_dec
                    # Affordability / pre-send veto: required margin must fit the
                    # margin still available after existing open positions.
                    _lev_for_afford = self.wallet.get_leverage(self.symbol) if getattr(self.wallet, "live_execution", False) else (self.cfg.leverage if self.cfg else 2)
                    required_margin = float(bumped_notional) / max(_lev_for_afford, 1)
                    margin_balance_now = float(self.wallet.margin_balance)
                    used_margin_now = sum(
                        float(p.margin_used) for p in self.wallet.positions.values()
                        if p.status == "OPEN"
                    )
                    available_margin = margin_balance_now - used_margin_now
                    if required_margin > available_margin:
                        logger.warning(
                            "[ENTRY SKIP] %s cannot afford venue minimum notional "
                            "(need ~$%.2f margin, have $%.2f); skipping",
                            self.symbol, required_margin, available_margin,
                        )
                        return

                    # Risk now exceeds the configured cap — operator MUST see this.
                    risk_now = (bumped_qty * stop_distance_dec) / self.wallet.margin_balance \
                        if self.wallet.margin_balance > 0 else Decimal("0")
                    logger.warning(
                        "[SIZING BUMP] %s risk-based notional $%.2f below venue min $%.2f "
                        "— bumping qty %s→%s (risk now ~%.3f%% of equity, exceeds target %.3f%%)",
                        self.symbol, float(cur_notional), float(min_n),
                        f"{float(quantity):.8f}", f"{float(bumped_qty):.8f}",
                        float(risk_now) * 100.0, float(_risk_pct) * 100.0,
                    )
                    quantity = bumped_qty
            except Exception as e:
                # In LIVE mode the venue enforces min-notional; without the spec we
                # cannot guarantee a legal size, so sending the risk-based qty would
                # just earn a guaranteed rejection (and churn). Skip the entry and
                # let the next tick retry once the spec is fetchable. In paper mode
                # there's no venue floor — fall back to the risk-based qty as-is.
                if self.cfg and self.cfg.is_live:
                    logger.warning(
                        "[ENTRY SKIP] %s instrument spec unavailable in live mode "
                        "(%s); cannot verify min-notional, skipping tick", self.symbol, e,
                    )
                    return
                logger.warning(f"Failed to fetch instrument spec for pre-entry validation: {e}")

        # After any bump, a still-non-positive qty means we could not size a
        # legal order (e.g. no mapper AND tiny risk_budget) → skip.
        if quantity <= 0:
            logger.warning("[ENTRY] computed quantity <= 0 (stop_distance=%s); skipping", stop_distance)
            return

        # Margin Engine Validation
        margin_balance = float(self.wallet.margin_balance)
        used_margin = sum(float(p.margin_used) for p in self.wallet.positions.values() if p.status == "OPEN")
        margin_ok, margin_msg = self.margin_engine.check_margin_utilization(used_margin, margin_balance)
        if not margin_ok:
            logger.warning(f"[ENTRY BLOCKED] Margin Utilization: {margin_msg}")
            return

        leverage_val = self.wallet.get_leverage(self.symbol) if getattr(self.wallet, "live_execution", False) else (self.cfg.leverage if self.cfg else 2)
        # Wallet uses mark-based margin: liq = entry / (1 ± 1/lev ∓ mmr)
        # This matches wallet._is_liquidation_required() so the entry gate
        # and the live liquidation check agree.
        _mmr = float(getattr(self.wallet, "maintenance_margin_ratio", 0.005))
        _inv_lev = 1.0 / max(leverage_val, 1)
        liq_price = (entry_price / (1 + _inv_lev - _mmr)
                     if is_long else
                     entry_price / (1 - _inv_lev + _mmr))
        liq_ok, liq_msg = self.margin_engine.check_liquidation_distance(
            entry_price=entry_price,
            stop_loss_price=setup["sl_price"],
            liquidation_price=liq_price,
            side=setup["side"].value
        )
        if not liq_ok:
            logger.warning(f"[ENTRY BLOCKED] Liquidation Distance: {liq_msg}")
            return

        # Leverage Engine Validation
        notional = float(quantity) * entry_price
        lev_ok, lev_msg = self.leverage_engine.validate_leverage_tier(
            requested_leverage=leverage_val,
            position_notional=notional,
            max_notional_for_tier=50000.0
        )
        if not lev_ok:
            logger.warning(f"[ENTRY BLOCKED] Leverage Tier: {lev_msg}")
            return

        # (Venue min-notional / min-quantity is enforced earlier via
        # bump-to-minimum, so the qty reaching the margin/liq/leverage checks
        # above and the placement below is already venue-legal.)

        # ── F6: Fee-adjusted expected profit gate ─────────────────────────────
        fee_gate_ok = True
        if self.cfg and getattr(self.cfg, "fee_awareness_enabled", False):
            taker_rate = float(getattr(self.wallet, "taker_fee_rate", Decimal("0.0005")))
            safety_buffer = getattr(self.cfg, "fee_safety_buffer_bps", 5.0) / 10000.0
            min_ratio = getattr(self.cfg, "min_profit_vs_fees_ratio", 1.5)

            # Conservative: assume taker on both entry and exit
            round_trip_fee = notional * taker_rate * 2.0
            total_cost = round_trip_fee + (notional * safety_buffer)

            # Expected profit to first TP (or 1% default if none set)
            tp = setup.get("tp_price")
            if not tp and setup.get("tp_levels"):
                tp = setup["tp_levels"][0].get("price")
            if tp:
                expected_profit = abs(float(tp) - entry_price) * float(quantity)
            else:
                expected_profit = notional * 0.01  # 1% default move

            if expected_profit < total_cost * min_ratio:
                logger.warning(
                    "[ENTRY BLOCKED] Fee gate: expected_profit=$%.2f < cost×ratio=$%.2f "
                    "(fees=$%.2f + buffer=$%.2f, ratio=%.1f) | notional=$%.2f",
                    expected_profit, total_cost * min_ratio,
                    round_trip_fee, notional * safety_buffer, min_ratio, notional
                )
                fee_gate_ok = False

        if not fee_gate_ok:
            return

        # ── Adaptive entry order style ────────────────────────────────────────
        # If spread is tight (< threshold) → market (speed matters).
        # If spread is wide (>= threshold) → maker_limit (fee savings worth waiting).
        cfg_style = getattr(self.cfg, "entry_order_style", "market") if self.cfg else "market"
        threshold_bps = getattr(self.cfg, "adaptive_entry_spread_threshold_bps", 2.0)
        spread_bps = spread_pct * 100.0  # convert % → bps

        if str(cfg_style).lower() == "maker_limit":
            # Global override: always use maker-limit when playbook agrees
            use_maker = str(setup.get("entry_order_style", "market")).lower() == "maker_limit"
        else:
            # Adaptive: switch to maker_limit on wide spreads
            use_maker = spread_bps >= threshold_bps
            if use_maker:
                logger.info(
                    "[ENTRY STYLE] Spread %.2f bps >= threshold %.2f bps → maker_limit",
                    spread_bps, threshold_bps
                )
        setup["entry_order_style"] = "maker_limit" if use_maker else "market"

        # Decoupled path: publish the entry as a signal. The in-process consumer
        # (shared wallet) executes it with idempotency/DLQ/PEL-recovery + a final
        # risk-gate veto, then emits TradeOpenedEvent. record_open is performed
        # exactly once by the consumer's risk gate, so we do NOT record it here.
        if self.signal_publisher is not None:
            from .execution.signal_bus import Signal
            meta = {
                "sl_price": float(setup["sl_price"]),
                "regime": regime.value if regime else "",
                "extended_regime": regime_ctx.extended.value if regime_ctx else "",
                "tech_score": float(tech_score),
                "llm_decision": "ALLOW" if final_score >= dynamic_threshold else "LLM_VETOED",
                "funding_rate": float(funding_rate),
                "oi_delta": float(oi_delta),
                "rvol": float(regime_ctx.rvol) if regime_ctx else 1.0,
                "entry_order_style": setup["entry_order_style"],
            }
            if use_maker and self.cfg:
                meta["maker_limit_timeout_s"] = float(self.cfg.maker_limit_timeout_s)
                meta["maker_limit_offset_bps"] = float(self.cfg.maker_limit_offset_bps)
                meta["maker_limit_fallback"] = str(self.cfg.maker_limit_fallback)
            if "time_stop_hours" in setup:
                meta["time_stop_hours"] = setup["time_stop_hours"]
            if "tp_price" in setup:
                meta["tp_price"] = float(setup["tp_price"])
            else:
                meta["tp_levels"] = [
                    {"price": float(t["price"]), "pct": float(t.get("pct", 1.0)),
                     "label": t.get("label", "TP")}
                    for t in setup.get("tp_levels", []) if t.get("price")
                ]
            mode = self.cfg.mode.value if self.cfg else "paper"
            self.signal_publisher.emit(Signal(
                strategy_id=f"engine_ws:{self.symbol}",
                symbol=self.symbol, side=setup["side"].value,
                quantity=float(quantity), mode=mode,
                order_type="limit" if use_maker else "market",
                price=float(entry_price), metadata=meta,
            ))
            self.adaptive_threshold.record_trade()
            logger.info("[EXECUTED→BUS] %s %s qty=%.4f @ %.4f style=%s published to execution bus",
                        self.symbol, setup["side"].value, float(quantity), float(entry_price),
                        setup["entry_order_style"])
            return

        # Direct path. For live maker-limit, acquire the passive fill lock-free
        # (never under the shared wallet lock), then book it; on a skip-fallback
        # miss, abort the entry. Paper maker-limit is simulated in open_position
        # via the setup flag. Market entries are unchanged.
        external_fill = None
        book_qty = quantity
        if use_maker and self.cfg and self.cfg.is_live:
            external_fill = self.wallet.acquire_live_entry_fill(
                self.symbol, setup["side"], quantity, Decimal(str(entry_price)),
                timeout_s=self.cfg.maker_limit_timeout_s,
                offset_bps=self.cfg.maker_limit_offset_bps,
                fallback=self.cfg.maker_limit_fallback,
            )
            if external_fill is None:
                logger.info("[MAKER-LIMIT] %s entry skipped (unfilled, fallback=skip)", self.symbol)
                return
            fq = external_fill.get("filled_quantity")
            if fq is not None:
                book_qty = Decimal(str(fq))

        pos = self.wallet.open_position(
            self.symbol,
            setup,
            entry_price,
            custom_margin=None,
            custom_quantity=book_qty,
            external_fill=external_fill,
        )

        if pos:
            self.risk_manager.record_open()
            self.adaptive_threshold.record_trade()

            if setup.get("strategy") == "mean_reversion":
                self.mr_state.record_entry(
                    side=setup["side"].value,
                    price=float(entry_price),
                    qty=float(book_qty),
                )

            # Calculate slippage
            intended = setup["entry_price"]
            actual = entry_price
            slippage = abs(actual - intended) / intended * 100 if intended > 0 else 0

            self.journal.log_open(
                trade_id=trade_id,
                symbol=self.symbol,
                regime=regime.value if regime else "",
                regime_score=regime_score,
                setup=setup,
                technical_score=tech_score,
                llm_advice=advice.to_dict() if self.advisor and advice else None,
                llm_weight=llm_weight,
                final_score=final_score,
                margin=pos.margin_used,
                notional=pos.notional,
                entry_price=entry_price,
                funding_rate=funding_rate,
                oi_delta=oi_delta,
                taker_ratio=taker_ratio,
            )

            # Cache open-side context for the outcome record built at close time.
            _has_advice = bool(self.advisor and advice)
            _llm_rationale = None
            if _has_advice:
                _factors = getattr(advice, "key_factors", None)
                if _factors:
                    _llm_rationale = "; ".join(str(f) for f in _factors)
                elif getattr(advice, "veto_reason", None):
                    _llm_rationale = advice.veto_reason
            # entry_band: per-strategy band where available (MR playbook), else cfg.
            _entry_band = setup.get("entry_band")
            if _entry_band is None and self.cfg is not None:
                _entry_band = getattr(self.cfg, "mr_entry_band", None)
            self._open_features[self.symbol] = {
                "trade_id": trade_id,
                "side": setup["side"].value,
                "opened_at": int(datetime.now(timezone.utc).timestamp() * 1000),
                "entry_price": float(entry_price),
                "quantity": float(book_qty),
                # stop loss price stashed so pnl_r can be computed at close from
                # initial_risk = |entry - stop| * quantity.
                "stop_loss_price": float(setup["sl_price"]) if setup.get("sl_price") else None,
                "regime": regime.value if regime else None,
                "regime_score": regime_score,
                # vol/extended regime descriptor (TREND_EXPANSION, LOW_VOL_CHOP, …).
                "vol_regime": regime_ctx.extended.value if regime_ctx else None,
                "funding_rate": funding_rate,
                "oi_delta": oi_delta,
                "session": regime_ctx.session_name if regime_ctx else None,
                "entry_reason": setup.get("strategy") or setup.get("playbook"),
                "llm_action": (advice.to_dict().get("bias") if _has_advice else None),
                "llm_confidence": (advice.confidence if _has_advice else None),
                "llm_rationale": _llm_rationale,
                "entry_band": float(_entry_band) if _entry_band is not None else None,
                "stop_loss_pct": setup.get("stop_loss_pct"),
                "risk_per_trade_pct": getattr(self.cfg, "risk_per_trade_pct", None) if self.cfg else None,
                "leverage": int(self.wallet.leverage),
            }

            logger.info(
                f"[EXECUTED] Trade {trade_id} | Entry={entry_price:.2f} | "
                f"Margin={pos.margin_used:.2f} | Score={final_score:.2f} | "
                f"Spread={spread_pct:.3f}% | Slippage={slippage:.3f}%"
            )

            # Publish Event for Telegram
            if self.event_bus:
                from .events import TradeOpenedEvent
                self.event_bus.publish(TradeOpenedEvent(
                    symbol=self.symbol,
                    side=setup["side"].value,
                    leverage=self.wallet.leverage,
                    entry_price=entry_price,
                    stop_loss=sl,
                    take_profit=tp,
                    margin=pos.margin_used,
                    notional=pos.notional,
                    regime=regime.value if regime else "",
                    tech_score=tech_score,
                    llm_decision="ALLOW" if final_score >= dynamic_threshold else "LLM_VETOED",
                    funding=funding_rate,
                    oi_delta=oi_delta,
                    liquidation_price=float(self.wallet.liquidation_price(pos)),
                    wallet_balance=float(self.wallet.wallet_balance),
                ))

    # ── WebSocket Callbacks ──

    def _on_mark_price(self, mark_price: float, funding_rate: float):
        """Called every 1s when mark price updates."""
        # Can be used for real-time PnL display or alerts
        pass

    def _on_kline(self, interval: str, candle: dict):
        """Called when kline updates (every candle close)."""
        if candle.get("is_closed"):
            logger.debug(f"[WS] {interval} candle closed: {candle['close']:.2f}")

    def _on_book_ticker(self, bid: float, ask: float):
        """Called when best bid/ask changes."""
        # Can be used for spread monitoring
        pass

    # ── Backtest (REST-only mode) ──

    def backtest(self, days: int = 14) -> pd.DataFrame:
        """Run walk-forward backtest using REST data only."""
        from .engine import TradingEngine
        # Use the REST-only engine for backtest
        rest_engine = TradingEngine(
            symbol=self.symbol,
            initial_balance=self.wallet.wallet_balance,
            leverage=self.wallet.leverage,
        )
        return rest_engine.backtest(days=days)


def main():
    parser = argparse.ArgumentParser(description="Crypto Trader v4 — WebSocket Edition")
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL)
    parser.add_argument("--balance", type=float, default=1_000.0)
    parser.add_argument("--leverage", type=int, default=LEVERAGE)
    parser.add_argument("--no-llm", action="store_true")
    parser.add_argument("--llm-host", default=None, help="Ollama host URL (defaults to OLLAMA_HOST env var)")
    parser.add_argument("--llm-model", default=None, help="Ollama model name (defaults to OLLAMA_MODEL env var)")
    parser.add_argument("--log-responses", action="store_true", help="Log all REST API, WS, and LLM JSON outputs (master toggle)")
    parser.add_argument("--log-rest", action="store_true", help="Log Binance REST API request/response JSON")
    parser.add_argument("--log-ws", action="store_true", help="Log Binance WebSocket message JSON")
    parser.add_argument("--log-llm", action="store_true", help="Log Ollama LLM prompt and response JSON")
    parser.add_argument("--tick", type=int, default=300, help="Signal tick interval (seconds)")
    parser.add_argument("--backtest-days", type=int, default=None)
    args = parser.parse_args()

    from .logger_config import configure_colored_logging
    configure_colored_logging(level=logging.INFO)

    engine = WebSocketTradingEngine(
        symbol=args.symbol,
        initial_balance=args.balance,
        leverage=args.leverage,
        use_llm=not args.no_llm,
        llm_host=args.llm_host,
        llm_model=args.llm_model,
        log_responses=args.log_responses,
        log_rest=args.log_rest,
        log_ws=args.log_ws,
        log_llm=args.log_llm,
    )

    if args.backtest_days:
        logger.info(f"Backtesting {args.backtest_days} days...")
        df = engine.backtest(days=args.backtest_days)
        print(df.tail(20).to_string(index=False))
        engine.wallet.print_summary()
    else:
        engine.run_loop(signal_interval_seconds=args.tick)


if __name__ == "__main__":
    main()
