"""
crypto_trader.websocket — Real-Time Binance Futures WebSocket Client
======================================================================
Streams:
    • @markPrice — mark price + funding rate (every 1s or 3s)
    • @kline_1h / @kline_4h — candle updates
    • @bookTicker — best bid/ask (LTP for entries/exits)
    • @aggTrade — recent trades for volume/sentiment

Architecture:
    - Single WebSocket connection per symbol
    - Async thread for non-blocking reception
    - Thread-safe ring buffer for latest data
    - Auto-reconnect with exponential backoff
    - Heartbeat/ping-pong handling

Author: Generated by Kimi K2.6
"""

import os
from decimal import Decimal
import json
import time
import logging
import threading
from dataclasses import dataclass, field
from typing import Optional, Dict, List, Callable, Any
from collections import deque

import websocket

logger = logging.getLogger("crypto_trader.websocket")

BINANCE_WS_BASE = "wss://fstream.binance.com"
BINANCE_WS_TESTNET = "wss://stream.binancefuture.com"


@dataclass
class WSMarketData:
    """Latest market data snapshot from all streams."""
    symbol: str
    mark_price: float = 0.0
    index_price: float = 0.0
    funding_rate: float = 0.0
    next_funding_time: int = 0
    best_bid: float = 0.0
    best_bid_qty: float = 0.0
    best_ask: float = 0.0
    best_ask_qty: float = 0.0
    last_price: float = 0.0       # LTP from aggTrade
    last_qty: float = 0.0
    volume_24h: float = 0.0
    price_change_24h: float = 0.0
    high_24h: float = 0.0
    low_24h: float = 0.0
    kline_1h: Optional[dict] = None
    kline_4h: Optional[dict] = None
    last_update_ms: int = 0
    is_connected: bool = False

    # Track freshness of individual price sources (in local time ms)
    last_price_time_ms: int = 0
    book_ticker_time_ms: int = 0
    mark_price_time_ms: int = 0


class BinanceWebSocketFeed:
    """
    Manages a single WebSocket connection streaming multiple topics.

    Streams subscribed:
        {symbol}@markPrice@1s      → mark price + funding (1s)
        {symbol}@kline_1h          → 1H candle updates
        {symbol}@kline_4h          → 4H candle updates
        {symbol}@bookTicker        → best bid/ask (LTP)
        {symbol}@aggTrade          → recent trades
        {symbol}@ticker            → 24h stats
    """

    def __init__(
        self,
        symbol: str,
        testnet: bool = False,
        on_mark_price: Optional[Callable] = None,
        on_kline: Optional[Callable] = None,
        on_book_ticker: Optional[Callable] = None,
        reconnect_base: float = 1.0,
        reconnect_max: float = 60.0,
        log_responses: bool = False,
    ):
        self.symbol = symbol.lower()
        self.testnet = testnet
        self.on_mark_price = on_mark_price
        self.on_kline = on_kline
        self.on_book_ticker = on_book_ticker
        self.reconnect_base = reconnect_base
        self.reconnect_max = reconnect_max
        self.log_responses = log_responses or os.getenv("LOG_BINANCE_RESPONSES", "false").lower() in ("true", "1", "yes")

        self.ws: Optional[websocket.WebSocketApp] = None
        self.data = WSMarketData(symbol=symbol.upper())
        self._lock = threading.RLock()
        self._thread: Optional[threading.Thread] = None
        self._running = False
        self._reconnect_attempts = 0
        self._last_ping = 0

    # ── Public API ──

    def start(self):
        """Start WebSocket connection in background thread."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()
        logger.info(f"[WS] Starting WebSocket for {self.symbol}")

    def stop(self):
        """Gracefully stop WebSocket."""
        self._running = False
        if self.ws:
            self.ws.close()
        if self._thread:
            self._thread.join(timeout=5)
        logger.info(f"[WS] Stopped WebSocket for {self.symbol}")

    def get_data(self) -> WSMarketData:
        """Thread-safe access to latest market data."""
        with self._lock:
            return self.data

    def get_ltp(self) -> float:
        """Get Last Traded Price (from aggTrade, bookTicker mid, or markPrice) using freshness logic."""
        with self._lock:
            now_ms = int(time.time() * 1000)
            
            # 1. Prefer last trade price (aggTrade) if it's fresh (within last 10 seconds)
            if self.data.last_price > 0 and (now_ms - self.data.last_price_time_ms) < 10000:
                return self.data.last_price
                
            # 2. Fallback to mid price from book ticker if it's fresh (within last 10 seconds)
            mid = self.get_mid_price()
            if mid > 0 and (now_ms - self.data.book_ticker_time_ms) < 10000:
                return mid
                
            # 3. Fallback to mark price if it's fresh (within last 10 seconds)
            if self.data.mark_price > 0 and (now_ms - self.data.mark_price_time_ms) < 10000:
                return self.data.mark_price
                
            # 4. Ultimate fallback: return whichever is non-zero, starting with last_price, then mid, then mark_price
            if self.data.last_price > 0:
                return self.data.last_price
            if mid > 0:
                return mid
            return self.data.mark_price

    def get_spread(self) -> float:
        """Get current bid-ask spread."""
        with self._lock:
            if self.data.best_ask > 0 and self.data.best_bid > 0:
                return self.data.best_ask - self.data.best_bid
            return 0.0

    def get_mid_price(self) -> float:
        """Get mid price (average of best bid/ask)."""
        with self._lock:
            if self.data.best_ask > 0 and self.data.best_bid > 0:
                return (self.data.best_ask + self.data.best_bid) / 2
            return self.data.mark_price

    def is_connected(self) -> bool:
        """Check if WebSocket is connected AND receiving data recently."""
        with self._lock:
            if not self.data.is_connected:
                return False
            
            # If we just connected in the last 20 seconds, we're "connected" even if no data yet
            now_ms = int(time.time() * 1000)
            if (now_ms - self.data.last_update_ms) > 1000000000: # Initial state (0)
                 # Grace period of 20 seconds after opening the connection
                 return True 

            # Otherwise, must have received a message in the last 20 seconds
            return (now_ms - self.data.last_update_ms) < 20000

    # ── Internal ──

    def _run_loop(self):
        """Main loop: connect → receive → reconnect on failure."""
        while self._running:
            try:
                self._connect()
                # Do not reset reconnect_attempts here; wait until first data is received successfully in _on_message.
                # Block until connection closes
                self.ws.run_forever(
                    ping_interval=30,
                    ping_timeout=15,
                )
            except Exception as e:
                logger.error(f"[WS] Connection error: {e}")

            if not self._running:
                break

            # Exponential backoff
            self._reconnect_attempts += 1
            sleep_time = min(self.reconnect_base * (2 ** (self._reconnect_attempts - 1)), self.reconnect_max)
            logger.warning(f"[WS] Reconnecting in {sleep_time:.1f}s (attempt {self._reconnect_attempts})")
            time.sleep(sleep_time)

    def _connect(self):
        """Establish WebSocket connection and subscribe to streams."""
        base = BINANCE_WS_TESTNET if self.testnet else BINANCE_WS_BASE
        # Combined stream: /stream?streams=topic1/topic2/...
        # Simplified stream list to ensure maximum compatibility
        streams = "/".join([
            f"{self.symbol}@markPrice",
            f"{self.symbol}@kline_1h",
            f"{self.symbol}@kline_4h",
            f"{self.symbol}@bookTicker",
            f"{self.symbol}@aggTrade",
            f"{self.symbol}@ticker",
        ])
        url = f"{base}/stream?streams={streams}"

        self.ws = websocket.WebSocketApp(
            url,
            on_open=self._on_open,
            on_message=self._on_message,
            on_error=self._on_error,
            on_close=self._on_close,
            on_ping=self._on_ping,
            on_pong=self._on_pong,
        )
        logger.info(f"[WS] Connecting to {url}")

    def _on_open(self, ws):
        logger.info(f"[WS] Connected to {self.symbol}")
        with self._lock:
            self.data.is_connected = True

    def _on_close(self, ws, close_status_code, close_msg):
        logger.warning(f"[WS] Closed: {close_status_code} {close_msg}")
        with self._lock:
            self.data.is_connected = False
            self.data.last_price = 0.0 # Reset to force refresh
            self.data.mark_price = 0.0
            self.data.last_price_time_ms = 0
            self.data.book_ticker_time_ms = 0
            self.data.mark_price_time_ms = 0

    def _on_error(self, ws, error):
        logger.error(f"[WS] Error: {error}")

    def _on_ping(self, ws, message):
        self._last_ping = time.time()

    def _on_pong(self, ws, message):
        pass

    def _on_message(self, ws, message):
        """Parse incoming WebSocket message and update state."""
        if self.log_responses:
            logger.info(f"[WS Message] Raw: {message}")
        try:
            payload = json.loads(message)
            # Combined stream wraps data in "data" field with "stream" topic
            if "stream" in payload and "data" in payload:
                stream = payload["stream"]
                data = payload["data"]
            else:
                # Direct stream (single topic)
                stream = ""
                data = payload

            with self._lock:
                if self.data.last_update_ms == 0:
                    msg = f"[WS] >>> FIRST DATA RECEIVED FOR {self.symbol.upper()} <<<"
                    print(msg) # Explicit print to bypass logging propagation issues
                    logger.info(msg)
                    # Reset reconnection attempts only when we successfully receive the first live message
                    self._reconnect_attempts = 0
                self.data.last_update_ms = int(time.time() * 1000)
                self._route_message(stream, data)

        except Exception as e:
            logger.error(f"[WS] Message parse error: {e}")

    def _route_message(self, stream: str, data: dict):
        """Route message to appropriate handler based on stream type."""
        event = data.get("e", "").lower()
        stream_lower = stream.lower()

        # Debug: log every event type once
        if not hasattr(self, "_seen_events"): self._seen_events = set()
        if event not in self._seen_events:
            logger.info(f"[WS] New event type seen for {self.symbol}: {event} (Stream: {stream})")
            self._seen_events.add(event)

        if event == "markpriceupdate" or "markprice" in stream_lower:
            self._handle_mark_price(data)
        elif event == "kline" or "kline" in stream_lower:
            self._handle_kline(data)
        elif event == "bookticker" or "bookticker" in stream_lower:
            self._handle_book_ticker(data)
        elif event == "aggtrade" or "aggtrade" in stream_lower:
            self._handle_agg_trade(data)
        elif event == "24hrticker" or "ticker" in stream_lower:
            self._handle_ticker(data)

    def _handle_mark_price(self, data: dict):
        price = float(data.get("p", 0))
        if price > 0:
            self.data.mark_price = price
            self.data.index_price = float(data.get("i", 0))
            self.data.funding_rate = float(data.get("r", 0))
            self.data.next_funding_time = int(data.get("T", 0))
            self.data.mark_price_time_ms = int(time.time() * 1000)
            if self.on_mark_price:
                self.on_mark_price(self.data.mark_price, self.data.funding_rate)

    def _handle_kline(self, data: dict):
        k = data.get("k", {})
        interval = k.get("i", "")
        candle = {
            "open_time": k.get("t"),
            "open": float(k.get("o", 0)),
            "high": float(k.get("h", 0)),
            "low": float(k.get("l", 0)),
            "close": float(k.get("c", 0)),
            "volume": float(k.get("v", 0)),
            "quote_volume": float(k.get("q", 0)),
            "trades": int(k.get("n", 0)),
            "is_closed": k.get("x", False),
        }
        if interval == "1h":
            self.data.kline_1h = candle
        elif interval == "4h":
            self.data.kline_4h = candle
        if self.on_kline:
            self.on_kline(interval, candle)

    def _handle_book_ticker(self, data: dict):
        self.data.best_bid = float(data.get("b", 0))
        self.data.best_bid_qty = float(data.get("B", 0))
        self.data.best_ask = float(data.get("a", 0))
        self.data.best_ask_qty = float(data.get("A", 0))
        self.data.book_ticker_time_ms = int(time.time() * 1000)
        
        # If we don't have a last_price or mark_price yet, initialize them from the book ticker mid-price
        if self.data.best_bid > 0 and self.data.best_ask > 0:
            mid = (self.data.best_bid + self.data.best_ask) / 2.0
            if self.data.last_price == 0.0:
                self.data.last_price = mid
                self.data.last_price_time_ms = self.data.book_ticker_time_ms
            if self.data.mark_price == 0.0:
                self.data.mark_price = mid
                self.data.mark_price_time_ms = self.data.book_ticker_time_ms

        if self.on_book_ticker:
            self.on_book_ticker(self.data.best_bid, self.data.best_ask)

    def _handle_agg_trade(self, data: dict):
        price = float(data.get("p", 0))
        if price > 0:
            self.data.last_price = price
            self.data.last_qty = float(data.get("q", 0))
            self.data.last_price_time_ms = int(time.time() * 1000)

    def _handle_ticker(self, data: dict):
        self.data.volume_24h = float(data.get("v", 0))
        self.data.price_change_24h = float(data.get("P", 0))
        self.data.high_24h = float(data.get("h", 0))
        self.data.low_24h = float(data.get("l", 0))


class WebSocketPositionManager:
    """
    High-frequency position manager using WebSocket LTP.

    Instead of polling REST every 5 minutes, this reacts to 
    every mark price update (1s) for SL/TP/Trail checks.

    Uses a ring buffer for recent prices to detect wicks vs sustained moves.
    """

    def __init__(
        self,
        ws_feed: BinanceWebSocketFeed,
        wallet,
        check_interval_ms: int = 1000,  # Check every 1s
        wick_buffer_size: int = 5,       # 5 samples = 5s
        event_bus = None,
    ):
        self.ws = ws_feed
        self.wallet = wallet
        self.event_bus = event_bus
        self.symbol = self.ws.symbol.upper()
        self.check_interval_ms = check_interval_ms
        self.wick_buffer = deque(maxlen=wick_buffer_size)
        self._running = False
        self._thread: Optional[threading.Thread] = None
        self._last_log_time = 0

    def start(self):
        """Start high-frequency position monitoring."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(target=self._monitor_loop, daemon=True)
        self._thread.start()
        logger.info("[WS-PM] Position manager started")

    def stop(self):
        self._running = False
        if self._thread:
            self._thread.join(timeout=2)
        logger.info("[WS-PM] Position manager stopped")

    def _monitor_loop(self):
        """Main loop: check positions against real-time LTP."""
        while self._running:
            try:
                # Must be connected AND have received at least one price update
                if not self.ws.is_connected():
                    time.sleep(1)
                    continue

                # Use LTP (last traded price) for execution
                data = self.ws.get_data()
                ltp = self.ws.get_ltp()
                mid = self.ws.get_mid_price()

                if ltp <= 0:
                    # Still waiting for the first message on a new connection
                    time.sleep(0.5)
                    continue

                # Add to wick buffer
                self.wick_buffer.append({
                    "ltp": ltp,
                    "mid": mid,
                    "mark": data.mark_price,
                    "time": data.last_update_ms,
                })

                # Log heartbeat every 30 seconds to confirm loop is alive
                now = time.time()
                if not hasattr(self, "_last_heartbeat"): self._last_heartbeat = 0
                if now - self._last_heartbeat >= 30:
                    logger.debug(f"[WS-PM] Loop heartbeat for {self.symbol} | LTP: {ltp:.2f}")
                    self._last_heartbeat = now

                # Check positions
                pos = self.wallet.get_open_position(self.symbol)
                if pos:
                    self._check_exits(pos, data, ltp, mid)

                time.sleep(self.check_interval_ms / 1000)

            except Exception as e:
                logger.error(f"[WS-PM] Monitor error: {e}")
                time.sleep(1)

    def _check_exits(self, pos, data: WSMarketData, ltp: float, mid: float):
        """Check all exit conditions using real-time prices."""
        # Use mid price for SL/TP to avoid wick hunting
        # Use LTP for trailing stops (more reactive)

        price_for_sl_tp = Decimal(str(mid))  # Mid price = fairer execution
        price_for_trail = Decimal(str(ltp))  # LTP = faster reaction

        # Update PnL using real-time LTP for higher reactivity
        pos.update_pnl(price_for_trail)
        pnl = pos.unrealized_pnl
        
        # Sync global wallet total on EACH tick
        self.wallet._sync_unrealized_total()

        # Log live PnL every 10 seconds
        now = time.time()
        if now - self._last_log_time >= 10:
            pnl_pct = (pnl / pos.margin_used) * 100 if pos.margin_used > 0 else 0
            logger.info(f"[LIVE] {pos.symbol} {pos.side.value} | PnL: {pnl:+.2f} USDT ({pnl_pct:+.2f}%) | Price: {ltp:.2f}")
            self._last_log_time = now

        # 1. Catastrophic SL
        cat_sl = pos.margin_used * Decimal(str(self.wallet.catastrophic_sl_pct))
        if pnl <= cat_sl:
            self._handle_close(data.mark_price, f"CATASTROPHIC_SL ({pnl:.2f})")
            return

        # 2. Playbook-specific exits
        from .wallet import Playbook
        if pos.playbook == Playbook.INTRADAY:
            self._check_intraday(pos, price_for_sl_tp, data)
        elif pos.playbook == Playbook.SWING:
            self._check_swing(pos, price_for_sl_tp, price_for_trail, data)

    def _check_intraday(self, pos, price: float, data: WSMarketData):
        from .wallet import PositionSide
        # Simple TP/SL using mid price
        if pos.side == PositionSide.LONG:
            if pos.tp_levels and price >= pos.tp_levels[0]["price"]:
                reason = f"TP_HIT ({pos.unrealized_pnl:.2f})"
                self._handle_close(price, reason)
                return
            if price <= pos.sl_price:
                reason = f"SL_HIT ({pos.unrealized_pnl:.2f})"
                self._handle_close(price, reason)
                return
        else:
            if pos.tp_levels and price <= pos.tp_levels[0]["price"]:
                reason = f"TP_HIT ({pos.unrealized_pnl:.2f})"
                self._handle_close(price, reason)
                return
            if price >= pos.sl_price:
                reason = f"SL_HIT ({pos.unrealized_pnl:.2f})"
                self._handle_close(price, reason)
                return

        # Time stop (using candle time from WS kline)
        if data.kline_1h and data.kline_1h.get("is_closed"):
            # Approximate: use last closed candle time
            pass  # Time stop handled by engine tick

    def _check_swing(self, pos, price_sl_tp: Decimal, price_trail: Decimal, data: WSMarketData):
        from .wallet import PositionSide
        # Scaled exits using mid price
        for tp in pos.tp_levels:
            if tp["hit"]:
                continue
            hit = False
            tp_price = Decimal(str(tp["price"]))
            if pos.side == PositionSide.LONG and price_sl_tp >= tp_price:
                hit = True
            elif pos.side == PositionSide.SHORT and price_sl_tp <= tp_price:
                hit = True

            if hit:
                self.wallet.partial_close(self.symbol, price_sl_tp, tp["pct"], f"{tp['label']} HIT", tp_label=tp["label"])
                if tp["label"] == "TP1":
                    self.wallet.adjust_sl_price(self.symbol, pos.entry_price)
                elif tp["label"] == "TP2":
                    self.wallet.activate_trailing_stop(self.symbol)
                return

        # SL check
        sl_price = Decimal(str(pos.sl_price))
        if pos.side == PositionSide.LONG and price_sl_tp <= sl_price:
            self._handle_close(price_sl_tp, f"SL_HIT ({pos.unrealized_pnl:.2f})")
            return
        elif pos.side == PositionSide.SHORT and price_sl_tp >= sl_price:
            self._handle_close(price_sl_tp, f"SL_HIT ({pos.unrealized_pnl:.2f})")
            return

        # Trailing stop using LTP (more reactive to momentum)
        if pos.trailing_active:
            if pos.side == PositionSide.LONG:
                if not hasattr(pos, '_highest_since_tp2'):
                    pos._highest_since_tp2 = pos.entry_price
                highest = Decimal(str(pos._highest_since_tp2))
                pos._highest_since_tp2 = max(highest, price_trail)
                trail_price = pos._highest_since_tp2 * Decimal("0.995")  # 0.5% trail
                if price_trail < trail_price:
                    self._handle_close(price_trail, f"TRAIL_STOP (0.5% from {pos._highest_since_tp2:.2f})")
                    return
            else:
                if not hasattr(pos, '_lowest_since_tp2'):
                    pos._lowest_since_tp2 = pos.entry_price
                lowest = Decimal(str(pos._lowest_since_tp2))
                pos._lowest_since_tp2 = min(lowest, price_trail)
                trail_price = pos._lowest_since_tp2 * Decimal("1.005")
                if price_trail > trail_price:
                    self._handle_close(price_trail, f"TRAIL_STOP (0.5% from {pos._lowest_since_tp2:.2f})")
                    return

    def _handle_close(self, price: Any, reason: str):
        """Internal helper to close position and publish event."""
        # Ensure price is converted to float for event and wallet if needed
        f_price = float(price)
        closed_pos = self.wallet.close_position(self.symbol, f_price, reason)
        if closed_pos and self.event_bus:
            from .events import TradeClosedEvent
            # Calculate metrics
            pnl_pct = (float(closed_pos.realized_pnl) / float(closed_pos.margin_used) * 100) if float(closed_pos.margin_used) > 0 else 0
            duration = (time.time() - closed_pos.open_time / 1000) / 60 if hasattr(closed_pos, 'open_time') else 0
            
            self.event_bus.publish(TradeClosedEvent(
                symbol=self.symbol,
                side=closed_pos.side.value,
                realized_pnl=float(closed_pos.realized_pnl),
                pnl_percent=pnl_pct,
                exit_price=f_price,
                reason=reason,
                duration_minutes=duration
            ))
